feat: add jvm credentials provider & include it in default credentials provider chain
aws/aws-sdk-kotlin pull request #1037
Opened 2023-08-31 20:46 UTC by 0marperez

## Issue \#

closes #1033 

## Description of changes

-Created JVM credentials provider
-Added it to the default credentials provider chain as the first one 

It's essentially a copy of the environment credentials provider

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-31 21:32 UTC, lauzadis requested changes
Pretty great first attempt! I had a few smaller comments

2023-08-31 21:32 UTC, lauzadis commented on .changes/ec4b3c6c-c63f-499d-a032-026139b4627e.json
> +    "description": "Add Jvm credentails provider and make it first in default chain credentials provider",
nit: "Jvm credentails" -> "JVM system property credentials"

2023-08-31 21:32 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/JvmCredentialsProvider.kt
> +public class JvmCredentialsProvider
nit: I'd call this the `JvmSystemPropertyCredentialsProvider`. There can be different types of credentials providers used on JVM, so `JvmCredentialsProvider` seems too vague to me.

Same comment applies everywhere just "JVM" is used.

2023-08-31 21:32 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/JvmCredentialsProvider.kt
> +        getProperty(variable) ?: throw ProviderConfigurationException("Missing value for JVM system properties `$variable`")
nit: "for JVM system **property**"

2023-08-31 21:32 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/JvmCredentialsProvider.kt
> +    public constructor() : this(PlatformProvider.System::getProperty)
Instead of two constructors you can just have one which defaults to `PlatformProvider.System::getProperty`

```kt
public constructor(private val getProperty: (String) -> String? = PlatformProvider.System::getProperty)
```

2023-08-31 21:32 UTC, lauzadis commented on aws-runtime/aws-config/jvm/test/aws/sdk/kotlin/runtime/auth/credentials/DefaultChainCredentialsProviderTest.kt
> +        private val jvm: Map<String, String>,
nit: jvmSystemProperties

2023-08-31 22:20 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/JvmCredentialsProvider.kt
> +public class JvmCredentialsProvider
I agree `JvmCredentialsProvider` is too vague but I don't think the JVM part is important. Sure, it'd only work on JVM _for now_ but there may be other future platforms which have some kind of system properties. I'd suggest `SystemPropertyCredentialsProvider`.

2023-08-31 22:32 UTC, ianbotsf reviewed
My comment about JVM not being the important part applies for names/strings/docs across the whole PR.

2023-08-31 22:32 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/JvmCredentialsProvider.kt
> +public class JvmCredentialsProvider
**Nit**: Needs KDocs, which should indicate exactly which system properties will be used.

2023-08-31 22:32 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/JvmCredentialsProvider.kt
> +        coroutineContext.trace<EnvironmentCredentialsProvider> {
**Nit**: Copy/paste error

2023-09-01 15:09 UTC, lauzadis approved these changes

2023-09-07 13:21 UTC, merged