fix: add content type header to empty body rest xml payloads
aws/aws-sdk-kotlin pull request #1073
Opened 2023-10-11 18:29 UTC by 0marperez

## Issue \#

closes #1050 
## Description of changes

-Empty body rest xml payloads will have the content type header added to them

Related to: 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-11 20:58 UTC, ianbotsf approved these changes

2023-10-12 12:48 UTC, aajtodd requested changes

2023-10-12 12:48 UTC, aajtodd commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/RestXml.kt
> +    override fun renderContentTypeHeader(
**suggestion**: We have [other](https://github.com/awslabs/aws-sdk-kotlin/blob/852fe92843713191d4948efeaf610bba2a635e67/codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/RestJson1.kt#L62) cases where we end up having to override when/how the content-type header is set. I suggest looking at the generated code for this case and any others and reconciling with the addition of `renderContentTypeHeader`.

2023-10-12 12:48 UTC, aajtodd commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/RestXml.kt
> +        if (!op.isBlobShape) {
**correctness**: `op` is of type `OperationShape`, this expression is never true.

2023-10-31 17:59 UTC, aajtodd requested changes

2023-10-31 17:59 UTC, aajtodd commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/RestJson1.kt
> +    override fun renderContentTypeHeader(
This isn't right, it's setting the content type header _always_ instead of predicating on whether the body is empty or not like it does in the base class. Looking at this closer I'd ignore my previous [suggestion](https://github.com/awslabs/aws-sdk-kotlin/pull/1073/files#r1356763978) and keep the inline customization to set content type on L62. I thought we could reconcile them but you'll just end up with repeated runtime checks.

2023-10-31 17:59 UTC, aajtodd commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/RestXml.kt
> +        val contentType = resolver.determineRequestContentType(op)
This is _always_ going to set the content type header when the failing test was restricted to union shapes. We should predicate this on that instead of overriding it for the entire protocol.

2023-11-10 13:30 UTC, aajtodd requested changes

2023-11-10 13:30 UTC, aajtodd commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/RestXml.kt
> +        if (op.inputIsUnionShape(ctx.model)) {
**fix**: You have overridden this for the entire protocol but are now only handling the new case. You need to be calling `super.renderContentTypeHeader(...)` somewhere in this function as the default code path and only special case the union shape requirement for content type.

2023-11-10 18:28 UTC, aajtodd approved these changes

2023-11-14 17:43 UTC, merged