feat: request compression trait
aws/aws-sdk-kotlin pull request #1120
Opened 2023-11-20 03:15 UTC by 0marperez

## Issue \#
N/A

## Description of changes
Adds request compression trait settings and interceptor to compress requests.

See also:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-11-24 16:11 UTC, lauzadis requested changes
Nice! This is a great start, there are a few small improvements to be made

2023-11-24 16:11 UTC, lauzadis commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/requestcompression/RequestCompressionTrait.kt
> +    override val name: String = "RequestCompressionTrait"
naming: `RequestCompressionTraitMiddleware`

(I am trying to avoid using `RequestCompressionTrait` because that name is already used by the trait itself)

2023-11-24 16:11 UTC, lauzadis commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/requestcompression/RequestCompressionTrait.kt
> +            val requestedCompressionAlgorithms = trait.encodings
naming: `supportedCompressionAlgorithms` (these are not the algorithms requested by the user, they are the ones the service supports)

2023-11-28 15:33 UTC, aajtodd commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/AwsServiceConfigIntegration.kt
> +        add(RequestMinCompressionSizeBytes)
Yeah as I commented elsewhere this belongs in it's own `KotlinIntegration` in `smithy-kotlin`

2023-11-28 19:48 UTC, 0marperez commented on codegen/sdk/aws-models/s3.json
> +                  "encodings": ["gzip"]
I'll remove this for the final review. It's here for testing purposes

2023-12-05 14:48 UTC, lauzadis approved these changes
Nice!

2023-12-05 14:48 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/compression/ResolveDisableRequestCompression.kt
> +    CompressionSettings.AwsDisableRequestCompression.resolve(platform) ?: profile.get().disableRequestCompression
nit: return the default value `false` here

same for `10240` min compression size

2023-12-05 14:48 UTC, lauzadis commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/core/AwsHttpBindingProtocolGenerator.kt
>          )
nit: `ignoredTests` is unused

2023-12-13 15:52 UTC, lauzadis approved these changes

2023-12-13 17:03 UTC, aajtodd requested changes
Question: Are there any services that have enabled `gzip` that we can write an integration test against?

2023-12-18 19:33 UTC, aajtodd approved these changes

2023-12-20 18:07 UTC, merged