feat: allow full URI path to a localhost metadata service to be a hostname
aws/aws-sdk-kotlin pull request #1182
Opened 2024-01-19 20:57 UTC by 0marperez

## Issue \#
closes #476

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-01-19 22:52 UTC, ianbotsf requested changes

2024-01-19 22:52 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/EcsCredentialsProvider.kt
> +}
**Correctness**: We already have an [`IpAddr` class](https://github.com/awslabs/smithy-kotlin/blob/main/runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/IpAddr.kt) and a separate [`HostResolver` interface](https://github.com/awslabs/smithy-kotlin/blob/main/runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/HostResolver.kt). We should reuse those here instead of re-inventing the wheel.

We _don't_ currently have an `isLoopbackAddress` feature so that's the novel piece to keep. You _can_ delegate down to the platform implementation but it may be simpler just to embed the knowledge in the `IpAddr` class hierarchy and check manually for `127.0.0.1` or `::1`.

2024-01-19 22:52 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/EcsCredentialsProvider.kt
> +                }
**Correctness**: The `all` method behaves in a way we don't want for empty collections—it always returns true (because no items in the collection _don't_ match the predicate). I think you may want to invert this check to `if (!ipAddresses.any { !it.isLoopbackAddress() })`.

2024-01-22 13:52 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/EcsCredentialsProvider.kt
> +}
The `IpAddr` class has an [isLoopBack](https://github.com/awslabs/smithy-kotlin/blob/main/runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/IpAddr.kt#L39) field already. All of the components to implement this are in place we just need to use them

2024-01-22 18:20 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/EcsCredentialsProvider.kt
> +}
Oh yes, you're correct. That's what I get for searching for `isLoopbackAddress` instead of something more general. 😅

2024-01-22 19:44 UTC, ianbotsf requested changes

2024-01-22 19:44 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/EcsCredentialsProvider.kt
> +                    HostResolver.Default.resolve(url.host.toString())
**Correctness**: For the sake of testability and modularity we should probably make the specific `HostResolver` instance a constructor parameter which _defaults_ to `HostResolver.Default`.

2024-01-23 17:55 UTC, ianbotsf requested changes

2024-01-23 17:55 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/EcsCredentialsProvider.kt
>  ) : CloseableCredentialsProvider {
**Correctness**: Sorry, I should've been more clear in my previous comment. This is [a backwards-incompatible change](https://kotlinlang.org/docs/jvm-api-guidelines-backward-compatibility.html#don-t-add-arguments-to-existing-api-functions) and may cause binary compatibility issues. We'll need to maintain the old signature (probably as a secondary constructor) and add a new constructor that accepts the `hostResolver`.

2024-01-23 21:04 UTC, ianbotsf approved these changes

2024-01-24 13:51 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/EcsCredentialsProvider.kt
>  ) : CloseableCredentialsProvider {
As an aside, isn't this what the binary validator is for? Should we have guidelines on reviewing the API diff output for binary compatibility? I feel like relying on intuition and experience here is not the right mechanism.

2024-01-24 13:53 UTC, aajtodd approved these changes

2024-01-24 13:53 UTC, aajtodd commented on aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/auth/credentials/EcsCredentialsProviderTest.kt
> +    fun testLocalFullUri() = runTest {
**suggestion**: These tests make use of real host resolver when we could plug in a mock resolver that doesn't actually rely on resolving DNS.

2024-01-25 16:06 UTC, merged