fix: application of sigv4a
aws/aws-sdk-kotlin pull request #1186
Opened 2024-01-22 15:33 UTC by lauzadis

Addresses an issue with applying the SigV4A trait to services which don't model it 
## Issue \#

#1184 
## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-01-22 16:51 UTC, ianbotsf approved these changes

2024-01-22 16:58 UTC, 0marperez approved these changes

2024-01-22 17:37 UTC, aajtodd commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/SigV4AsymmetricTraitCustomization.kt
> +                    builder.addTrait(
**suggestion**: We should make the predication for `enabledForService` to include not only the `sdkId` check but also that it doesn't have the `sigv4a` trait already. This will help the integration be a bit more forward compatible (e.g. the FIXME on L18 becomes less of a concern).

2024-01-22 17:38 UTC, aajtodd approved these changes
We should probably try and get some integration tests around sigv4a and sigv4 for these services.

2024-01-23 19:55 UTC, 0marperez reviewed
LGTM

2024-01-23 20:08 UTC, aajtodd requested changes

2024-01-23 20:08 UTC, aajtodd commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/SigV4AsymmetricTraitCustomization.kt
> +    private val unmodeledSigV4aServices = listOf("s3", "eventbridge", "cloudfront keyvaluestore")
**correctness**: I don't think cloudfront KVS needs to be in this integration anymore does it?

2024-01-23 20:08 UTC, aajtodd commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/SigV4AsymmetricTraitCustomization.kt
> +                    } ?: AuthTrait(mutableSetOf(SigV4Trait.ID, SigV4ATrait.ID))
**suggestion**: Probably want a remark in here about why this is ordered this way.

(It's because existing services (cloudfront KVS excluded) that use sigv4a do so through endpoint rules and it's not on the model. We don't know which operations it should apply for in those cases and so the safest thing to do is add it at the end and let endpoint rules change the priority as needed. Adding it this way registers support for the trait to let the rest of codegen Just Work (TM)).

2024-01-23 20:08 UTC, aajtodd commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/CloudFrontKeyValueStoreSigV4APrioritizationCustomization.kt
> +    override val order: Byte = -55
I don't think you'll even need to order this if you remove it from the other integration

2024-01-23 20:08 UTC, aajtodd commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/CloudFrontKeyValueStoreSigV4APrioritizationCustomization.kt
> +class CloudFrontKeyValueStoreSigV4APrioritizationCustomization : KotlinIntegration {
**fix**: Other service specific customization's are in their own package directory. 


**suggestion/nit**: This is more of a backfill, I'd consider renaming to `BackfillSigv4A` or something to that affect.

2024-01-23 20:08 UTC, aajtodd commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/CloudFrontKeyValueStoreSigV4APrioritizationCustomization.kt
> +                    val authTrait = AuthTrait(mutableSetOf(SigV4ATrait.ID, SigV4Trait.ID))
**fix**: We should retain the existing auth trait in case it has other auth schemes over time (unlikely but no need to bake it in this way). I'd also only add sigv4a if the existing service model doesn't have it on the service shape.

2024-01-23 20:34 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/SigV4AsymmetricTraitCustomization.kt
> +    private val unmodeledSigV4aServices = listOf("s3", "eventbridge", "cloudfront keyvaluestore")
It is needed, this integration also applies the SigV4A trait. Do you want the new integration to replicate that and then remove cloudfront KVS from this integration?

2024-01-23 21:35 UTC, aajtodd commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/SigV4AsymmetricTraitCustomization.kt
> +    private val unmodeledSigV4aServices = listOf("s3", "eventbridge", "cloudfront keyvaluestore")
I'm not sure I'm following, the new CFKVS integration is applying the sigv4a trait as well so it's redundant here no?

2024-01-23 21:37 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/SigV4AsymmetricTraitCustomization.kt
> +    private val unmodeledSigV4aServices = listOf("s3", "eventbridge", "cloudfront keyvaluestore")
It wasn't when you first reviewed it, I just added that application and removed `cloudfront keyvaluestore` from the `SigV4AsymmetricTraitCustomization`

2024-01-24 13:57 UTC, aajtodd approved these changes

2024-01-24 14:30 UTC, merged