misc: e2e tests for s3 mrap
aws/aws-sdk-kotlin pull request #1193
Opened 2024-01-24 22:34 UTC by 0marperez

## Issue \#

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-02-15 14:44 UTC, aajtodd requested changes

2024-02-15 14:44 UTC, aajtodd commented on services/build.gradle.kts
> +                            implementation("aws.sdk.kotlin:s3control:+")
**fix**: We can't just add these to every e2e test. For example `sts` has it's own e2e tests and taking a dependency on it will cause classpath conflicts (or more likely unpredictable class loading behavior). We're going to need to probably give this more thought.

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +internal suspend fun createS3Bucket(
**question**: Why can't we re-use the existing `S3Utils.getBucket()`?

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +internal suspend fun getAccountId(): String {
**fix**: Move to function on `S3Utils` so these are all grouped.

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    val accountId = sts.getCallerIdentity(
**style**: this operation has a [default parameter](https://sdk.amazonaws.com/kotlin/api/latest/sts/aws.sdk.kotlin.services.sts/-sts-client/get-caller-identity.html), no need to construct an empty request object

```kotlin
val accountId = sts.getCallerIdentity()
```

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +            details =
**style**: use the DSL builder

```kotlin
        s3control.createMultiRegionAccessPoint {
            accountId = "accont"
            details { 
                name = "access-point-name"
                regions = listOf(
                    Region { bucket = "one" },
                    Region { bucket = "two" }
                )
            }
        }

```

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +        createRequestToken.requestTokenArn ?: throw Exception("Unable to get request token ARN"),
**style**

```kotlin
s3ControlClient,
checkNotNull(createRequestToken.requestTokenArn) { "request token arn missing" },
...
```

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/MutliRegionAccessPointTest.kt
> +    private val usWestBucket = "${S3TestUtils.TEST_BUCKET_PREFIX}for-aws-kotlin-sdk-us-west-2"
**concern**: Why do we need to hard code all of these instead of generating them with some random suffix? 

One of the nice properties of the existing tests and `S3Utils.getObject` is that if something goes wrong it attempts to re-use existing infrastructure and/or clean it up. If these tests fail for some reason it may leave the account in a bad state for future tests. I think we need to try and retain this kind of resiliency.

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +internal suspend fun deleteS3Bucket(
**question**: Why do we need this if we have `S3Utils.deleteBucketAndAllContents`?

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +internal suspend fun objectWasCreated(
**fix**: I don't see this used anywhere, if not remove.

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    val search = s3.listObjectsV2(
**fix**: This fails to account for pagination but also using `HeadObject` is a better way to do test this. If you need an object to exist use the waiter `waitUntilObjectExists`.

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +internal suspend fun s3BucketWasCreated(
**fix**: I don't see this used anywhere, if not remove.

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    val search = s3.listBuckets(
**fix**: Same comments, use `HeadBucket` or `waitUntilBucketExists` depending on what you are trying to do.

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    val search = s3Control.listMultiRegionAccessPoints(
**style**: use the DSL builders

**question**: Is there not a better way to do this than just listing access points? I'd imagine either `getMultiRegionAccessPoint` throws some kind of predictable error if the AP doesn't exist.

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    sts.close()
**fix**: You can ensure this is closed always by leveraging `use`

```kotlin
StsClient { region = "us-west-2"}.use { sts ->
      ...
}
```

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    return accountId ?: throw Exception("Unable to get AWS account ID")
**style**: `checkNotNull(accountId) { "..."}`

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    s3ControlClient.listMultiRegionAccessPoints(
**correctness**: Should we not be able to leverage `getMultiRegionAccessPoint`?

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +        1000 * 60 * 10, // 10 minutes
**concern**: Why so long?

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +            details =
Not going to mark this everywhere but there are several other spots I'd have the same feedback

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    timeLimit: Int,
**style**: Use duration

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    while (System.currentTimeMillis() - startTime < timeLimit) {
**fix**: You don't need this, just use [withTimeout](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/with-timeout.html) (or [withTimeoutOrNull](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/with-timeout-or-null.html) depending)

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +        TimeUnit.SECONDS.sleep(10L) // Avoid constant status checks
**fix**: It doesn't matter here since these are all `runBlocking` tests but this is not coroutine friendly, use [delay](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/delay.html) instead

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/MutliRegionAccessPointTest.kt
> +        } catch (exception: Throwable) {
**style**: This is unnecessary, any exception will fail the test with the given cause.

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/MutliRegionAccessPointTest.kt
> +        val accountId = getAccountId()
**suggestion**: You could get this once in `setupMrapTest` and share it across tests.

e.g.

```kotlin
private lateinit var accountId: String

@BeforeAll
private fun setupMrapTest() : Unit = runBlocking { 
    ...
    accountId = getAccountId()
}

```

2024-02-15 14:44 UTC, aajtodd commented on services/s3/e2eTest/src/MutliRegionAccessPointTest.kt
> +    private fun setUpMrapTest(): Unit = runBlocking {
**nit**: `setup` and `cleanup` are one word.

2024-02-15 14:44 UTC, lauzadis reviewed
The tests look good. I would recommend keeping new functions out of `S3TestUtils` unless you think other S3 tests will use it. For MRAP-specific things, it makes more sense to define them in your specific test file

2024-02-15 14:44 UTC, lauzadis commented on services/s3/e2eTest/src/MutliRegionAccessPointTest.kt
> +        println("Setting up MutliRegionAccessPointTest tests")
nit: unnecessary print

2024-02-15 14:44 UTC, lauzadis commented on services/s3/e2eTest/src/MutliRegionAccessPointTest.kt
> +        println("Cleaning up MutliRegionAccessPointTest tests")
nit: unnecessary print

2024-02-15 14:44 UTC, lauzadis commented on services/s3/e2eTest/src/S3TestUtils.kt
> +}
correctness: because this uses `StsClient` it's not an "S3 test util", I'd recommend moving it

2024-02-15 14:44 UTC, lauzadis commented on services/s3/e2eTest/src/S3TestUtils.kt
> +}
question: This seems really similar to `getBucketWithPrefix`. Can that function be adapted to fit your requirements instead of making a new function that does roughly the same thing?

2024-02-15 14:44 UTC, lauzadis commented on services/s3/e2eTest/src/S3TestUtils.kt
> +}
simplification: I don't think these need to be new functions, they are simple enough to write every time

2024-02-15 14:44 UTC, lauzadis commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    while (System.currentTimeMillis() - startTime < timeLimit) {
simplification: `withTimeout(timeLimit) { ... }`

2024-02-15 14:44 UTC, lauzadis commented on services/s3/e2eTest/src/S3TestUtils.kt
> +        TimeUnit.SECONDS.sleep(10L) // Avoid constant status checks
simplification: `delay(10.seconds)`

2024-02-15 14:44 UTC, lauzadis commented on services/s3/e2eTest/src/S3TestUtils.kt
> +}
Same comment here, this function is simple enough, I recommend removing it

2024-02-15 14:44 UTC, lauzadis commented on services/s3/e2eTest/src/S3TestUtils.kt
> +        },
simplification: pass `prefix = keyName` to this call and S3 will do the searching for you

2024-02-15 14:44 UTC, lauzadis commented on services/s3/e2eTest/src/S3TestUtils.kt
> +}
Another function that's simple enough to remove

2024-02-15 14:44 UTC, lauzadis commented on services/s3/e2eTest/src/MutliRegionAccessPointTest.kt
> +            println("Test failed with exception: ${exception.cause}")
nit: unnecessary print

2024-02-15 14:44 UTC, lauzadis commented on services/s3/e2eTest/src/MutliRegionAccessPointTest.kt
> +            println("Test failed with exception: ${exception.cause}")
nit: unnecessary print

2024-02-15 17:32 UTC, ianbotsf commented on services/s3/e2eTest/src/MutliRegionAccessPointTest.kt
> +    private fun setUpMrapTest(): Unit = runBlocking {
**Counter-nit**: "setup" and "cleanup" are nouns. "Set up" and "Clean up" are verbs, which is [the preferred form of method names](https://kotlinlang.org/docs/coding-conventions.html#choose-good-names).

2024-02-19 16:09 UTC, 0marperez commented on services/build.gradle.kts
> +import aws.sdk.kotlin.gradle.kmp.kotlin
IntelliJ does that, it doesn't like the `*` imports. I'll leave it how it was

2024-02-22 14:31 UTC, 0marperez commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    internal suspend fun multiRegionAccessPointWasCreated(
This _could_ be done using a get operation and then looking at the error we get if the MRAP doesn't exist. The only issue is it returns a rather generic `S3ControlException` and all we would have to differentiate a non existent MRAP from a failure would be the error message. Which doesn't seem right as it could change. Either way I can take that approach if that's what everyone thinks

2024-02-22 14:35 UTC, 0marperez commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    internal suspend fun getAccountId(): String {
I couldn't think of a better place for this function. It seemed out of place in the tests class instead of here with the other utils. Placing it in a STS test utils folder could be another option but it seems a little odd since it's used for S3

2024-02-22 19:51 UTC, aajtodd approved these changes

2024-02-22 19:51 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +        duration: Int,
**nit**: `withTimeout` also accepts a `Duration`, instead of passing this as an integer you could just be writing `5.minutes` in the calling code and accept a `Duration`. Also probably rename to something like `timeoutAfter`

2024-02-22 19:51 UTC, aajtodd commented on services/s3/e2eTest/src/S3TestUtils.kt
> +                if (status == "FAILED") throw Exception("$operation operation failed.")
**style**: 

```
check(status != "FAILED") { "$operation operation failed")
```

2024-02-22 19:51 UTC, aajtodd commented on services/build.gradle.kts
> +                        if (project.name == "s3") {
I suppose this works but this is getting ugly. I'm thinking we'll be revisiting the structure around e2e tests soon.

2024-02-22 19:58 UTC, 0marperez commented on services/build.gradle.kts
> +                        if (project.name == "s3") {
I agree,I think we could refactor some of this into a functions if it starts getting used more.

2024-02-22 20:20 UTC, lauzadis approved these changes

2024-02-22 20:20 UTC, lauzadis commented on services/s3/e2eTest/src/MutliRegionAccessPointTest.kt
> +    private fun setUpMrapTest(): Unit = runBlocking {
nit: My thought on this is to just call it `setup`, the test class is enough of a hint of what you are setting up

2024-02-22 20:20 UTC, lauzadis commented on services/s3/e2eTest/src/S3TestUtils.kt
> +        }
nit: possible simplification
```kt
var testBucket = buckets?.firstOrNull { bucketName -> 
    bucketName.startsWith(prefix) && 
    region?.let { 
        client.getBucketLocation { 
            bucket = bucketName
            expectedBucketOwner = accountId
        }.locationConstraint?.value == region 
    } ?: true 
}
```

2024-02-22 20:20 UTC, lauzadis commented on services/s3/e2eTest/src/S3TestUtils.kt
> +        println("Getting account ID")
nit: seems like an unnecessary print to me

2024-02-22 20:20 UTC, lauzadis commented on services/s3/e2eTest/src/S3TestUtils.kt
> +        return search != null
nit: simplification

```kt
return s3Control.listMultiRegionAccessPoints {
    accountId = testAccountId
}.accessPoints?.any { it.name == multiRegionAccessPointName }
```

2024-02-22 20:20 UTC, lauzadis commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    internal suspend fun getAccountId(): String {
Yeah this seems fine, especially now that S3 E2E tests are guaranteed to have a dependency on STS

2024-02-22 20:24 UTC, 0marperez commented on services/s3/e2eTest/src/S3TestUtils.kt
> +        println("Getting account ID")
There's a couple of other print statements in the utils, why does this one seem unnecessary?

2024-02-22 21:17 UTC, merged