feat: Support S3 Express One Zone
aws/aws-sdk-kotlin pull request #1206
Opened 2024-02-08 15:14 UTC by lauzadis

Adds support for [S3 Express One Zone](https://aws.amazon.com/s3/storage-classes/express-one-zone/)
## Issue \#

## Description of changes

- New execution context attributes `S3ExpressAttributes.Bucket` (bucket name the user is making requests to) and `S3ExpressAttributes.Client` (the user's S3 client, used to make `s3:CreateSession` requests)
- New auth scheme: `SigV4S3ExpressAuthScheme`
- New HTTP signer `S3ExpressHttpSigner` which is a thin wrapper over the existing `AwsHttpSigner`, which makes some header changes required for S3 Express 
- New `SdkS3ExpressCredentialsProvider` which fetches credentials from an `S3ExpressCredentialsCache`. This cache calls `s3:CreateSession` to get credentials and caches them for some time.  
- New config options on S3 clients: `disableS3ExpressSessionAuth` which is used to force S3 Express requests to use default auth methods, and `s3ExpressCredentialsProvider` which can be used to configure a custom implementation of S3ExpressCredentialsProvider

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-02-12 21:16 UTC, aajtodd requested changes

2024-02-12 21:16 UTC, aajtodd commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/express/S3ExpressIntegration.kt
> +            SectionWriterBinding(HttpProtocolClientGenerator.ConfigureAuthSchemes, configureS3ExpressAuthSchemeWriter),
**question/correctness**: If we have an auth scheme integration + handler why do we need to override individual sections? That's why those abstractions exist.

2024-02-12 21:16 UTC, aajtodd commented on services/s3/common/src/aws/sdk/kotlin/services/s3/internal/SdkS3ExpressCredentialsProvider.kt
> +public class SdkS3ExpressCredentialsProvider(
**suggestion**: _if_ we are going to keep a new interface for this thing then make this `internal` and expose it through `S3CredentialsProvider` companion object via a factory function named `default`

e.g.

```kotlin
interface S3ExpressCredentialsProvider {
     companion object {
          fun default(bootstrapCredentialsProvider: CredentialsProvider): S3ExpressCredentialsProvider
     }
}
```

_If we keep this public_ rename it to `DefaultS3ExpressCredentialsProvider` (and add docs)

2024-02-12 21:16 UTC, aajtodd commented on services/s3/common/src/aws/sdk/kotlin/services/s3/internal/S3ExpressCredentialsCache.kt
> +public class S3ExpressCredentialsCache(
**question**: Why does the cache and key need to be public at all?

2024-02-12 21:16 UTC, aajtodd commented on services/s3/common/src/aws/sdk/kotlin/services/s3/internal/S3ExpressCredentialsCache.kt
> +            Credentials.invoke(
**nit**: remove the `.invoke` you can just call `Credentials(...)` and it will infer you mean the operator function

2024-02-12 22:18 UTC, ianbotsf requested changes

2024-02-12 22:18 UTC, ianbotsf commented on tests/benchmarks/service-benchmarks/jvm/src/aws/sdk/kotlin/benchmarks/service/definitions/S3ExpressBenchmark.kt
> +    private val regionAz = "usw2-az1"
**Suggestion**: IMDS can report the running EC2 instance's AZID by querying the `placement/availability-zone-id` path (see the [IMDS metadata categories page](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-categories.html) for more info). Consider making this test and the E2E test more flexible by adapting to the location the test is running from.

2024-02-13 15:57 UTC, lauzadis commented on aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/S3ExpressHttpSigner.kt
> +private const val SESSION_TOKEN_HEADER = "X-Amz-Security-Token"
It's not, I could make it one since it's used all over the place now

2024-02-13 15:59 UTC, lauzadis commented on aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/interceptors/S3ExpressCrc32ChecksumInterceptor.kt
> +        context.executionContext[HttpOperationContext.ChecksumAlgorithm] = CRC32_ALGORITHM_NAME
I overlooked this, it's outdated logic. We only need to set a flexible checksum if it's not set already. We do not need to override users' flexible checksum algorithms (even if they are SHA1, SHA256, CRC32C), we just need to make sure _something_ is set (defaulting to CRC32) so the MD5 checksum does not get sent.

2024-02-13 16:02 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/resources/META-INF/services/software.amazon.smithy.kotlin.codegen.integration.KotlinIntegration
>  aws.sdk.kotlin.codegen.customization.glacier.GlacierAddVersionHeader
Alphabetic order, I will revert since this is unmaintainable long-term without a lint check

2024-02-13 16:02 UTC, ianbotsf commented on aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/S3ExpressHttpSigner.kt
> +public class S3ExpressHttpSigner(
Counter-question: why _should_ it be `internal`? The `AuthScheme` interface is public, as is its `signer: HttpSigner` property, and we intend users to be able to provide their own auth schemes—potentially ones which reuse or customize our signing logic right?

2024-02-13 16:08 UTC, ianbotsf commented on codegen/aws-sdk-codegen/src/main/resources/META-INF/services/software.amazon.smithy.kotlin.codegen.integration.KotlinIntegration
>  aws.sdk.kotlin.codegen.customization.glacier.GlacierAddVersionHeader
It's worth noting here that, while it improves maintainability, the order of items in this list is significant. SPI will load classes in the order listed here and for all implementations that share a `KotlinIntegration.order` value they will maintain that ordering.

2024-02-13 17:03 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/resources/META-INF/services/software.amazon.smithy.kotlin.codegen.integration.KotlinIntegration
>  aws.sdk.kotlin.codegen.customization.glacier.GlacierAddVersionHeader
It may be important right now, but I feel if integrations have the same `order`, they should support being applied in any order. Otherwise they should configure `KotlinIntegration.order` as needed.

2024-02-13 17:16 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/internal/S3ExpressCredentialsCache.kt
> +    private val lru = LruCache<S3ExpressCredentialsCacheKey, ExpiringValue<Credentials>>(DEFAULT_S3_EXPRESS_CACHE_SIZE)
I kinda disagree with this after looking at the SEP / other implementations ([Java](https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3express/S3ExpressIdentityCache.java#L42), [C++](https://github.com/aws/aws-sdk-cpp/blob/c62954ca213255d572f78f2004e0a0bddf74fc97/generated/src/aws-cpp-sdk-s3/source/S3ExpressIdentityProvider.cpp#L21)) which don't support configuring the size. 

Users are able to create and configure their own `S3ExpressCredentialsProvider` and then they can define their own size. FWIW, 100 is the SEP default but Java found just 25 to be sufficient for their users' use patterns.

2024-02-13 17:47 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/internal/S3ExpressCredentialsCache.kt
> +            .withConfig { interceptors = mutableListOf() }
I supposed we should. This came up during my testing, I had an interceptor which asserted requests were made with SigV4 S3 Express auth, and the assertion failed due to this `createSession` request. It was unexpected at the time but I can see how users would _want_ their configured interceptors used even for this internal request

2024-02-13 17:53 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/internal/S3ExpressCredentialsCache.kt
> +        )
I somewhat disagree. After I make these both `internal` / `@InternalApi` (as they should have been from the start), these credentials will always come from the `SdkS3ExpressCredentialsProvider`. I could add that constructor parameter for clarity, but it will always be the same

2024-02-13 21:14 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/SigV4S3ExpressAuthScheme.kt
> +private val S3_EXPRESS_AUTH_SCHEME_ID = AuthSchemeId("aws.auth#sigv4s3express")
I could for this usage, but codegen wouldn't be able to use it since this is moved to the `s3` package. I don't think it can be made an `AwsRuntimeType` if it's not in the `aws-runtime` project.

2024-02-13 21:43 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/SigV4S3ExpressAuthScheme.kt
> +// FIXME Copied from SigV4AuthScheme.kt
I went the route of making a `sigV4(...)` auth option and copying its attributes, nice suggestion!

2024-02-13 22:32 UTC, lauzadis commented on aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/S3ExpressHttpSigner.kt
> +    public val awsHttpSigner: AwsHttpSigner,
This will always be `AwsHttpSigner`, right? Is there some use-case I don't know about where having this be `HttpSigner` would be useful?

2024-02-13 23:08 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/internal/SdkS3ExpressCredentialsProvider.kt
> +public class SdkS3ExpressCredentialsProvider(
I went the `internal` route exposing it as `S3ExpressCredentialsProvider.default(...)`. This may change depending on where we land on [configuration](https://github.com/awslabs/aws-sdk-kotlin/pull/1206/files#r1486772945) (such as cache size).

2024-02-14 13:43 UTC, aajtodd commented on aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/S3ExpressHttpSigner.kt
> +public class S3ExpressHttpSigner(
I would say yes we intend for users to be able to customize auth schemes. Why they need or want to do that remains unknown and so we lose nothing from making it `internal` and then later based on feedback converting it to `public`. Best case scenario nobody needs to customize it and our public API surface we have to maintain is smaller, worse case we have feedback and concrete use cases to use to expose the right abstractions.

2024-02-14 13:45 UTC, aajtodd commented on aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/S3ExpressHttpSigner.kt
> +    public val awsHttpSigner: AwsHttpSigner,
it's more about taking only what you need as a principle.

2024-02-14 14:59 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/express/SigV4S3ExpressAuthSchemeIntegration.kt
> +class SigV4S3ExpressAuthSchemeIntegration : SigV4AuthSchemeIntegration() {
I did this to avoid duplicating a lot of the overrides:
- `customizeMiddleware` for `Sigv4SignedBodyHeaderMiddleware`
- `additionalServiceConfigProps`
- `sectionWriters`

I agree with your concern so let me remove the inheritance and see how to minimize the duplication

2024-02-14 18:56 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/internal/S3ExpressCredentialsCache.kt
> +    private val lru = LruCache<S3ExpressCredentialsCacheKey, ExpiringValue<Credentials>>(DEFAULT_S3_EXPRESS_CACHE_SIZE)
We spoke offline and agreed to keep this unconfigurable as recommended by the SEP. If we get feedback asking for configurability, we'll reconsider adding configuration options.

2024-02-15 17:54 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/express/S3ExpressIntegration.kt
> +            SectionWriterBinding(HttpProtocolClientGenerator.ConfigureAuthSchemes, configureS3ExpressAuthSchemeWriter),
Auth schemes are fetched using `[effectiveAuthHandlersForService](https://github.com/awslabs/smithy-kotlin/blob/main/codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/knowledge/AuthIndex.kt#L65)` off the service model, which doesn't pick up this new S3 Express auth scheme. That's why I had to add sections everywhere we need S3 Express added. Is there a better way to do this

2024-02-15 17:56 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/express/SigV4S3ExpressAuthSchemeIntegration.kt
> +                writer.renderOrElse(expressionRenderer, scheme.getStringMember("signingRegion"), "null")
This is copied from [SigV4AuthSchemeIntegration](https://github.com/awslabs/smithy-kotlin/blob/main/codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/auth/SigV4AuthSchemeIntegration.kt#L201-L212), how would you recommend changing it?

2024-02-15 18:20 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/internal/S3ExpressCredentialsCache.kt
> +    private fun ExpiringValue<Credentials>.isExpired(clock: Clock): Boolean = clock.now().until(expiresAt).absoluteValue <= REFRESH_BUFFER
I understand the issue but am not sure how `TimeSource` can be used effectively here. It exposes `markNow` but no way to determine where the system is relative to the credentials expiration `Instant`. I think we will always need to use a `Clock` at some point, at least to get the time between `clock.now()` and the `expiresAt` time.

```kt
val expirationInstant: Instant = credentials.expiration
val expirationMark = timeSource.markNow().plus(clock.now().until(expirationInstant)) // uses clock

private fun ExpiringValue<Credentials>.isExpired(): Boolean = (expirationMark + REFRESH_BUFFER).hasPassedNow()
```

2024-02-15 18:31 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/internal/S3ExpressCredentialsCache.kt
> +                logger.debug { "Cache is empty, waiting..." }
question: I am unable to see log statements in this `refresh()` function, probably because this class implements `CoroutineScope` but does not instantiate a `TelemetryProvider`, how should I do that?

2024-02-16 17:06 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/internal/S3ExpressCredentialsCache.kt
> +    private fun ExpiringValue<Credentials>.isExpired(clock: Clock): Boolean = clock.now().until(expiresAt).absoluteValue <= REFRESH_BUFFER
`markNow` returns a `TimeMark`, which exposes [`elapsedNow`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-time-mark/elapsed-now.html), a method which returns the amount of time passed between now and the mark. It should allow us to determine for how much longer a `Credentials` is valid.

2024-02-16 17:20 UTC, aajtodd requested changes

2024-02-16 17:20 UTC, aajtodd commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/express/S3ExpressIntegration.kt
> +    private val AddBucketToExecutionContext = object : ProtocolMiddleware {
**suggestion**: Maybe just make this a generic S3 integration for S3 and rename the attribute to `Bucket` instead of `DirectoryBucket`, I can't imagine we won't need it again at some point...

2024-02-16 17:59 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/internal/S3ExpressCredentialsCache.kt
> +    private fun ExpiringValue<Credentials>.isExpired(clock: Clock): Boolean = clock.now().until(expiresAt).absoluteValue <= REFRESH_BUFFER
We spoke offline and agreed using `Clock` is required to get the initial `Duration` between the current time and the Credentials' expiration time. Outside of that, I will be removing use of `Clock` in this class

2024-02-17 18:10 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/S3ExpressCrc32ChecksumInterceptor.kt
> +public class S3ExpressCrc32ChecksumInterceptor(
Yes, the order is[ already set in S3ExpressIntegration](https://github.com/awslabs/aws-sdk-kotlin/blob/feat-s3-express/codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/express/S3ExpressIntegration.kt#L109) where the interceptor is rendered

2024-02-17 19:32 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/SigV4S3ExpressAuthScheme.kt
> +    get() = AuthSchemeId("aws.auth#sigv4s3express")
Shape IDs can't have dashes in them. It looks like the Go SDK remaps this during auth scheme resolution, we'll probably need to do something similar 

https://github.com/aws/aws-sdk-go-v2/blob/be0accd6c6511b727d38cbe98489753e481d68b3/service/s3/endpoint_auth_resolver.go#L26-L31

2024-02-17 19:46 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/express/S3ExpressIntegration.kt
> +    private val AddBucketToExecutionContext = object : ProtocolMiddleware {
I'll rename it for future reusability but keep it in S3 Express until we find another use for it.

2024-02-17 20:42 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/ClientConfigIntegration.kt
> +        val DisableExpressSessionAuth: ConfigProperty = ConfigProperty {
I don't see a huge difference, these are all scoped to S3 anyways

2024-02-17 20:44 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/internal/S3ExpressCredentialsCache.kt
> +                logger.debug { "Cache is empty, waiting..." }
Thanks! I got logging working using the `client.config.telemetryProvider`

2024-02-18 00:51 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/internal/SdkS3ExpressCredentialsProvider.kt
> +            credentialsCache = S3ExpressCredentialsCache(attributes[S3Attributes.ExpressClient] as S3Client)
Yeah. I would need to add a section to the `withConfig` block and then codegen an update to the execution context

2024-02-21 00:38 UTC, ianbotsf requested changes
**Opinion**: After re-reviewing the cache usage in the S3 Express creds provider, I think that having a single overall refresh loop is incorrect and causes more problems than it solves. I think a safer and simpler alternative is to fire off a delayed refresher for each entry in the cache. As soon as we create new session credentials we know exactly when they'll be eligible for refresh and should be checked.

2024-02-21 00:38 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/DefaultS3ExpressCredentialsProvider.kt
> +            ?: createSessionCredentials(key.bucket, client).also { credentialsCache.put(key, S3ExpressCredentialsCacheValue(it, usedSinceLastRefresh = true)) }.value
**Correctness**: This marks credentials as "used since last refresh" only if they're new but not if they're pre-existing.

2024-02-21 00:38 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/DefaultS3ExpressCredentialsProvider.kt
> +            }
**Correctness**: This takes a snapshot of the cache entries but then removes them based on that stale snapshot. It's possible that entries have already been evicted because of the cache capacity.

2024-02-21 00:38 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/DefaultS3ExpressCredentialsProvider.kt
> +            }
**Correctness**: There's a subtle multi-threading bug here where it's possible that `usedSinceLastRefresh == false` but then may be used and marked as `usedSinceLastRefresh == false` before we get to `credentialsCache.remove(it.key)`.

2024-02-21 00:38 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/DefaultS3ExpressCredentialsProvider.kt
> +                logger.trace { "Cache is empty, waiting..." }
**Nit**: This trace message is not super informative because it doesn't indicate why we're waiting.

2024-02-21 00:38 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/DefaultS3ExpressCredentialsProvider.kt
> +            entries.forEach { it.value.usedSinceLastRefresh = false }
**Correctness**: The credentials may have been used again since we last checked.

2024-02-21 00:38 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressCredentialsCache.kt
> +internal val ExpiringValue<Credentials>.isExpired: Boolean get() = (expiresAt - REFRESH_BUFFER).hasPassedNow()
**Correctness**: Credentials which are inside the refresh buffer are not _expired_, they're merely eligible for early refresh. This is important for logic inside the `resolve` method:

```kotlin
return credentialsCache
    .get(key)
    ?.expiringCredentials
    ?.takeIf { !it.isExpired } // Faulty assumption
    ?.value
    ?: …
```

2024-02-21 00:38 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/DefaultS3ExpressCredentialsProvider.kt
> +    }
**Question**: Why do we need fallback logic for when the lazy client reference isn't yet initialized? We don't seem to be logging anything before we have an initialized client.

2024-02-21 00:38 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/DefaultS3ExpressCredentialsProvider.kt
> +internal fun TimeMark.until(other: TimeMark): Duration = (this.elapsedNow().absoluteValue - other.elapsedNow().absoluteValue).absoluteValue
**Nit**: [`ComparableTimeMark`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-comparable-time-mark/) already has a `minus` operator for getting the duration between two marks. We should tighten the interface we use from `TimeSource` to [`WithComparableMarks`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-time-source/-with-comparable-marks/).

2024-02-21 00:38 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressCredentialsCache.kt
> +}
**Question**: This class seems to merely wrap the `LruCache` class with specific type parameters. Could this be replaced with just:

```kotlin
typealias S3ExpressCredentialsCache = LruCache<S3ExpressCredentialsCacheKey, S3ExpressCredentialsCacheValue>
fun S3ExpressCredentialsCache() = S3ExpressCredentialsCache(DEFAULT_S3_EXPRESS_CACHE_SIZE)
```

2024-02-21 00:38 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressCredentialsCache.kt
> +internal data class ExpiringValue<T> (val value: T, val expiresAt: TimeMark)
**Nit**: Extraneous space after `>`

2024-02-21 00:38 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressCredentialsProvider.kt
> +}
**Question**: What value does this interface provide?

2024-02-21 14:28 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressCredentialsProvider.kt
> +}
It doesn't provide much value from the `interface` perspective, but it does provide public access to the internal `DefaultS3ExpressCredentialsProvider` through the companion object.

I think removing the interface makes sense, but then do you have any opinions on how we provide access to this internal default provider?

2024-02-21 14:30 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressCredentialsCache.kt
> +}
Nice simplification, thanks!

2024-02-21 15:04 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/express/SigV4S3ExpressAuthSchemeIntegration.kt
> +    override val order: Byte = -50
This is set so it runs after `SigV4AuthSchemeIntegration`. I have not figured out exactly why, but if `order` is greater than `-50`, it results in the tests failing due to infinite recursion / stack overflow exceptions when making requests.

I updated this to `-51` and added a comment for clarity

2024-02-21 16:06 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressCredentialsProvider.kt
> +}
A factory function or a public no-args constructor seem like viable options to me.

2024-02-21 21:57 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressCredentialsProvider.kt
> +}
I went with a public no-args constructor!

2024-02-21 21:58 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/DefaultS3ExpressCredentialsProvider.kt
> +    }
It was mainly for safety, so someone in the future doesn't add a log statement when the client is uninitialized, but they would find out very quickly through failing tests in that case

2024-02-22 15:36 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/internal/S3ExpressCredentialsCache.kt
> +    private suspend fun refresh() {
Addressed in the latest async refresh strategy implementation. An async refresh will be kicked off during `resolve` when the credentials are within their refresh window.

2024-02-22 19:25 UTC, ianbotsf approved these changes

2024-02-22 19:25 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/DefaultS3ExpressCredentialsProvider.kt
> +                }
**Nit**: I believe the `singleFlight` should wrap this entire `if` block. Otherwise multiple threads could detect the refresh buffer, log the trace message, launch a coroutine, and update the credentials cache.

2024-02-22 19:25 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/DefaultS3ExpressCredentialsProvider.kt
> +        }
**Suggestion**: Both places we call this method we then immediately put the new credentials into the cache. Seems like that logic could be moved here

2024-02-22 19:25 UTC, ianbotsf commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    private suspend fun getDirectoryBucket(client: S3Client, suffix: String): String = withTimeout(60.seconds) {
**Style**: It seems unnecessary to have the `getDirectoryBucket` helper method when it's completely delegated to by a single calling method.

2024-02-22 19:25 UTC, ianbotsf commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    private suspend fun getDirectoryBucket(client: S3Client, suffix: String): String = withTimeout(60.seconds) {
**Question**: This method isn't guaranteed to find or create a bucket in the caller's AZ. Is that important?

2024-02-22 19:25 UTC, ianbotsf commented on tests/benchmarks/service-benchmarks/jvm/src/aws/sdk/kotlin/benchmarks/service/definitions/S3ExpressBenchmark.kt
> +    private val getObjectBenchmark = object : AbstractOperationBenchmark<S3Client>("s3express:GetObject") {
**Nit**: Don't prefix the operation name with `s3express:`. Instead, set `clientName` in the `client()` function above.

2024-02-22 20:57 UTC, lauzadis commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    private suspend fun getDirectoryBucket(client: S3Client, suffix: String): String = withTimeout(60.seconds) {
Agreed, I will refactor that

2024-02-22 21:07 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/DefaultS3ExpressCredentialsProvider.kt
> +                }
I tried this initially, but ran into trouble when testing multiple threads, they would all start calling `createSessionCredentials` instead of just one of them.

The reason is the `singleFlight { ... }` blocks until the inner block is done executing. `launch(coroutineContext) { ... }` exits immediately (because it runs asynchronously) meaning that every coroutine completed its own `singleFlight` call and excessive async refreshes were launched.

2024-02-23 16:03 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/DefaultS3ExpressCredentialsProvider.kt
> +                }
Oh right. 🤦‍♂️ Well, we can at least ensure the cache update happens inside the SFG.

2024-02-26 21:42 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/express/SigV4S3ExpressAuthSchemeIntegration.kt
> +        name = "AuthSchemeId(\"aws.auth#sigv4s3express\")"
I already tried this but had a ton of trouble because the AuthSchemeId is an extension in `aws.sdk.kotlin.services.s3.express` but the AuthSchemeId symbol comes from RuntimeTypes

2024-02-26 22:12 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/express/S3ExpressIntegration.kt
> +                writer.write("op.interceptors.add(#T(${checksumHeaderName?.dq() ?: ""}))", interceptorSymbol)
Yes, we only need to register this interceptor if the operation requires a checksum. I could move all this logic to the `isEnabledFor` to reflect that better

2024-02-26 22:13 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/express/S3ExpressIntegration.kt
> +                writer.write("op.interceptors.add(#T(${checksumHeaderName?.dq() ?: ""}))", interceptorSymbol)
The reason for this is: if an operation requires a checksum and the user does not provide one through flexible checksums, the SDK will default to MD5. S3 Express **does not support** MD5, so we need to prevent sending MD5 by enabling CRC32 when an operation requires a checksum.

2024-02-26 23:21 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/flexiblechecksums/FlexibleChecksumsRequest.kt
> +            writer.withBlock("input.${requestAlgorithmMember.defaultName()}?.let {", "}") {
Addressed by passing the input as a `checksumAlgorithmNameInitializer` function like was done before, but I moved its invocation from `readAfterSerialization` to `modifyBeforeSigning`. See smithy-kotlin PR for more details

2024-02-27 14:17 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/express/SigV4S3ExpressAuthSchemeIntegration.kt
> +private fun renderAuthSchemes(writer: KotlinWriter, authSchemes: Expression, expressionRenderer: ExpressionRenderer) {
That wasn't expected, but oddly enough the S3 Express requests all still worked. I [fixed it in smithy-kotlin](https://github.com/awslabs/smithy-kotlin/pull/1033/commits/6a4757c4891b9fc7ede39daa7b750a42a2b632e5) by adding support for multiple endpoint property renderers per key. Before this change, the SigV4AuthSchemeIntegration was overriding whatever was set here in this integration.

2024-02-27 16:13 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/express/S3ExpressIntegration.kt
> +        val authTrait = AuthTrait(mutableSetOf(SigV4S3ExpressAuthTrait.ID) + serviceShape.expectTrait(AuthTrait::class.java).valueSet)
1. It **does** need to be added to the auth trait to resolve properly
2. I fixed an issue [(in smithy-kotlin)](https://github.com/awslabs/smithy-kotlin/pull/1033/commits/91733c3cdcbeb2cb0c5de469811e44e72bdc5417) and now add S3 Express auth scheme to the _end_ of this prioritized list

2024-02-28 15:05 UTC, aajtodd reviewed
Looks good, really close just a couple questions and a few small things to tidy up.

2024-02-28 15:05 UTC, aajtodd commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/DefaultS3ExpressCredentialsProvider.kt
> +        val key = S3ExpressCredentialsCacheKey(attributes[S3Attributes.Bucket], client.config.credentialsProvider.resolve(attributes))
I can see this is called out in the SEP but it seems so odd to me to have to fetch credentials to form a cache key. I guess thats what we have to do but we are relying heavily on this being a cached provider.

2024-02-28 15:20 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressCrc32ChecksumInterceptor.kt
> +            logger.info { "Checksum is required and not already configured, enabling CRC32 for S3 Express" }
Sure I could make it `debug`. I chose `info` at first because we are changing the user's input but I agree it will be noisy.

2024-02-28 15:24 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/DefaultS3ExpressCredentialsProvider.kt
> +    private lateinit var client: S3Client
It's not needed anymore, I can refactor to remove it

2024-02-28 15:25 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/DefaultS3ExpressCredentialsProvider.kt
> +        val key = S3ExpressCredentialsCacheKey(attributes[S3Attributes.Bucket], client.config.credentialsProvider.resolve(attributes))
Yeah the cache key needs to be unique across Account ID / Secret Access Key, using Credentials in the cache key is the simple way to achieve that, it's what Java does too FWIW

2024-02-28 15:36 UTC, lauzadis commented on services/s3/e2eTest/src/S3ExpressTest.kt
> +class S3ExpressTest {
I just opened one. https://github.com/awslabs/aws-sdk-kotlin/issues/1236

Sure, I'll add a test but it won't be very useful right now.

2024-02-28 19:15 UTC, lauzadis commented on tests/benchmarks/service-benchmarks/jvm/src/aws/sdk/kotlin/benchmarks/service/definitions/S3ExpressBenchmark.kt
> +class S3ExpressBenchmark : ServiceBenchmark<S3Client> {
I can't re-run all these benchmarks because Pinpoint is throttling and they no longer support adjusting the quota. Ian has a limit of 7000 which is enough to run the benchmarks, but my account has the default (10) which causes throttling errors.

A few options:
1. Update all the benchmarks except Pinpoint
2. Only add S3 Express benchmark results
3. Don't update the benchmarks at all right now, do it when the quota issue is fixed

2024-02-28 19:46 UTC, lauzadis commented on tests/benchmarks/service-benchmarks/jvm/src/aws/sdk/kotlin/benchmarks/service/definitions/S3ExpressBenchmark.kt
> +class S3ExpressBenchmark : ServiceBenchmark<S3Client> {
Decided on #2, only add/update the S3 benchmarks, which are in a different section. Also created a backlog item to address the Pinpoint throttles, internal reference `SDK-KT-104`

2024-02-29 15:51 UTC, merged