feat: configuration options for sigv4aSigningRegionSet
aws/aws-sdk-kotlin pull request #1235
Opened 2024-02-27 15:08 UTC by 0marperez

## Issue \#
closes #1234 
SigV4a as a trait is implemented in the following PR: smithy-kotlin#1023

## Description of changes
The `sigv4aSigningRegionSet` config options are added in this PR and are routed to the relevant signer in #X

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-02-27 17:42 UTC, ianbotsf requested changes

2024-02-27 17:42 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/sigv4a/ResolveSigningRegionSet.kt
> +    Regex("^\\s*([^,\\s]+\\s*,\\s*)*[^,\\s]+\\s*\$").matches(input)
**Question**: Is it _important_ that the list contains no empty strings? Or could they just be filtered out after splitting?

```kotlin
rawString
    ?.split(",")
    ?.map { it.trim() }
    ?.filter { it.isNotEmpty }
```

2024-02-27 17:42 UTC, ianbotsf commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/AwsServiceConfigIntegration.kt
> +                The set of regions to use when signing a request with sigV4a. If not provided this will automatically be set by the SDK.
**Nit**: `sigV4a` → `SigV4a`

2024-02-27 17:42 UTC, ianbotsf commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/AwsServiceConfigIntegration.kt
> +            order = 100
**Question**: Why `order = 100`? If it's important that this appears before/after something else, we should leave a clarifying comment.

2024-02-27 17:42 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/sigv4a/ResolveSigningRegionSet.kt
> +}
**Style**: Since this is a region _set_ it feels odd to pass it around in a `List`, especially since the signer implementation in **smithy-kotlin** will turn it into a `Set` eventually. I suggest making the type `Set<String>` in config, resolution, etc.

2024-02-27 17:42 UTC, ianbotsf commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/AwsServiceConfigIntegration.kt
> +        }
**Correctness**: This adds the new property for every service client whether that service supports SigV4a or not. I think we should scope this more narrowly to only services which _actually_ use it—by model trait or known list.

2024-02-27 18:19 UTC, 0marperez commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/sigv4a/ResolveSigningRegionSet.kt
> +    Regex("^\\s*([^,\\s]+\\s*,\\s*)*[^,\\s]+\\s*\$").matches(input)
The design document says it "must be an optional, non-empty list of non-empty strings". I don't think it matters much but I would like to have consistency with the other SDK's.

2024-02-27 18:21 UTC, 0marperez commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/sigv4a/ResolveSigningRegionSet.kt
> +}
This is also something that I did because of the design document. The name doesn't make any sense but I think it would be nice to have consistency with the other SDK's

2024-02-27 18:26 UTC, 0marperez commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/AwsServiceConfigIntegration.kt
> +            order = 100
This was just a copy paste leftover oops. The order shouldn't matter here

2024-02-29 17:31 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AwsSdkSetting.kt
> +        strEnvSetting("aws.sigv4aSigningRegionSet", "AWS_SIGV4A_SIGNING_REGION_SET")
naming: `aws.sigV4aSigningRegionSet` (capital V)

2024-02-29 17:31 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/sigv4a/ResolveSigningRegionSet.kt
> + * Attempts to resolve sigv4aSigningRegionSet from specified sources.
nit/suggestion: be more specific about "from specified sources"

2024-02-29 17:31 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/sigv4a/ResolveSigningRegionSet.kt
> +}
I'd also vote to go against the spec here and make it a `Set<String>`. I had [the same comment](https://github.com/awslabs/smithy-kotlin/pull/1043#discussion_r1507918750) in your smithy-kotlin PR and didn't realize it was discussed here already. 

This is probably something we should discuss and see if we can get the spec changed

2024-02-29 17:31 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/sigv4a/ResolveSigningRegionSet.kt
> +    Regex("^\\s*([^,\\s]+\\s*,\\s*)*[^,\\s]+\\s*\$").matches(input)
suggestion: I'd recommend using Kotlin functions to filter this list instead of a regex, it's way more maintainable.

2024-02-29 17:31 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/sigv4a/ResolveSigningRegionSet.kt
> +    Regex("^\\s*([^,\\s]+\\s*,\\s*)*[^,\\s]+\\s*\$").matches(input)
I think the spec just calls out what you can expect the values to be. I don't think we have to validate + blow up / throw an exception if the set has an empty string in it

2024-03-01 13:56 UTC, aajtodd requested changes

2024-03-01 13:56 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
> +            config.sigv4aSigningRegionSet = config.sigv4aSigningRegionSet ?: resolveSigningRegionSet(platform, profile)
**correctness**: This doesn't apply to every service, only services using sigv4a. We shouldn't register config properties that are unused/meaningless.

2024-03-01 13:56 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AwsSdkSetting.kt
> +        strEnvSetting("aws.sigv4aSigningRegionSet", "AWS_SIGV4A_SIGNING_REGION_SET")
Whatever we use for JVM system properties needs to be consistent with Java. I don't see a [setting](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkSystemSetting.java) defined by them yet so talk with someone on Java team to confirm.

2024-03-01 13:56 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/sigv4a/ResolveSigningRegionSet.kt
> +package aws.sdk.kotlin.runtime.config.sigv4a
I'm not a fan of proliferating packages with single things in them. We should have grouped resolvers somewhere probably but we can at least do better going forward. This should be either in [ResolveRegion](https://github.com/awslabs/aws-sdk-kotlin/blob/main/aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/region/ResolveRegion.kt) or in a more generic package like `aws.sdk.kotlin.runtime.config.auth` such that new auth related settings/resolvers end up grouped.

2024-03-01 13:56 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/sigv4a/ResolveSigningRegionSet.kt
> +    Regex("^\\s*([^,\\s]+\\s*,\\s*)*[^,\\s]+\\s*\$").matches(input)
Agreed, I think being tolerant here is probably a better experience.

2024-03-01 13:56 UTC, aajtodd commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/client/AwsSdkClientConfig.kt
> +    public val sigv4aSigningRegionSet: List<String>?
**fix**: Again this doesn't belong here, this should be registered as part of the integration. We can define interfaces for it if we want/need to but the config setting should be added as part of codegen.

2024-03-01 16:02 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AwsSdkSetting.kt
> +        strEnvSetting("aws.sigv4aSigningRegionSet", "AWS_SIGV4A_SIGNING_REGION_SET")
The Java SDK has not yet implemented this feature and doesn't have a system property name selected yet so they will use whatever we decide in this instance. Given that their typical pattern is a camel-cased version of the environment variable name, I think `aws.sigV4aSigningRegionSet` is good and probably what they would've selected anyway.

2024-03-07 18:53 UTC, aajtodd approved these changes

2024-03-07 21:20 UTC, lauzadis approved these changes

2024-03-11 15:47 UTC, merged