fix: correctly handle all empty HeadObject/HeadBucket responses
aws/aws-sdk-kotlin pull request #1378
Opened 2024-08-05 21:02 UTC by lauzadis

Previously we only checked for empty bodies with HTTP 404, but it seems like S3 also returns empty bodies for HTTP 403. This PR expands the handler logic to catch all empty bodies rather than just 404's.

## Issue \#

Closes https://github.com/awslabs/aws-sdk-kotlin/issues/1368

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-06 14:49 UTC, 0marperez reviewed
question: do S3s 403 responses frequently contain payloads? I think we would still fail with the same `Failed to parse response as ...` exception if that's the case

2024-08-06 14:49 UTC, 0marperez commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/S3OperationErrorHandler.kt
> +            withBlock("throw #T(#S).also {", "}", exceptionBaseSymbol, "Failed to parse response as ${ctx.protocol.name}") {
style: I would vote for keeping the mention that this is an error in the exception message. It's kind of useful for determining where the exception happened

2024-08-06 14:51 UTC, 0marperez commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/S3OperationErrorHandler.kt
> +            withBlock("throw #T(#S).also {", "}", exceptionBaseSymbol, "Failed to parse response as ${ctx.protocol.name}") {
`Failed to parse response as '${ctx.protocol.name}' error`

2024-08-06 16:07 UTC, lauzadis commented
> question: do S3s 403 responses frequently contain payloads? I think we would still fail with the same `Failed to parse response as ...` exception if that's the case

HeadObject 403 never contains a payload. Here is a sample codegen:
```kt
private fun throwHeadObjectError(context: ExecutionContext, call: HttpCall, payload: ByteArray?): kotlin.Nothing {
    val wrappedResponse = call.response.withPayload(payload)
    val wrappedCall = call.copy(response = wrappedResponse)

    val errorDetails = try {
        if (payload == null) {
            if (call.response.status == HttpStatusCode.NotFound) {
                S3ErrorDetails(code = "NotFound")

            } else {
                S3ErrorDetails(code = call.response.status.toString())

            }
        } else {
            checkNotNull(payload) { "unable to parse error from empty response" }
            parseS3ErrorResponse(payload)

        }
    } catch (ex: Exception) {
        throw S3Exception("Failed to parse response as restXml").also {
            setS3ErrorMetadata(it, wrappedCall.response, null)
        }
    }
    val ex = when(errorDetails.code) {
        "NotFound" -> NotFoundDeserializer().deserialize(context, wrappedCall, payload)
        else -> S3Exception(errorDetails.message)
    }

    setS3ErrorMetadata(ex, wrappedResponse, errorDetails)
    throw ex
}
```

I'm not sure how a 403 with a non-null payload will get an `Failed to parse response as restXml error` exception thrown unless it's malformed.

2024-08-06 16:18 UTC, ianbotsf requested changes
**Correctness**: Add E2E test(s) please.

2024-08-06 16:18 UTC, ianbotsf commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/S3OperationErrorHandler.kt
>                  }
**Question**: Isn't `call.response.status.toString()` also correct if the status code is `NotFound`? Do we _need_ the special case for `NotFound` in this `if` block?

2024-08-06 16:18 UTC, ianbotsf commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/S3OperationErrorHandler.kt
> +            }
**Question**: Why does this `else` block still have a `checkNotNull(payload)` in it? The `if` condition was that `payload == null` so it should be impossible for `payload` to be `null` in this `else` block.

2024-08-06 16:24 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/S3OperationErrorHandler.kt
> +            }
Yeah, it's probably not necessary, this was carried over from the previous codegen

2024-08-06 16:24 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/S3OperationErrorHandler.kt
>                  }
Actually it would be `Not Found` for a 404. We map it to "NotFound" which is how S3 models it.

2024-08-06 16:48 UTC, ianbotsf commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/S3OperationErrorHandler.kt
>                  }
Does `code` have to match an S3 error code? Because `call.response.status.toString()` won't necessarily.

2024-08-09 21:05 UTC, ianbotsf approved these changes

2024-08-13 18:12 UTC, 0marperez approved these changes

2024-08-13 18:17 UTC, merged