Create new codegen module and refactor annotation processor to use it
aws/aws-sdk-kotlin pull request #1382
Opened 2024-08-12 15:06 UTC by lauzadis

## Issue \#

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-12 16:12 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/rendering/AnnotationRenderer.kt
> +        withBlock("internal object #L : #T<#L> by #T(", ")", converterName, Types.ItemConverter, className, Types.SimpleItemConverter) {
I made the ItemConverter and ItemSchema `internal`, is there any argument for keeping it `public`? I figured users would mainly interact with this through the codegenerated `getTable` function

2024-08-12 16:12 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/rendering/AnnotationRenderer.kt
> +            "public fun #1T.get#2LTable(name: String): #3T.#4L<#2L, #5L> = #6L(name, #7L)",
This is pretty hard to read so I'm open to suggestions on how to make it clearer, if any

2024-08-12 20:57 UTC, ianbotsf requested changes
Looks like a great start! In general I like the stuff you pulled out into a common module but I think we should be more zealous about using `#T` and type references rather than `#L` and names that we assume are in scope.

2024-08-12 20:57 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/rendering/AnnotationRenderer.kt
> +                }
**Question**: Not all properties are required. The nullability of the source type should be used to determine the nullability of the builder type. Should we tackle that now or in a future task? If not now, let's leave a `TODO`.

2024-08-12 20:57 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/rendering/AnnotationRenderer.kt
> +                withBlock("return #L(", ")", className) {
**Correctness**: Use `#T` and a `Type`.

2024-08-12 20:57 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/rendering/AnnotationRenderer.kt
> +        withBlock("internal object #L : #T<#L> by #T(", ")", converterName, Types.ItemConverter, className, Types.SimpleItemConverter) {
I'm guessing users will _often_ but _not necessarily_ access schemata/converters through the `getTable` function (e.g., for unit testing). We should make them `public` by default I think but this'll be one of the configurable settings for our codegen.

2024-08-12 20:57 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/rendering/AnnotationRenderer.kt
> +        renderBuilder()
**Question**: Rendering a builder will not always be necessary. Annotated classes may consist entirely of mutable public properties, in which case we should probably skip the builder. Should we tackle that now or in a future task? If not now let's at least leave a `TODO` here.

2024-08-12 20:57 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/rendering/AnnotationRenderer.kt
> +    private fun renderBuilder() {
**Suggestion**: Rendering builders is something we're likely to need to do in many different places. I suggest we abstract this up to **:hll:codegen** and make it reusable.

2024-08-12 20:57 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/rendering/AnnotationRenderer.kt
> +    }
**Future**: Leave a `TODO` for handling composite keys in addition to single keys.

2024-08-12 20:57 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/rendering/AnnotationRenderer.kt
> +        }
**Comment**: I'll come back to these when I finish with the attribute converters PR. Can you add a `TODO` for filling this out please?

2024-08-12 20:57 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/rendering/AnnotationRenderer.kt
> +        }
**Future**: Leave a `TODO` for handling the last remaining key type: `ByteArray`.

2024-08-12 20:57 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/rendering/AnnotationRenderer.kt
> +            "public fun #1T.get#2LTable(name: String): #3T.#4L<#2L, #5L> = #6L(name, #7L)",
Haha, this may be the most complex parameterized template in our entire code base! 😆 A few things:

I think we should consider `Table.PartitionKey` to be a `Type`, instead of considering `Table` as the type and suffixing it with a dot and string name. I don't think `Type` adequately handles nested types right now so the auto-import logic would fail but we should probably fix that too.

Furthermore, we should treat `Table.PartitionKey` as a parameterized type and have a factory for it in `Types` such that we can do something like `Types.tablePartitionKey(objectType, keyType)` to get a comprehensive `Type` reference that would replace all of `#3T.#4L<#2L, #5L>`.

Lastly, I find template placeholders difficult to read when smooshed inside of a name token (e.g., `get#2LTable`) so I'd probably recommend `val methodName = "get${className}Table` and then `#L` substitution for the entire method name.

2024-08-12 20:57 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/MapperProcessor.kt
>              .filter { it.validate() }
**Nit**: This list isn't a list of "annotations", it's a list of "annotated classes".

2024-08-12 20:57 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/rendering/HighLevelRenderer.kt
> +) {
**Nit**: Commented elsewhere but `annotations` doesn't actually contain annotations, it's a list of annotated classes.

2024-08-12 20:57 UTC, ianbotsf commented on hll/codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/model/Type.kt
> +
**Correctness**: Nothing mapper- or DynamoDB-specific belongs in this file/module. We'll probably need a generic-level `Types` in this generic module and a use case-level `MapperTypes` in **dynamodb-mapper-annotation-processor**.

2024-08-12 21:39 UTC, ianbotsf commented on hll/codegen/build.gradle.kts
> +}
Oh and that means this module should have a better name than **codegen** (which would get published as `aws.sdk.kotlin:codegen`). Perhaps **hll-codegen** or **hll-codegen-common** or something similar.

2024-08-13 14:18 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/MapperProcessor.kt
> +        logger.info("Found invalid classes $invalid")
I'm not sure, this validation is something done by KSP

2024-08-13 14:34 UTC, lauzadis commented on hll/codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/model/Type.kt
> +
We also need some of these `MapperTypes` in **dynamodb-mapper-ops-codegen**, we probably need a shared package between all of the dynamodb-mapper modules where we could place these shared types

2024-08-13 14:45 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/build.gradle.kts
>              }
Will the annotation processor itself be published? I thought we would only be exposing it through the Gradle plugin

2024-08-13 14:46 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/MapperProcessor.kt
> +        invoked = true
I'm not sure exactly, it might mean we're doing repetitive work within the same Gradle build, this aims to avoid that.

I was following the style of `HighLevelOpsProcessor`, is there a reason `invoked` exists there but shouldn't here?

2024-08-13 14:48 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/rendering/AnnotationRenderer.kt
> +) : RendererBase(ctx, "${classDeclaration.qualifiedName!!.getShortName()}Schema") {
I agree but it also doesn't _just_ generate schemas. Lacking a better name suggestion, I'll rename it to `SchemaRender` for now

2024-08-13 14:49 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/rendering/AnnotationRenderer.kt
> +        renderBuilder()
I think I would add that consideration and configurability as part of the future codegen configuration task. Users might have classes consisting of entirely mutable public properties and still want a builder generated. I'll add a TODO for now.

2024-08-13 16:15 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/build.gradle.kts
>              }
Spoke offline, it _will_ need to be published, so I'll add some metadata for the public

2024-08-13 16:20 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/rendering/AnnotationRenderer.kt
> +                }
I'll handle that one now since it's not subject to configuration

2024-08-13 16:42 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-annotation-processor/jvm/src/aws/sdk/kotlin/hll/dynamodbmapper/processor/rendering/AnnotationRenderer.kt
> +                write("public var #L: #L? = null", it.name, it.typeName.asString())
I was manually importing the user's class to account for different packages / files but using `#T` is better

2024-08-15 22:01 UTC, ianbotsf approved these changes
Nice improvements! No blocking concerns left for me so leaving an approval conditional on addressing the remaining nits and questions. Style and suggestion comments optional.

2024-08-16 14:13 UTC, lauzadis commented on hll/codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/rendering/BuilderRenderer.kt
> +) {
I agree, let me try to stop the bleeding by just passing a `TypeRef`

2024-08-16 14:16 UTC, lauzadis commented on hll/codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/rendering/RendererBase.kt
> +) : CodeGenerator by ctx.codegenFactory.generator(fileName, ctx.pkg, rendererName) {
Nice suggestion, I like it!

2024-08-16 14:22 UTC, lauzadis commented on hll/codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/rendering/RendererBase.kt
> +}
No reasons besides that I completely looked over `apply`, removed it!

2024-08-16 14:23 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/api/dynamodb-mapper-codegen.api
No, there shouldn't be an apiDump for codegen, I have it in the `ignoredProjects` of apiValidation, so let me see why it's not working as expected...

2024-08-16 15:09 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper/build.gradle.kts
Yes we should, thanks for catching that

2024-08-16 15:11 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/api/dynamodb-mapper-codegen.api
Fixed by adding "hll-codegen" to the ignoredProjects and deleting the existing API files

2024-08-16 16:11 UTC, lauzadis commented on hll/codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/core/TemplateProcessor.kt
>              } else if (existingImport.fullName != type.fullName) {
Good point, I added it as `baseName`, let me know if you think it should have a different name

2024-08-16 16:15 UTC, ianbotsf commented on hll/codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/core/TemplateProcessor.kt
>              } else if (existingImport.fullName != type.fullName) {
Sounds great to me!

2024-08-16 16:18 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
> +
We spoke offline and both agreed it's weird, we're going to live with it and see if a solution becomes more necessary / clear. 

Some possible solutions include using ksp DSL's `arg` to pass a mode (enabled / disabled) to the KSP processors. Another option is to replace `excludeProcessor` with a custom DSL function like `singleProcessor(...)` or `includeProcessor(...)`

2024-08-16 16:27 UTC, lauzadis commented on hll/codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/rendering/BuilderRenderer.kt
> +) {
I think I've got a way cleaner signature now:
```kt
/**
 * A DSL-style builder renderer.
 * @param renderer The base renderer in which the builder will be written
 * @param classType The [TypeRef] representing the class for which a builder will be generated
 * @param members The [Set] of members of [classType] which will be included in the builder
 */
class BuilderRenderer(
    private val renderer: RendererBase,
    private val classType: TypeRef,
    private val members: Set<Member>
) { ... }
```

2024-08-16 16:27 UTC, lauzadis commented on hll/codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/rendering/BuilderRenderer.kt
> +}
I didn't realize `TypeRef` already had a `nullable`, I was able to remove this entire class and just use `Member`

2024-08-16 17:53 UTC, 0marperez approved these changes

2024-08-19 20:15 UTC, merged