feat: smoke tests
aws/aws-sdk-kotlin pull request #1388
Opened 2024-08-23 14:18 UTC by 0marperez

## Issue \#

## Description of changes

Adds gradle support for smoke tests

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-23 20:02 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/GradleGenerator.kt
> +
You can access `ctx.settings` in `generateGradleBuild`, do you need this atomic boolean / `enabledForService`?

2024-08-23 20:02 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/GradleGenerator.kt
> +                    withBlock("register<Jar>(\"smokeTestJar\") {", "}") {
Use #S instead of managing the quotes yourself

2024-09-16 15:48 UTC, ianbotsf requested changes

2024-09-16 15:48 UTC, ianbotsf commented on settings.gradle.kts
> +
**Correctness**: The **tests/** modules are intended to test our own SDK-developed code. These smoke tests will actually be verifying model correctness, which is a slightly different scope and intent. Moreover, I believe we'll want to package these up and distribute them to test runners at some point, which is more reason for them not to live here.

Have we explored codegenning into the **services/** modules directly? We don't have to include them in the main publication (so they're _not_ included in our Maven Central artifacts) but we can create a new publication that would include them separately.

2024-09-16 15:48 UTC, ianbotsf commented on tests/codegen/smoke-tests/src/test/kotlin/SmokeTestE2ETest.kt
> +    }
**Question**: Are any of these tests SDK specific? Could they live in **smithy-kotlin** instead?

2024-09-16 15:48 UTC, ianbotsf commented on tests/codegen/smoke-tests/src/test/resources/smoke-tests-failure.smithy
> +}
**Question**: Were these model files copied or adapted from somewhere? If so, let's include a comment with a link back to them in case we ever need to refresh them. (If you wrote these from scratch then never mind!)

2024-09-16 20:35 UTC, 0marperez commented on tests/codegen/smoke-tests/build.gradle.kts
> +    }
Oh I see, this task only cleans `<sdk root dir>/tests/codegen/smoke-tests/services`. That's the directory where the code-generated services for the E2E tests go. It doesn't clean the `<sdk root dir>/services` folder. I don't see a case where we should be writing any code there but I can see how it's unsafe. I added it as a QOL utility I guess. It's not necessary though so I can get rid of it.

2024-09-16 20:35 UTC, 0marperez commented on tests/codegen/smoke-tests/build.gradle.kts
> +                    packageVersion = "1.0"
With the SDK version? Is there a reason why? These projections are just for testing

2024-09-16 20:35 UTC, 0marperez commented on settings.gradle.kts
> +
The actual smoke tests runners are being code-generated directly into the `services` module. The path is something like: `<sdk root dir>/services/<relevant service>/generated-src-jvm/test/java/aws/sdk/kotlin/services/<relevant service>/smoketest/SmokeTests.kt`. This block of code is for including the code-generated services that are meant for E2E testing into the project.

2024-09-16 20:35 UTC, 0marperez commented on tests/codegen/smoke-tests/src/test/kotlin/SmokeTestE2ETest.kt
> +    }
They're sort of SDK specific. The tests and infra around them mock the setup we have for copying directories from the smithy projections into the dedicated services folders. So mocking `<sdk root dir>/services/<relevant service>` but in `<sdk root dir>/tests/codegen/smoke-tests/services/<relevant service>` for our tests. This includes the `gg smokeTest` task that I created for the SDK repo and that is not available in smithy kotlin.

They also test the actual runner which doesn't _need_ to be tested in the SDK but it's a lot easier to test here rather than in smithy kotlin. If we move the tests to smithy kotlin we would lose a lot of test coverage around all this SDK specific stuff I mentioned.

2024-09-16 20:35 UTC, 0marperez commented on tests/codegen/smoke-tests/src/test/resources/smoke-tests-failure.smithy
> +}
These were very loosely based on [this example](https://smithy.io/2.0/additional-specs/smoke-tests.html#smoke-tests-example). I don't know if we need to keep up to date with it though, they're only very loosely based on the example. If something changes in the smithy syntax, then the E2E tests would probably break anyway. Do you feel like we should link that example? And do you have a reason in mind for why we should?

2024-09-16 21:24 UTC, ianbotsf commented on settings.gradle.kts
> +
Oh I think I must've gotten confused by the word "services". So **/tests/codegen/smoke-tests/services** contains generated clients for the services defined in **[smoke-tests-failure.smithy](https://github.com/awslabs/aws-sdk-kotlin/pull/1388/files/d7a4877515ccb0aad6fa5405d49b39ae01d6fa87#diff-515b98ec7be69d02b783d537019d7eaf5f6bbc07706c7e467a9469ca945e4616)** and **[smoke-tests-success.smithy](https://github.com/awslabs/aws-sdk-kotlin/pull/1388/files/d7a4877515ccb0aad6fa5405d49b39ae01d6fa87#diff-5f83884c293fdcd749bb400ed751339c5d831107d77e6e104dddb9f3c77c0b02)**? Our other **tests/** projects generate those into a **build** directory so they get cleaned automatically, don't get checked-in, etc. It also means that the set of loaded Gradle subprojects isn't changing dynamically.

For example, our [event streams test project](https://github.com/awslabs/aws-sdk-kotlin/tree/86c002df182c4d864ad74b931ce9be45faa77f72/tests/codegen/event-stream) codegens the client, model, and serde files into **tests/codegen/event-stream/build/smithyprojections/event-stream/restJson1/kotlin-codegen**.

Can we do something similar here?

2024-09-16 21:26 UTC, ianbotsf commented on tests/codegen/smoke-tests/build.gradle.kts
> +                    packageVersion = "1.0"
If config this is just for generated service clients _from the smoke tests test suite_ then it doesn't matter. Disregard!

2024-09-16 21:28 UTC, ianbotsf commented on tests/codegen/smoke-tests/src/test/resources/smoke-tests-failure.smithy
> +}
No, we only need a link if it's something we think should be kept up-to-date with some source. Seems like that's not necessary here so never mind.

2024-09-16 21:31 UTC, ianbotsf commented on tests/codegen/smoke-tests/src/test/kotlin/SmokeTestE2ETest.kt
> +    }
> the setup we have for copying directories from the smithy projections into the dedicated services folders
Can you elaborate more? Is this setup defined in our smoke test generators or our manually-maintained build files?

2024-09-17 14:38 UTC, 0marperez commented on tests/codegen/smoke-tests/src/test/kotlin/SmokeTestE2ETest.kt
> +    }
The smoke tests integration from smithy kotlin [writes](https://github.com/smithy-lang/smithy-kotlin/blob/4e58bbd672dff777e19b31fe9d0559182c180d03/codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/smoketests/SmokeTestsIntegration.kt#L23) the smoke test runner file to `<relevant service smithy projection dir>/jvm-src/test/java/` and then the `stageSdks` task that we created [moves](https://github.com/awslabs/aws-sdk-kotlin/blob/d7a4877515ccb0aad6fa5405d49b39ae01d6fa87/codegen/sdk/build.gradle.kts#L179-L182) the whole `jvm-src` directory into the `<sdk root dir>/services/<relevant service>/generated-src-jvm` directory. 

This is also done for the regular service code generated code. I'm not sure where `<relevant service smithy projection dir>/src` is created but you can see where it is [copied](https://github.com/awslabs/aws-sdk-kotlin/blob/d7a4877515ccb0aad6fa5405d49b39ae01d6fa87/codegen/sdk/build.gradle.kts#L175-L178) over to `<sdk root dir>/services/<relevant service>/generated-src` in the `stageSdks` task.

2024-09-17 14:38 UTC, 0marperez commented on settings.gradle.kts
> +
> So /tests/codegen/smoke-tests/services contains generated clients for the services defined in [smoke-tests-failure.smithy](https://github.com/awslabs/aws-sdk-kotlin/pull/1388/files/d7a4877515ccb0aad6fa5405d49b39ae01d6fa87#diff-515b98ec7be69d02b783d537019d7eaf5f6bbc07706c7e467a9469ca945e4616) and [smoke-tests-success.smithy](https://github.com/awslabs/aws-sdk-kotlin/pull/1388/files/d7a4877515ccb0aad6fa5405d49b39ae01d6fa87#diff-5f83884c293fdcd749bb400ed751339c5d831107d77e6e104dddb9f3c77c0b02)?

Yeah, that's right

> For example, our [event streams test project](https://github.com/awslabs/aws-sdk-kotlin/tree/86c002df182c4d864ad74b931ce9be45faa77f72/tests/codegen/event-stream) codegens the client, model, and serde files into tests/codegen/event-stream/build/smithyprojections/event-stream/restJson1/kotlin-codegen.

> Can we do something similar here?

I don't think we can because the generated test services need to be inside a gradle project so we can run the `gg smokeTest` task. I'm not sure that we can run a gradle task from the `build` directory.

2024-09-18 17:32 UTC, ianbotsf commented on settings.gradle.kts
> +
Our other codegen tests _also_ need to be run after generating them. The event streams tests [generate sources via our Smithy build plugin](https://github.com/awslabs/aws-sdk-kotlin/blob/6f4673f4fd087faf7c1fab6ea9db2091dbc6707d/tests/codegen/event-stream/build.gradle.kts#L46-L77) (which go into the **build** dir) and then [add each of the generated client roots to the Kotlin source](https://github.com/awslabs/aws-sdk-kotlin/blob/6f4673f4fd087faf7c1fab6ea9db2091dbc6707d/tests/codegen/event-stream/build.gradle.kts#L109-L113). Then, statically written tests can [invoke the generated code](https://github.com/awslabs/aws-sdk-kotlin/blob/6f4673f4fd087faf7c1fab6ea9db2091dbc6707d/tests/codegen/event-stream/src/test/kotlin/RpcEventStreamTests.kt#L100).

It seems to me like a similar setup could work for the smoke tests: use Smithy build plugin (may require new options/tweaks to support smoke test codegen) to generate tests into the **build** dir and then invoke those tests in statically-written code.

One of my concerns here is repo hygene and consistency. We had to add new **.gitignore** entries for this which _seems_ wrong. Maybe it's not and this is the best option but I'd like to at least verify this can't be done in a manner more similar to other codegenned tests.

2024-09-23 14:09 UTC, lauzadis approved these changes

2024-09-23 14:09 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/GradleGenerator.kt
> +                        write("mustRunAfter(build)")
`dependsOn` and `mustRunAfter` seem redundant, why do we need both?

2024-09-23 16:40 UTC, ianbotsf approved these changes

2024-09-23 16:40 UTC, ianbotsf commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/GradleGenerator.kt
> +                        write("mustRunAfter(build)")
> And when running a task with the parallel flag , dependsOn only guarantees that the task that is depended on starts first but not that it ends first.

That's kind of surprising. Is that documented somewhere? Or were you seeing errors in the build without this ordering constraint?

2024-09-23 17:05 UTC, 0marperez commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/GradleGenerator.kt
> +                        write("mustRunAfter(build)")
I don't think it's documented anywhere but I was seeing errors in the build without the ordering constraint.

2024-09-24 19:56 UTC, ianbotsf approved these changes

2024-09-26 17:03 UTC, 0marperez commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/smoketests/SmokeTestFailHttpEngineIntegration.kt
> +            settings.sdkId !in smokeTestDenyList &&
It's not required, I ended up removing this check

2024-09-26 17:03 UTC, merged