Working
aws/aws-sdk-kotlin pull request #1392
Opened 2024-08-27 16:15 UTC by lauzadis

…#1382)

## Issue \#

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-28 17:14 UTC, ianbotsf requested changes

2024-08-28 17:14 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginTest.kt
> +             id("org.jetbrains.kotlin.jvm") version "2.0.0"
**Nit**: We're on Kotlin version 2.0.10 now.

2024-08-28 17:14 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginTest.kt
> +         }
**Question**: What exactly are we testing here?

2024-08-28 17:14 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginTest.kt
> +    fun `configures the plugin`() {
**Correctness**: There's a bit of duplication in this test with the existing test. Let's extract test environment/config to a helper method so we can reuse it in these tests. That'll also help with parameterizing the build later. I suspect we're going to want a suite of tests to run across a matrix of configurations, sort of like we do for our HTTP engine tests or our service benchmarks.

2024-08-28 17:14 UTC, ianbotsf commented on hll/dynamodb-mapper/tests/dynamodb-mapper-schema-generator-plugin-test/common/test/aws/sdk/kotlin/hll/dynamodbmapper/tests/plugins/UserTest.kt
> +//        val converted = UserConverter.toItem(user)
**Nit**: Add `// FIXME`

2024-08-28 17:14 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginExtension.kt
> +const val SCHEMA_GENERATOR_PLUGIN_EXTENSION = "schemaGeneratorPluginExtension"
**Style**: This is the name that gets provided as a convenience DSL method in users' build files right? If so, we should select a name that's more ergonomic like `"dynamoDbMapper"` or something.

2024-08-28 17:14 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPlugin.kt
> +        }
**Question**: Why does this need to be applied in `project.afterEvaluate`?

2024-08-28 17:14 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginTest.kt
> +         }
**Nit**: We should test (either here or in a new test) using the DSL method for this:

```kotlin
dynamoDbMapper {
    generateBuilderClasses = ...
}
```

2024-08-28 17:18 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/AnnotationsProcessor.kt
> +}
No problem, I wasn't sure exactly what we wanted to offer for configurability, this PR sets up the framework so adding those additional config options should be easy

2024-08-28 19:02 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/SchemaRenderer.kt
> +            },
I don't see the duplication besides checking `sortKeyProp != null`, one is ItemSchema and one is Table

2024-08-28 19:11 UTC, lauzadis commented on hll/hll-codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/model/Member.kt
>  }
Yes, we could. I thought it would be safer to require providing a value, but assuming immutability seems safe too

2024-08-28 19:26 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/SchemaRenderer.kt
> +        val alwaysGenerateBuilders = ctx.attributes.getOrNull(CodegenAttributes.AlwaysGenerateBuilders) ?: true
When using the plugin, yes, these will always be set. If somebody uses the annotation processor standalone (such as in our dynamodb-mapper-annotation-processor-test module), the attributes won't be set. 

Should we still try to support that use-case or will we assume people only use the annotation processor through the plugin?

2024-08-28 19:39 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPlugin.kt
> +        }
Without this, the default values of the args were passed to KSP without reading the user's extension configuration. I think it's because the plugin's `apply(...)` runs during the configuration stage which is before the configured extension is available.

2024-08-28 20:31 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginTest.kt
> +         }
Just checking that the config options exist / can be used

2024-08-28 21:05 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/SchemaRenderer.kt
> +        val alwaysGenerateBuilders = ctx.attributes.getOrNull(CodegenAttributes.AlwaysGenerateBuilders) ?: true
Good point. We should probably leave the door open for using the annotation processor standalone, which means we should probably get-or-default the values into attributes at some common level like `AnnotationsProcessor`.

2024-08-29 13:20 UTC, 0marperez approved these changes

2024-08-29 17:40 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/SchemaRenderer.kt
> +        Visibility.IMPLICIT -> "public"
I'm not sure what we should be doing with `Visibility.IMPLICIT`. I'm guessing it will change / get more refined in the future, but for now, `PUBLIC` and `IMPLICIT` are exactly the same.

2024-08-29 17:41 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/build.gradle.kts
> + */
This is annoying but required. Without this, the Gradle TestKit execution does not have access to any dependencies 
from smithy-kotlin / aws-sdk-kotlin

2024-08-29 17:42 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPlugin.kt
> +                is DestinationPackage.ABSOLUTE -> "absolute=${dstPkg.pkg}"
Any thoughts on this serialization method? KSP can only pass strings as args

2024-08-29 17:43 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/SchemaRenderer.kt
> +        Visibility.IMPLICIT -> "public"
`IMPLICIT` should be unspecified:

```kotlin
Visibility.IMPLICIT -> ""
```

2024-08-30 18:54 UTC, ianbotsf requested changes

2024-08-30 18:54 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/build.gradle.kts
> + */
Ooh, what about [this](https://discuss.gradle.org/t/testkit-for-plugin-that-depends-on-another-module-in-a-multi-module-build/42887/6)? Might something along those lines work?

2024-08-30 18:54 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPlugin.kt
> +                is DestinationPackage.ABSOLUTE -> "absolute=${dstPkg.pkg}"
The serialization format looks fine to me but I don't love the implementation details being spread across two modules. I suggest overriding `DestinationPackage.toString()` to generate the serialized form and adding a `DestinationPackage.fromString(...)` method to handle deserializing.

2024-08-30 18:54 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPlugin.kt
> +    SchemaGeneratorPlugin::class.java.getResource("sdk-version.txt")?.readText() ?: throw IllegalStateException("sdk-version.txt does not exist")
**Style**: `?: throw IllegalStateException` can be replaced with [`checkNotNull`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/check-not-null.html):

```kotlin
checkNotNull(SchemaGeneratorPlugin::class.java.getResource("sdk-version.txt")?.readText()) { "sdk-version.txt does not exist" }
```

2024-08-30 18:54 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginTest.kt
> +            id("org.jetbrains.kotlin.jvm") version "2.0.10"
**Nit**: Let's add a FIXME for un-hardcoding (softcoding?) the Kotlin version

2024-08-30 18:54 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginTest.kt
> +        } ?: error("Could not read $resourceName")
**Question**: You used a shortened syntax elsewhere for reading a resource into a string...is there any reason that won't work here?

```kotlin
checkNotNull(this::class.java.getResource("sdk-version.txt")?.readText()) { "Could not read $resourceName" }
```

2024-08-30 18:54 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginTest.kt
> +        )
**Question**: I'm a little iffy on asserting big codegen blocks in an integration-style test like this. Would it be feasible/better to add unit tests to the test projects and assert that Gradle ran them successfully (i.e., make the tests more _functional_ and less _literal_)?

2024-08-30 18:54 UTC, ianbotsf commented on hll/hll-codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/rendering/BuilderRenderer.kt
>                  members.forEach {
**Ponderance**: It's slightly irksome to me how we have to either accept unnecessary whitespace from our codegen (i.e., when `visibility == ""`, then we'll generate ` fun build():…`) or jump through extra hoops to pad non-empty/null placeholder values (i.e., `val visibilityPrefix = if (visibility.isNullOrEmpty) "" else "$visibility "`). It's the same in Smithy codegen but I wonder if our HLL codegen could simplify this somehow. 🤔 I don't have a concrete suggestion nor am I requesting you come up with something in the scope of this review—just wondering how we could streamline this in the future.

2024-09-03 13:37 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/AnnotationsProcessor.kt
> +        }
Probably because I had to use `.name` when passing the KSP args and it was carried over from a copy-paste

2024-09-03 13:38 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/AnnotationsProcessorOptions.kt
> +    IMPLICIT,
I think `Visibility.DEFAULT` sounds good

2024-09-03 13:38 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/AnnotationsProcessorOptions.kt
> +     * Constructs should be code-generated into a package RELATIVE to the class being processed. Defaults to mapper.schemas.
I think at one point these had link symbols `[RELATIVE]` but were lost during a refactor. I'll update to something like what you recommended

2024-09-03 13:41 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/AnnotationsProcessorOptions.kt
> +    IMPLICIT,
Looking at the Kotlin docs, I'm now wondering why we have separate options for `Visibility.DEFAULT` and `Visibility.PUBLIC` when they accomplish the same thing (`PUBLIC` does it explicitly). What do you think about defaulting to `PUBLIC` and removing `DEFAULT`?

2024-09-03 13:43 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/AnnotationsProcessorOptions.kt
> +    class ABSOLUTE(override val pkg: String = "mapper.schemas") : DestinationPackage()
Yeah I think that's a good idea

2024-09-03 13:46 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/SchemaRenderer.kt
> +        BuilderRenderer(this, classType, members, visibility).render()
Yeah since the BuilderRenderer is in **hll-codegen** and it uses visibility, it makes sense to lift `Visibility` to that level too

2024-09-03 13:56 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginTest.kt
> +            id("org.jetbrains.kotlin.jvm") version "2.0.10"
I ended up just fixing it by creating another resource file called `kotlin-version.txt`

2024-09-03 14:03 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginTest.kt
> +        )
It's feasible, and probably better. I was modeling these tests off of our other codegen tests which assert on the output. Those are a pain to update when you make a big change to the code generation so I'm in favor of replacing this with unit tests

2024-09-03 15:16 UTC, lauzadis commented on hll/hll-codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/rendering/BuilderRenderer.kt
>                  members.forEach {
One option (and what I did here in the latest revision) is add an extension method `Attributes.visibility` which handles the whitespace padding, then you just need to write `#Lfun build(...), ctx.attributes.visibility` and it will render all visibilities with the correct amount of whitespace.

Maybe we could make a new template token `#V` that renders the visibility and also consumes the following whitespace. So you could write `#V fun build(...)` and it will render `public ` and consume the whitespace following the `#V`

2024-09-03 16:06 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/AnnotationsProcessorOptions.kt
> +    IMPLICIT,
We spoke offline and agreed to reduce the options to `Visibility.PUBLIC` and `Visibility.INTERNAL` for now.

A few reasons to keep `Visibility.DEFAULT` were discussed:
1. IntelliJ displays a message when the `public` modifier is used unnecessarily (in non-explicit API mode)
1. Kotlin / JetBrains may change the meaning of an implicit/default/unspecified modifier in the future
	- We can address this change when/if it happens

2024-09-03 16:19 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/build.gradle.kts
> +    dependsOn(smithyKotlin.task(":runtime:auth:aws-signing-default:publishToMavenLocal"))
CI passes so I think it's safe to use Maven Local: https://github.com/awslabs/aws-sdk-kotlin/actions/runs/10686643498/job/29622369526?pr=1392

We can refactor in the future if we see issues with using it

2024-09-03 16:46 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/SchemaRenderer.kt
> +        val hasAllMutableMembers = classDeclaration.getAllProperties().all { it.isMutable }
`hasAllMutableMembers` _would_ be **false** in that example. Should annotation processing be ignoring private members entirely? Right now we'll still generate a builder entry / attribute descriptor for them.

2024-09-03 17:05 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginTest.kt
> +        )
I _thought_ it would be better to have unit test resources, but in practice these are pretty difficult to create and I envision will be difficult to maintain. There is no IDE support (autocompletion, error detection) when writing them because the schemas don't exist until the unit tests are run. So, I think asserting on the raw codegen output is better than having to maintain essentially plain-text unit tests.

We _can_ still have unit tests (see the last test in this file) but I think the majority of this plugin's tests can be successfully accomplished by asserting on the codegen output (i.e asserting a builder was / was not generated, asserting visibility of codegenerated classes / objects).

Do you have any oppositions to this approach? Is the issue that we're asserting on **large** blocks of text, would you rather see them made smaller?

2024-09-03 17:20 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/build.gradle.kts
> + */
`dependsOn(smithyKotlin.task("publishToMavenLocal"))` doesn't work because it doesn't start with `:`. For some reason [Gradle requires included build tasks to have this prefix](https://github.com/gradle/gradle/blob/master/subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuild.java#L164). I found a seemingly related GitHub issue: https://github.com/gradle/gradle/issues/22335 

I tried reading through that link you shared but didn't see anything immediately useful. I think the solution here is fine besides having to be exceedingly verbose, which should be fixed by that GH issue. 🤔  

Or maybe we can create a new task like `:publishSubprojectsToMavenLocal` in smithy-kotlin which `dependsOn` all the subprojects' publishToMavenLocal tasks, then we can just depend on that single task.

2024-09-03 17:26 UTC, ianbotsf commented on hll/hll-codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/rendering/BuilderRenderer.kt
>                  members.forEach {
Yeah extension methods like you made work, they just feel hyper-specific and will lead to boilerplate. A new token type is a good idea, although handling the space after something is not the only use case: we've got code that conditionally [prepends spaces](https://github.com/smithy-lang/smithy-kotlin/blob/b3d817c14bb5a31602ee38bb7189967a4b95875f/codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt#L183-L190), [appends non-spaces](https://github.com/smithy-lang/smithy-kotlin/blob/b3d817c14bb5a31602ee38bb7189967a4b95875f/codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpStringValuesMapSerializer.kt#L85-L86), etc. It'd be nice to have some token or other facility to handle all these weird cases.

Again, nothing needed for now. Just noodling.

2024-09-03 17:29 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/SchemaRenderer.kt
> +        val hasAllMutableMembers = classDeclaration.getAllProperties().all { it.isMutable }
Yes, I _think_ it should ignore private members altogether. 🤔 I wonder what kind of problems that could get us into...

2024-09-03 19:49 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginTest.kt
> +        )
I think asserting on codegen blocks for unit tests is "fine"—not really great but kinda necessary in some situations. (And in those situations yes, smaller blocks = better blocks.)

My issue is that this _isn't_ strictly a unit test—it's much more of an integration test because we're testing the Gradle plugin, our usage of KSP, and our codegen stack. We're operating at the scope where individual bytes of code output don't matter as much as functionality. That said, if the alternative (e.g., maintaining unit tests as text files) is so difficult to work with we may be stuck with this for now.

So if you're convinced codegen assertions are the more maintainable approach then let's got with that for now. And take whatever reasonable steps you can to trim down assertion blocks. Thanks for looking into it!

2024-09-03 19:51 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/build.gradle.kts
> + */
OK then we can live with the verbosity for now. Maybe leave a FIXME or TODO or something related to the Gradle issue you found.

2024-09-04 16:59 UTC, ianbotsf requested changes
Getting pretty close!

2024-09-04 16:59 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/AnnotationsProcessorOptions.kt
> +    internal abstract val pkg: String
**Nit**: Should be `public`

2024-09-04 16:59 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/AnnotationsProcessorOptions.kt
> +    public class Relative(override val pkg: String = "aws.sdk.kotlin.hll.dynamodbmapper.generatedschemas") : DestinationPackage()
**Correctness**: The default for relative package destinations shouldn't be something AWS-specific or very long because it's getting nested inside of a user's existing namespace. Something like `dynamodbmapper.generatedschemas` should suffice.

2024-09-04 16:59 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/build.gradle.kts
> +    inputs.file(gradlePropertiesFile)
**Correctness**: The Kotlin version isn't specified in **gradle.properties** anymore and so setting that as the input to this task means we may not run this task at the right times. We should be binding to [**gradle/libs.versions.toml**](https://github.com/awslabs/aws-sdk-kotlin/blob/main/gradle/libs.versions.toml).

2024-09-04 16:59 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginExtension.kt
> +open class SchemaGeneratorPluginExtension {
**Nit**: This `SCHEMA_GENERATOR_PLUGIN_EXTENSION` constant shouldn't be `public` (probably `internal` at best).

**Correctness**: This `SchemaGeneratorPluginExtension` should definitely be (explicitly) `public`. Seeing that it's not made me realize we're not correctly enforcing API compatibility in this module either. 🥲 We should turn on the binary compat checker and then adjust all the implicit visibilities that result.

2024-09-04 16:59 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/build.gradle.kts
> +}
**Nit**: Now that we're doing this in multiple places (including deeply-nested subprojects like this one) we should probably extract it into something simple/reusable in [**build-support**](https://github.com/awslabs/aws-kotlin-repo-tools/tree/main/build-plugins/build-support). That's well outside the scope of this PR so let's just add a FIXME here for now.

2024-09-04 17:48 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginExtension.kt
> +open class SchemaGeneratorPluginExtension {
We are enforcing API compatibility in this module (there is a .api file), but `explicitApi()` was not enabled. I'll enable it and add visibilities

2024-09-04 22:47 UTC, ianbotsf approved these changes

2024-09-06 14:22 UTC, merged