feat: basic annotation processing
aws/aws-sdk-kotlin pull request #1399
Opened 2024-09-06 19:50 UTC by lauzadis

## Issue \#

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-09-16 20:40 UTC, lauzadis commented on hll/hll-codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/core/TemplateProcessor.kt
I added `args` to `TypeRef` so that map and list converters could be code-generated properly

For example, a `Map<String, List<String>>` needs to have a value converter code generated like this: `            MapConverter(aws.sdk.kotlin.hll.dynamodbmapper.values.scalars.TextConverters.StringToStringConverter, ListConverter(StringConverter))` 

I was having trouble finding a clean way to render these arguments (`ListConverter(**StringConverter**)`), which these news `args` solved. 

One possible solution is to pass the writer into `KSType.valueConverter` function and render the arguments as-needed, but I didn't like the idea of passing around the writer. Maybe it is the better option though, I'm open to suggestions

2024-09-17 16:09 UTC, ianbotsf requested changes

2024-09-17 16:09 UTC, ianbotsf commented on hll/hll-codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/core/TemplateProcessor.kt
Hmm, I see. 🤔 Well I understand what it gains us here but it feels like contorting the _intent_ of type references and trying to bundle a lot of information into a string that's much more complex than that (at _this_ point of codegen). We may decide that's good enough but I _suspect_ we can come up with a cleaner separation.

FWIW, I agree that passing around the writer is not great so, instead of passing the _writer_ to the rendering logic, what if we pass the _rendering logic_ to the writer?

**Thought exercise:** We could make a new template processor `#X` (for e**X**ecute) that operates on a lambda. I'm not precisely sure that the inputs to the lambda would be—possibly some context about the line, the other parameters, or maybe just nothing—but the output could be a new string template and accompanying args, which the template engine would then process recursively.

The combination of a string template and accompanying args is what we use as the main input to most of the additive writer methods (e.g., `write`, `withBlock`, etc.) but it could _also_ be used as fragment in the middle of a larger template. So perhaps a new template processor `#F` to interpolate those (again, recursively).

In combination, that means your `SchemaRenderer` would no longer map a type name (e.g., `"kotlin.String"`) to a converter `TypeRef` (e.g., `MapperTypes.Values.Scalars.StringConverter`) but rather to a template fragment, which would include a `#T` placeholder for the map converter type, plus two `#X` placeholders for the argument types. And in fact, now that we've defined a fragment as (template, args), that's probably what the _output_ of `#X` lambdas are.

One final wrinkle: I think since both of these new placeholder types (execute and fragment) require recursive processing, their processors probably need a reference to the `TemplateEngine` itself. This is a bit of a circular dependency so it gets a little chicken-and-egg but we could consider passing the engine as a parameter into processors generally, or these processors specifically.

How does this idea sound?

2024-09-17 16:18 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/SchemaRenderer.kt
> +            this.isUserClass -> TypeRef(ctx.pkg, "${this.declaration.simpleName.asString()}ValueConverter")
What if we require users to annotate _properties_ with `@DyanmoDbItem` in these cases? The users would pass the fully qualified class as a parameter (by default it'd be inferred as a class in the same package). I think that would eliminate the ambiguity for these nested types.

2024-09-17 19:27 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/HighLevelRenderer.kt
> +                val annotatedTypeName = annotated.qualifiedName?.asString()
Their docs say "might not exist for some declarations like local declarations". This is on `KSDeclaration` while we have a `KSClassDeclaration` here which I think(?) will never be a local declaration. I'll add `requireNotNull` anyways

2024-09-17 19:53 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/SchemaRenderer.kt
> +        }
This doesn't work because `ItemConverter` is a separate interface from `Converter` and then `andThenFrom` function you're referring to is defined on Converters. Should `ItemConverter` interface be refactored to implement `Converter<V, Item>`?

2024-09-18 17:41 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/SchemaRenderer.kt
> +        }
🤦‍♂️ Yes, I should've done that as part of my [attribute converter overhaul](https://github.com/awslabs/aws-sdk-kotlin/pull/1381).

2024-09-18 21:14 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/SchemaRenderer.kt
> +        get() = listOf("kotlin", "java", "aws.smithy.kotlin", "aws.sdk.kotlin").none { declaration.packageName.asString().startsWith(it) }
Updated to check if the class has the `DynamoDbItem` annotation. This seems to be the correct heuristic and it also has the added benefit of making unannotated classes throw an error during schema generation

2024-09-18 21:34 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/operations/HighLevelOpsProcessor.kt
> +            val codegenFactory = CodeGeneratorFactory(codeGenerator, logger) // FIXME Pass dependencies
FYI: I could not figure out how to get a list of dependencies for the ops code generator, I kept getting `null` values when trying to find the file which contains `DynamoDbClient`

2024-09-18 23:07 UTC, ianbotsf requested changes
Looks pretty good, just a few small things left.

2024-09-18 23:07 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper/common/src/aws/sdk/kotlin/hll/dynamodbmapper/values/ItemToValueConverter.kt
> +}
**Nit**: KDocs

2024-09-19 13:14 UTC, lauzadis commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/standard-item-converters/src/Lists.kt
> +        }
Oh, that's what I had in the beginning. I think I missed it / forgot to mention after your first comment, but I was always checking the size of the lists

https://github.com/awslabs/aws-sdk-kotlin/pull/1399#discussion_r1763442300

2024-09-19 15:02 UTC, ianbotsf commented on hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/standard-item-converters/src/Lists.kt
> +        }
Oh wow, my eyes totally skipped past that. I apologize. What you originally had was fine.

2024-09-19 15:04 UTC, ianbotsf approved these changes

2024-09-19 15:22 UTC, merged