misc: credentials search precedence change
aws/aws-sdk-kotlin pull request #1434
Opened 2024-10-07 15:43 UTC by 0marperez

## Issue \#

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-10-07 20:15 UTC, ianbotsf requested changes

2024-10-07 20:15 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/profile/ProfileChain.kt
> +    if (!contains(CREDENTIAL_PROCESS)) return LeafProviderResult.Err("profile ($name) did not contain credential information")
**Nit**: Throwing the chain-level no-creds-in-profile exception feels like a concern which should live _outside_ this method (whose job it is to return _process_ credentials).

2024-10-07 20:15 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/profile/ProfileChain.kt
>          else -> {
**Comment**: Nice improvement to this error message. 👍

2024-10-07 20:15 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/profile/ProfileChain.kt
**Question**: It feels like the precedence logic is a bit spread out in this file (some of which predates your changes). How easy/possible would it be to centralize the logic into a single place, preferably as a data structure like a list, so that we had a single place to look for the ordering specifically? (Not saying to move the actual resolution logic into a single place, just the precedence order.)

2024-10-08 13:49 UTC, 0marperez commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/profile/ProfileChain.kt
It's possible, and I think it would make this file more readable. I think it would take maybe a day or two of just working on this to refactor it to use a list and have the assume role logic fit into that.

2024-10-08 13:50 UTC, 0marperez commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/profile/ProfileChain.kt
>          else -> {
Thanks!

2024-10-08 13:50 UTC, 0marperez commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/profile/ProfileChain.kt
> +                if (leaf != null) break@loop
The change in order makes it unnecessary. The check was there because static credentials were of highest precedence in the assume role profile only. Now that static credentials are always highest precedence there's no need to check if we're in the `1 + n` visited  profile.

2024-10-08 13:50 UTC, 0marperez commented on .changes/announcement.md
> +6. Process
I didn't combine them because of concerns I had about how users would tell apart profile only credentials locations. I think maybe using `4.x` for the profile chain would work or indentation.

2024-10-08 14:39 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/profile/ProfileChain.kt
OK then unless you've already started on it then let's skip the refactor for now. Let's just address the other comments and get this shipped.

2024-10-08 15:56 UTC, lauzadis reviewed
correctness: this PR is missing the emission of business metrics

2024-10-08 15:56 UTC, lauzadis commented on .changes/0b5b53ab-70c0-4c1b-a445-8663ae86d6d1.json
correctness: Add requiresMinorVersionBump

2024-10-08 15:56 UTC, lauzadis commented on .changes/announcement.md
> +6. Process
It can also be made clearer if you separate these into two separate sections (`## Default credentials provider chain`, `## Profile credentials provider`)

2024-10-10 16:01 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/DefaultChainCredentialsProvider.kt
>          val wrapped = StsWebIdentityCredentialsProvider.fromEnvironment(platformProvider = platformProvider, httpClient = httpClient, region = region)
`StsWebIdentityCredentialsProvider` is already public, why do we need to make the wrapper class public too?

2024-10-10 16:37 UTC, 0marperez commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/DefaultChainCredentialsProvider.kt
>          val wrapped = StsWebIdentityCredentialsProvider.fromEnvironment(platformProvider = platformProvider, httpClient = httpClient, region = region)
The wrapper delays any exceptions until `resolve()` is called so it can be part of a credentials provider chain. Without the wrapper some exceptions are thrown outside of the `resolve()` call and not caught by the credentials provider chain.

For example using the client below, if there's no valid env config for `StsWebIdentityCredentialsProvider` an exception is thrown early.
```kotlin
S3Client{
    region = "us-west-2"
    credentialsProvider = CredentialsProviderChain(
        SystemPropertyCredentialsProvider(),
        EnvironmentCredentialsProvider(),
        StsWebIdentityCredentialsProvider.fromEnvironment(),
        ProfileCredentialsProvider(),
        EcsCredentialsProvider(),
        ImdsCredentialsProvider(),
    )
}.use { client ->
    client.listBuckets(ListBucketsRequest{})
}
```
```
Exception in thread "main" aws.sdk.kotlin.runtime.auth.credentials.ProviderConfigurationException: Required field `roleArn` could not be automatically inferred for StsWebIdentityCredentialsProvider. Either explicitly pass a value, set the environment variable `AWS_ROLE_ARN`, or set the JVM system property `aws.roleArn`
```
Instead of what we want:
```
Exception in thread "main" aws.smithy.kotlin.runtime.identity.IdentityProviderException: No identity could be resolved from the chain: CredentialsProviderChain -> SystemPropertyCredentialsProvider -> EnvironmentCredentialsProvider -> StsWebIdentityProvider -> ProfileCredentialsProvider -> EcsCredentialsProvider -> ImdsCredentialsProvider .......
```

2024-10-10 16:38 UTC, 0marperez commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/DefaultChainCredentialsProvider.kt
>          val wrapped = StsWebIdentityCredentialsProvider.fromEnvironment(platformProvider = platformProvider, httpClient = httpClient, region = region)
Tbh I think the name doesn't help

2024-10-10 17:00 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/DefaultChainCredentialsProvider.kt
>          val wrapped = StsWebIdentityCredentialsProvider.fromEnvironment(platformProvider = platformProvider, httpClient = httpClient, region = region)
I think it's fine for the chain to fail early when users are manually configuring a custom chain. We just don't want it to fail early in the default chain because not every user will have a valid environment config

2024-10-10 18:09 UTC, 0marperez commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/DefaultChainCredentialsProvider.kt
>          val wrapped = StsWebIdentityCredentialsProvider.fromEnvironment(platformProvider = platformProvider, httpClient = httpClient, region = region)
I think we should avoid failing early in any credentials provider chain not just the default one. IMO a credentials provider chain is supposed to keep looking for credentials and only fail once the options are exhausted. If we fail early it could be seen as a bug.

2024-10-11 21:44 UTC, ianbotsf approved these changes

2024-11-04 21:07 UTC, merged