misc: credentials business metrics
aws/aws-sdk-kotlin pull request #1442
Opened 2024-10-16 14:34 UTC by 0marperez

## Issue \#

## Description of changes

-Emitting credentials related business metrics
-Tests for credentials related business metrics

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-10-17 13:19 UTC, lauzadis commented on aws-runtime/aws-config/common/test-resources/default-provider-chain/imds_assume_role/test-case.json
> +      "business_metrics": ["p","0", "i"]
If this is just meant to resolve credentials from IMDS, why are there three credentials provider metrics emitted?

2024-10-17 13:19 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/profile/ProfileChain.kt
> +    val roleArnSource: RoleArnSource? = null,
naming: `source` makes this more readable, `roleArn.source` vs. `roleArn.roleArnSource`

2024-10-17 13:19 UTC, lauzadis commented on aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/auth/credentials/ProfileCredentialsProviderTest.kt
> +    fun staticCredentialsBusinessMetrics() = runTest {
naming: static -> profile

2024-10-17 13:19 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/BusinessMetricsIntegration.kt
> +                "if (config.credentialsProvider.#T != #S ) {",
Compare classes directly rather than their simple names, `if (config.credentialsProvider !is ManagedCredentialsProvider)`

2024-10-17 13:19 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/BusinessMetricsIntegration.kt
> +                    "op.context.#T(#T.Credentials.CREDENTIALS_CODE)",
This middleware will emit `CREDENTIALS_CODE` any time a custom credentials provider is configured and used. I thought that this metric referred to using the `StaticCredentialsProvider`. 

If someone configures a custom `ProfileCredentialsProvider`, should we really not be emitting the `CREDENTIALS_PROFILE` metric?

2024-10-17 13:19 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/StsWebIdentityCredentialsProvider.kt
> +    private var createdFromEnvironment: Boolean = false
I understand why you needed to add this but it seems a little hacky. 

We only call `StsWebIdentityCredentialsProvider.fromEnvironment` in one spot, the default chain, can the metrics emission for that be lifted to that point and then we can remove this `createdFromEnvironment` here?

2024-10-17 14:12 UTC, 0marperez commented on aws-runtime/aws-config/common/test-resources/default-provider-chain/imds_assume_role/test-case.json
> +      "business_metrics": ["p","0", "i"]
The test actually uses [this](https://github.com/awslabs/aws-sdk-kotlin/blob/main/aws-runtime/aws-config/common/test-resources/default-provider-chain/imds_assume_role/fs/home/.aws/config) config file. So `p` is for the named provider, `0` is for IMDS, and `i` is for the assume role call with the credentials resolved from IMDS. I think it might be a good idea to change the docs for this test because I made the same assumption when I first added the business metrics.

2024-10-17 14:18 UTC, 0marperez commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/BusinessMetricsIntegration.kt
> +                    "op.context.#T(#T.Credentials.CREDENTIALS_CODE)",
`CREDENTIALS_CODE` is meant for when there's any code to setup credentials, so configuring a custom / non-default credentials provider, the `StaticCredentialsProvider`, session objects for boto, etc. We don't have a business metric for `StaticCredentialsProvider` but it falls under `CREDENTIALS_CODE`. We could get more specific in the future though, we would just have to discuss adding a metric for something like the `StaticCredentialsProvider` that all SDKs share.

`CREDENTIALS_PROFILE` is confusing, it's meant for static credentials in a profile. It was called something else but I think the name changed during review. Same as `StaticCredentialsProvider`, we don't have a metric for `ProfileCredentialsProvider`. The focus for the initial metrics was more on the default credentials provider chain related metrics not all credentials providers but we can go back and more metrics soon because I think they would be very useful.

We still capture _most_ of what's going on, e.g. If a user sets the `ProfileCredentialsProvider` we would see that they set a non-default credentials provider, and then we could see where in the profile the credentials are resolved from because every profile option is captured in the metrics.

2024-10-17 14:19 UTC, 0marperez commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/StsWebIdentityCredentialsProvider.kt
> +    private var createdFromEnvironment: Boolean = false
I originally had it in the default credentials provider chain but it wasn't working correctly so I moved it here. The default credentials provider chain doesn't have attributes so I was creating some and then merging them with the ones from the resolve call, but something about that wasn't working correctly. I can try again for a bit and see if I can make it work.

2024-10-17 19:14 UTC, 0marperez commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/BusinessMetricsIntegration.kt
> +                    "op.context.#T(#T.Credentials.CREDENTIALS_CODE)",
`CREDENTIALS_CODE` is now mapped to `StaticCredentialsProvider`

2024-10-31 22:10 UTC, ianbotsf requested changes

2024-10-31 22:10 UTC, ianbotsf commented on aws-runtime/aws-http/api/aws-http.api
**Correctness**: More backward-incompatible changes.

2024-10-31 22:10 UTC, ianbotsf commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/BusinessMetricsIntegration.kt
> +                    "op.context.#T(#T.Credentials.CREDENTIALS_CODE)",
> `CREDENTIALS_CODE` is now mapped to `StaticCredentialsProvider`. It's not in the provider itself because it's an implementation detail for other providers.

I don't think I understand the point being made here. Why can't we move this specialized logic into `StaticCredentialsProvider`? This custom middleware and the symbol references seem way more complex than just tracking the metric in static code the same way we do for all other providers.

2024-10-31 23:02 UTC, 0marperez commented on aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/interceptors/businessmetrics/AwsBusinessMetricsUtils.kt
> +public fun Credentials.emitBusinessMetric(identifier: String): Credentials =
Same comment would go for every other use/variation of `emitBusinessMetric `. It's what we've been using so far.

2024-10-31 23:02 UTC, 0marperez commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/DefaultChainCredentialsProvider.kt
> +        ) {
That was originally what I had, you can see it [here](https://github.com/awslabs/aws-sdk-kotlin/pull/1442/commits/18c80e780be28756376944d12f0b78c0122e9d3f#r1804773271). There's some conversation you can follow

2024-10-31 23:02 UTC, 0marperez commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/BusinessMetricsIntegration.kt
> +                    "op.context.#T(#T.Credentials.CREDENTIALS_CODE)",
The issue is that it's used in the [ProfileCredentialsProvider](https://github.com/awslabs/aws-sdk-kotlin/blob/290c04810ea57d17eb430733b3121bcd55a3472e/aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ProfileCredentialsProvider.kt#L189). When testing I saw the `StaticCredentialsProvider` business metrics being emitted when using `ProfileCredentialsProvider`.

2024-11-04 17:21 UTC, lauzadis commented on aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/interceptors/businessmetrics/AwsBusinessMetricsUtils.kt
> +public fun Credentials.emitBusinessMetric(identifier: String): Credentials =
I agree with Ian, it's a "nit" comment but would improve readability

2024-11-04 17:22 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/DefaultChainCredentialsProvider.kt
> +        ) {
This doesn't really address my initial concern of the business metrics seeming to be hacked into the credentials provider implementation. I agree with Ian, `LazilyInitializedCredentialsProvider` should not have to know about business metrics

2024-11-04 17:38 UTC, lauzadis requested changes
Overall it looks good and getting close to merge. My last concern is around `LazilyInitializedCredentialsProvider` being too closely coupled with business metrics

2024-11-04 17:38 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ProfileCredentialsProvider.kt
> +    private val credentialsBusinessMetrics: MutableSet<BusinessMetric> = mutableSetOf()
correctness: `MutableSet` does not guarantee order of elements

> A generic unordered collection of elements that does not support duplicate elements, and supports adding and removing elements.
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-mutable-set/

2024-11-04 17:38 UTC, lauzadis commented on aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/interceptors/businessmetrics/AwsBusinessMetricsUtils.kt
> +    metrics.forEach { identifier ->
nit: this is no longer an identifier but the metric itself

2024-11-04 17:38 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ProfileCredentialsProvider.kt
> +        return creds.emitBusinessMetrics(credentialsBusinessMetrics)
note: We're calling `emitBusinessMetrics` on a `creds` which might already have business metrics applied, which would result in duplication if you weren't using a `MutableSet` (which you might not want to be, based on my other comment above)

2024-11-04 18:27 UTC, 0marperez commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ProfileCredentialsProvider.kt
> +    private val credentialsBusinessMetrics: MutableSet<BusinessMetric> = mutableSetOf()
It actually does

From `MutableSet`:
> [LinkedHashSet](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-linked-hash-set/index.html)
The implementation of the [MutableSet](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-mutable-set/index.html#kotlin.collections.MutableSet) interface, backed by a [InternalMap](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-mutable-set/#) implementation.

From `LinkedHashSet`:

> The implementation of the [MutableSet](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-mutable-set/index.html#kotlin.collections.MutableSet) interface, backed by a [InternalMap](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-linked-hash-set/#) implementation.

> The insertion order is preserved by the corresponding [InternalMap](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-linked-hash-set/#) implementation.

You can double check we're using `LinkedHashSet` by getting the `::class.simpleName` of the business metrics

2024-11-04 19:07 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ProfileCredentialsProvider.kt
> +    private val credentialsBusinessMetrics: MutableSet<BusinessMetric> = mutableSetOf()
That's the current implementation, but it's not guaranteed and could change in a future version of Kotlin. It's unlikely, and I'm open to keeping this `MutableSet` but just wanted to call it out 🤷

2024-11-04 19:34 UTC, lauzadis approved these changes

2024-11-04 20:05 UTC, merged