feat: support default checksums
aws/aws-sdk-kotlin pull request #1475
Opened 2024-11-27 10:53 UTC by 0marperez

## Issue \#

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-11-27 16:01 UTC, 0marperez commented
Note to reviewers: I'll address the failing CI checks and clean up the PR soon. In the meantime, I’d appreciate a review of the checksum-related changes.

2024-11-27 20:08 UTC, lauzadis commented on tests/codegen/checksums/src/commonTest/kotlin/utils/ChecksumTestUtils.kt
> +package utils
package seems incorrect

2024-11-27 20:08 UTC, lauzadis commented on tests/codegen/checksums/src/commonTest/kotlin/ChecksumResponseTest.kt
Missing package / copyright header. Applies to other test files

2024-11-27 20:08 UTC, lauzadis commented on buildSrc/src/main/kotlin/shared/CodegenTest.kt
> +package shared
Package is incorrect

2024-11-27 20:08 UTC, lauzadis commented on tests/codegen/event-stream/src/commonTest/resources/event-stream-model-template.smithy
> -{op-traits}
How do these `{protocol-name}` and `{op-traits}` templates work now?

2024-12-01 21:45 UTC, 0marperez commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/checksums/ResolveRequestChecksumCalculation.kt
> +                "'$it' is not a valid value for request checksum calculation. Valid values are: ${HttpChecksumConfigOption.entries.toTypedArray()}",
You're right, thanks

2024-12-01 21:45 UTC, 0marperez commented on buildSrc/src/main/kotlin/shared/CodegenTest.kt
This is an abstraction we can use for codegen tests (smoke tests, event streams, checksums, + any new ones we add)

2024-12-01 21:45 UTC, 0marperez commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/flexiblechecksums/FlexibleChecksumsRequest.kt
> +                    RuntimeTypes.Core.BusinessMetrics.SmithyBusinessMetric,
These are two different runtime types, `emitBusinessMetric` & `SmithyBusinessMetric`. What do you mean?

2024-12-01 21:45 UTC, 0marperez commented on services/s3/e2eTest/src/S3ChecksumTest.kt
> +    private val testBucket = "s3-test-bucket-ci-motorcade"
We have to use the hardcoded bucket because it's the only one allowlisted. If we don't we'll get `S3Exception: Checksum Type mismatch occurred, expected checksum Type: null, actual checksum Type: crc32`

2024-12-01 21:45 UTC, 0marperez commented on services/s3/e2eTest/src/S3ChecksumTest.kt
> +    @Order(1)
I had tests set up in a way that required them to run in a certain order before

2024-12-01 21:45 UTC, 0marperez commented on tests/codegen/checksums/src/commonTest/kotlin/utils/ChecksumTestUtils.kt
> +package utils
I noticed that none of the codegen tests were in packages. I put them all in packages, that should fix this

2024-12-01 21:45 UTC, 0marperez commented on tests/codegen/event-stream/src/commonTest/resources/event-stream-model-template.smithy
> -{op-traits}
I turned them off for some reason. I added the templates back, they still work

2024-12-02 16:22 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/flexiblechecksums/FlexibleChecksumsRequest.kt
> +                    RuntimeTypes.Core.BusinessMetrics.SmithyBusinessMetric,
I was meaning your two separate calls to `emitBusinessMetric` but I'm failing to see/remember what style refactor I was trying to suggest. This should be fine as is

2024-12-02 16:23 UTC, lauzadis commented on tests/codegen/checksums/src/commonTest/kotlin/ChecksumResponseTest.kt
Also are we running ktlint on these files? It should have caught the missing copyright header.

2024-12-02 16:24 UTC, lauzadis commented on services/s3/e2eTest/src/S3ChecksumTest.kt
> +    private val testBucket = "s3-test-bucket-ci-motorcade"
Should we add a TODO to move back to a random bucket once the allowlist is no longer necessary?

2024-12-02 22:01 UTC, 0marperez commented on services/s3/e2eTest/src/S3ChecksumTest.kt
> +    private val testBucket = "s3-test-bucket-ci-motorcade"
Yes, good idea

2024-12-02 22:01 UTC, 0marperez commented on tests/codegen/checksums/src/commonTest/kotlin/ChecksumResponseTest.kt
I think ktlint didn't run on these files because they weren't in a package

2024-12-09 19:43 UTC, ianbotsf requested changes

2024-12-09 19:43 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressDisableChecksumInterceptor.kt
> +        logger.warn { "Checksums must not be sent with S3 express upload part operation, removing checksum(s)" }
**Suggestion**: We have a [dedicated `warn` extension method](https://github.com/smithy-lang/smithy-kotlin/blob/394eb3b2f975b111e234da89fd901a250bc6faf2/runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/logging/CoroutineContextLogExt.kt#L147-L156) (and `info`, `debug`, et al.) on `CoroutineContext` itself, which is useful when you only need to log a single message in a given scope:

```kotlin
coroutineContext.warn<S3ExpressDisableChecksumInterceptor> { "Checksums must not be sent with S3 Express UploadPart operation, removing checksum(s)" }
```

2024-12-09 19:43 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressDisableChecksumInterceptor.kt
> +        logger.warn { "Checksums must not be sent with S3 express upload part operation, removing checksum(s)" }
**Nit**: Use proper feature name (S3 Express) and operation name (UploadPart) in message:

```kotlin
"Checksums must not be sent with S3 Express UploadPart operation, removing checksum(s)"
```

2024-12-09 19:43 UTC, ianbotsf commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressDisableChecksumInterceptor.kt
> +    }
**Correctness**: Use `ignoreCase = true`. Applies to `removeChecksumTrailingHeaders` and `removeChecksumTrailingHeadersFromXAmzTrailer` methods too.

2024-12-09 19:43 UTC, ianbotsf commented on services/s3/common/test/aws/sdk/kotlin/services/s3/express/ChecksumRemovalTest.kt
> +class ChecksumRemovalTest {
**Nit**: Add tests for varying capitalizations of header names.

2024-12-09 19:43 UTC, ianbotsf commented on services/s3/e2eTest/src/PaginatorTest.kt
>      fun testListPartsPagination() = runBlocking {
**Question**: Do we _have_ to disable this test? Can't we just adjust the assertion to simplify verify the parts have the correct `partNumber`/`eTag` and ignore the checksum algorithm?

2024-12-09 19:43 UTC, ianbotsf commented on services/s3/e2eTest/src/S3ChecksumTest.kt
> +    }
**Correctness**: We should be asserting something in these tests. Please verify the operation invocations had the desired effects by calling `GetObject` or similar and inspecting the resulting body and checksum.

2024-12-09 19:43 UTC, ianbotsf commented on services/s3/e2eTest/src/S3ChecksumTest.kt
> +        ) {}
**Correctness**: We should be fetching the object body and asserting something here.

2024-12-09 19:43 UTC, ianbotsf commented on services/s3/e2eTest/src/S3TestUtils.kt
> +            ?.mapNotNull { it.name }
**Correctness**: This call does not paginate and may fail to find the desired bucket name if it's not in the first page of results. Fortunately, reading through the entire paginated list is not required. The `HeadBucket` operation provides all we need:

```kotlin
client
    .headBucket {
        this.bucket = bucket
        expectedBucketOwner = accountId
    }
    ?.takeIf { it.bucketRegion == region }
    ?: run {
        println("Creating S3 bucket: $bucket")

        client.createBucket {
            this.bucket = bucket
            createBucketConfiguration {
                locationConstraint = BucketLocationConstraint.fromValue(region ?: client.config.region!!)
            }
        }

        client.waitUntilBucketExists { this.bucket = bucket }
    }
```

2024-12-09 19:43 UTC, ianbotsf commented on services/s3/e2eTest/src/S3TestUtils.kt
> +        }
**Question**: This verifies an existing bucket is in the expected region but, if that isn't true, the following logic would attempt to _create_ a bucket with the same name in a different region. Won't this fail? What should we do in this case?

2024-12-09 19:43 UTC, ianbotsf commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    }
**Question**: How many multipart uploads do we expect to delete? Should we launching/joining these?

2024-12-09 19:43 UTC, ianbotsf commented on tests/codegen/build.gradle.kts
> +    )
**Question**: Why do we need to opt into `RequiresOptIn`?

2024-12-09 19:43 UTC, ianbotsf commented on tests/codegen/checksums/src/commonTest/kotlin/aws/sdk/kotlin/tests/codegen/checksums/utils/ChecksumTestUtils.kt
> +    }
**Correctness**: Initializing `containsExpectedBusinessMetrics` to `true` will result in a false positive if the interceptor never runs.

2024-12-11 15:45 UTC, 0marperez commented on services/s3/e2eTest/src/PaginatorTest.kt
>      fun testListPartsPagination() = runBlocking {
I don't think so, this test fails because we're getting an exception from S3 for sending a request with a checksum. We're not failing the assertion.

2024-12-11 15:49 UTC, 0marperez commented on services/s3/e2eTest/src/S3TestUtils.kt
> +    }
Currently just one per bucket, I don't think we need to be launching/joining these yet.

2024-12-11 15:53 UTC, 0marperez commented on tests/codegen/build.gradle.kts
> +    )
I refactored a lot of things here and I don't remember. I think it's because of [this](https://github.com/awslabs/aws-sdk-kotlin/blob/fb94044e163e77cd973edb382b00f40721f54da0/aws-runtime/build.gradle.kts#L59-L61). I'll try removing it to see if anything breaks

2024-12-11 19:38 UTC, 0marperez commented on services/s3/e2eTest/src/S3TestUtils.kt
> +        }
I think we can throw our own exception explaining the problem

2024-12-11 19:38 UTC, 0marperez commented on services/s3/e2eTest/src/S3TestUtils.kt
> +            ?.mapNotNull { it.name }
I like this solution but I think it won't work when the bucket doesn't exist. From the s3:headBucket docs:
>If the bucket does not exist or you do not have permission to access it, the HEAD request returns a generic 400 Bad Request, 403 Forbidden or 404 Not Found code. A message body is not included, so you cannot determine the exception beyond these HTTP response codes.

2024-12-11 21:48 UTC, 0marperez commented on tests/codegen/build.gradle.kts
> +    )
We don't actually need it, I removed it

2024-12-11 22:06 UTC, ianbotsf commented on services/s3/e2eTest/src/S3TestUtils.kt
> +            ?.mapNotNull { it.name }
Ah too bad. Well we should still use `HeadBucket` (perhaps wrapped in a helper method) or some other operation that gets us the bucket info in *O*(1) time instead of iterating through them when we already have the name.

2024-12-13 15:43 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/express/S3ExpressIntegration.kt
> -    private val useCrc32Checksum = object : ProtocolMiddleware {
question/correctness: S3 Express' spec says CRC32 is **required**. If we change our SDK's default algorithm to CRC64NVME in the future, how will we ensure CRC32 is still used for S3 Express? That's what this integration was responsible for.

Does S3 Express support CRC64NVME?

2024-12-13 15:43 UTC, lauzadis commented on aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/interceptors/S3CompositeChecksumsInterceptor.kt
> +            logger.warn { "S3 returned a composite checksum, composite checksums are not supported, removing checksum" }
info: Log the composite checksum header name

2024-12-13 15:43 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/flexiblechecksums/s3/S3CompositeChecksumsIntegration.kt
> + * Composite checksums are used for multipart uploads and end with "-#" where "#" is a number.
correctness/breaking change: I don't think we should be removing these headers, what if users need them for other purposes?

Isn't it easier to just ignore composite checksums in the flexible checksums implementation?

2024-12-13 15:43 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressDisableChecksumInterceptor.kt
> + * Disables checksums for s3:UploadPart requests that use S3 express.
nit: S3 Express

2024-12-13 15:43 UTC, lauzadis commented on tests/codegen/event-stream/src/commonTest/resources/event-stream-model-template.smithy
> -{op-traits}
> I added the templates back

I still don't see them

2024-12-13 15:43 UTC, lauzadis commented on buildSrc/build.gradle.kts
Does this need to exist? [buildSrc is treated as an included build](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:build_sources) which means every subproject will have these config options applied.

It seems odd to need this just for codegen tests

2024-12-13 15:43 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/PresignerGenerator.kt
> +                withBlock("input.#L?.value?.let { checksumAlgorithmString ->", "}", checksumAlgorithmMember) {
nit/naming/style: avoid Hungarian notation, `checksumAlgorithmName`

2024-12-13 15:43 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/PresignerGenerator.kt
> +                                        "The requested checksum algorithm is not supported for pre-signed URL checksums, sending request without checksum.",
We should include which checksum algorithm the user chose and which are supported

2024-12-13 15:43 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/PresignerGenerator.kt
> +     * Gets the checksum algorithm member if a user can configure request checksums otherwise null
> if a user can configure request checksums

style/docs: This seems awkward to me

"Gets the checksum algorithm member if configured on a request, otherwise null"

2024-12-13 15:43 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/flexiblechecksums/FlexibleChecksumsRequest.kt
> +    private val configBusinessMetrics = object : ProtocolMiddleware {
nit: middleware name and value's name should match

2024-12-13 17:28 UTC, 0marperez commented on buildSrc/build.gradle.kts
It's the best way I could find to share a data class between subprojects, do you know of alternatives that would work better? I might've missed them

2024-12-13 18:12 UTC, lauzadis commented on buildSrc/build.gradle.kts
You can make a new project that both of those subprojects depend on

2024-12-19 15:16 UTC, 0marperez commented on buildSrc/build.gradle.kts
This is still a work in progress, I don't want to block the review because of this. I think worst case scenario we can come back and refactor this without it being a breaking change

2024-12-19 19:42 UTC, lauzadis requested changes

2024-12-19 19:42 UTC, lauzadis commented on aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/interceptors/S3FlexibleChecksumResponseInterceptor.kt
> + * S3 variant of the flexible checksum interceptor where composite checksums are not validated
nit/docs: `... of the [FlexibleChecksumsResponseInterceptor]...`

2024-12-19 19:42 UTC, lauzadis commented on aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/interceptors/S3FlexibleChecksumResponseInterceptor.kt
correctness: This file should go in `services/s3/common/src/aws/sdk/kotlin/services/s3/internal` with all the other S3-specific interceptors

2024-12-19 19:42 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/flexiblechecksums/FlexibleChecksumsRequest.kt
> +private fun requestChecksumsConfigured(ctx: ProtocolGenerator.GenerationContext, op: OperationShape): Boolean {
naming: "configured" implies that this is dependent on user behavior, but it's just based on the model. I suggest making this an extension function `OperationShape.hasRequestAlgorithmMember(...)`

2024-12-19 19:42 UTC, lauzadis commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/flexiblechecksums/FlexibleChecksumsResponse.kt
> +        }
docs: let's add a comment here about why S3 needs a custom interceptor

2024-12-19 19:42 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressDefaultChecksumAlgorithm.kt
> +    executionContext.getOrNull(AttributeKey(S3_EXPRESS_ENDPOINT_PROPERTY_KEY)) != S3_EXPRESS_ENDPOINT_PROPERTY_VALUE
style: Could be an extension function off `ExecutionContext`

2024-12-19 19:42 UTC, lauzadis commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressDefaultChecksumAlgorithm.kt
> +) : HttpInterceptor {
style: This works but I think the previous implementation using two different interceptors was cleaner. It's not clear to me why this had to deviate so much from what we already had

2024-12-19 19:42 UTC, lauzadis commented on .github/workflows/continuous-integration.yml
> +          path: '**/build/reports'
What are these test reports used for?

2024-12-19 19:55 UTC, 0marperez commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressDefaultChecksumAlgorithm.kt
> +) : HttpInterceptor {
Because `FlexibleChecksumsResponseInterceptor` is in smithy kotlin, which shouldn't know anything SDK related

2024-12-19 19:55 UTC, 0marperez commented on services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressDefaultChecksumAlgorithm.kt
> +) : HttpInterceptor {
This was one of the suggestion we discussed during standup

2024-12-20 17:39 UTC, 0marperez commented on codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/flexiblechecksums/FlexibleChecksumsResponse.kt
> +        }
Now that I look at this again, we could replace `S3FlexibleChecksumResponseInterceptor` with something more generic that could be applied to other services. In case other services start sending composite checksums in the future. What does the team think?

2024-12-24 14:54 UTC, 0marperez commented on tests/codegen/event-stream/src/commonTest/resources/event-stream-model-template.smithy
> -{op-traits}
I was having trouble "resetting" the model back to the original with templates. I was taking a closer look and realized that the templates weren't even required so I removed them

2025-01-09 16:52 UTC, lauzadis commented on buildSrc/build.gradle.kts
I'm still a little concerned about this new `buildSrc` and the fact that it's treated as an include-build by every module. This means every module will have the Kotlin JVM plugin applied to it which shouldn't be necessary everywhere.

https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:build_sources

Can we accomplish the same thing without using buildSrc?

2025-01-09 16:52 UTC, lauzadis commented on services/s3/e2eTest/src/PaginatorTest.kt
> +    @Ignore
When can this test be enabled? Is it still broken?

2025-01-09 17:24 UTC, 0marperez commented on services/s3/e2eTest/src/PaginatorTest.kt
> +    @Ignore
Still broken, left a comment about why on slack

2025-01-09 20:23 UTC, 0marperez commented on buildSrc/build.gradle.kts
Discussed offline and we're keeping `buildSrc` for now

2025-01-09 22:09 UTC, 0marperez commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AwsSdkSetting.kt
> +        strEnvSetting("aws.responseChecksumValidation", "AWS_RESPONSE_CHECKSUM_VALIDATION")
Well that's handy. I guess I forgot/couldn't find this type. Let's start using it

2025-01-13 22:11 UTC, ianbotsf approved these changes

2025-01-13 22:11 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt
> +
**Suggestion**: Oh, gross. I thought we had enum parsing support built for profiles but I guess not. This appears to work but relies on hardcoded name strings and wouldn't catch any new values we add to the enum. A safer way to parse would be what we do for [`retryMode`](https://github.com/awslabs/aws-sdk-kotlin/blob/757925d99d6703914ba5e33dd472e6602ee27345/aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt#L79-L91) or [`accountIdEndpointMode`](https://github.com/awslabs/aws-sdk-kotlin/blob/757925d99d6703914ba5e33dd472e6602ee27345/aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt#L135-L147): iterate through the entries and pick the first matching name.

Even better would be making a generic `getEnumOrNull` function to support parsing to any enum type and then we could clean this up along with  `retryMode` and `accountIdEndpointMode`. Up to you.

2025-01-14 18:45 UTC, 0marperez commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt
> +
I think `getEnumOrNull` is the right thing to do here. I can try to get this done before we have to merge the feature. Since it's not a breaking change, if I can't finish it now I'll just create a task to do it later

2025-01-15 19:59 UTC, merged