fix: utilize endpoint ports
aws/aws-sdk-kotlin pull request #311
Opened 2021-09-02 18:44 UTC by ianbotsf

## Issue \#

Closes #310 

## Description of changes

Currently, neither the presigning logic nor the service endpoint resolver correctly utilize endpoint ports. This is most readily apparent when using the `StaticEndpointResolver` or a test mock, but may also have negative implications for generated endpoint resolvers in the future.

## Scope

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-02 20:45 UTC, kggilmer approved these changes
LGTM

2021-09-03 13:07 UTC, aajtodd requested changes
These changes look ok but I think we're missing part of the puzzle.

We need to ensure each HTTP client engine respects the port as well.

Glancing at the [CrtHttpClientEngine](https://github.com/awslabs/aws-sdk-kotlin/blob/9dcd33450ff654a07d2d21011b7edc68704b85a7/aws-runtime/http-client-engine-crt/common/src/aws/sdk/kotlin/runtime/http/engine/crt/CrtHttpEngine.kt#L85) it looks like we still wouldn't do the right thing because we would be caching client managers by only the hostname (as an aside probably should have named that property `hostname` rather than `host` which usually implies "hostname:port"). 

It [looks like](https://github.com/awslabs/smithy-kotlin/blob/5b4b37e98b55e5aab63df70517a6626b52ff79fe/runtime/protocol/http-client-engines/http-client-engine-ktor/jvm/src/aws/smithy/kotlin/runtime/http/engine/ktor/KtorUtils.kt#L33) the KTOR based engine we started with would be ok.


I found a semi related issue with how we handle ports in the [AsyncStressTest](https://github.com/awslabs/aws-sdk-kotlin/blob/78a671cb72d9ec59c5fce1e430c52c5227b0a75e/aws-runtime/http-client-engine-crt/jvm/test/aws/sdk/kotlin/runtime/http/engine/crt/AsyncStressTest.kt#L50) and [TestWithLocalServer](https://github.com/awslabs/aws-sdk-kotlin/blob/78a671cb72d9ec59c5fce1e430c52c5227b0a75e/aws-runtime/http-client-engine-crt/jvm/test/aws/sdk/kotlin/runtime/http/engine/crt/TestWithLocalServer.kt#L17) work. The host is set as `hostname:port` which only works because of how it gets passed into crt-java later [here](https://github.com/awslabs/aws-crt-kotlin/blob/8daf1da6d8fc122105bb03c35517239541b8aa70/src/jvm/src/aws/sdk/kotlin/crt/http/HttpClientConnectionManagerJVM.kt#L56).

2021-09-03 16:56 UTC, ianbotsf commented
> We need to ensure each HTTP client engine respects the port as well.

You're right, didn't go deep enough.

> as an aside probably should have named that property `hostname` rather than `host` which usually implies "hostname:port").

RFC 3986 names the combination of **userinfo**, **host**, and **port** as the [**authority**](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2) of the URI. Logically, is that the right scope for caching connection managers? Or is **userinfo** irrelevant?

2021-09-03 17:06 UTC, aajtodd commented
> RFC 3986 names the combination of **userinfo**, **host**, and **port** as the [**authority**](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2) of the URI. Logically, is that the right scope for caching connection managers? Or is **userinfo** irrelevant?

Userinfo for an AWS SDK is _likely_ always going to be irrelevant but that is probably as good as anything to cache on.

2021-09-07 13:25 UTC, aajtodd approved these changes

2021-09-07 20:20 UTC, merged