Profile Auth Support JVM system property and Environment Variables #297
aws/aws-sdk-kotlin pull request #312
Opened 2021-09-06 03:08 UTC by kmbotts

Added support for the Profile Credentials Provider to check for JVM System property and Environment Variable for the profileName should it not be provided in the constructor. The code and usage was leveraged from the aws-java-sdk v1 file AwsProfileNameLoader with the added change of giving the JVM system property higher priority over Environment variable in determining the profile name, however that can be changed if it's undesirable.

Included are unit tests for the various combinations of configuring the Profile provider, with a refactor of the unit test to create the test credentials file statically in a BeforeAll and delete the file in AfterAll step for unit test readability. Required an addition of a new dependency in the text project so that I was able to "mock" the environment variable during the creation of the provider to keep unit test machine agnostic.

## Issue \#

https://github.com/awslabs/aws-sdk-kotlin/issues/297

## Description of changes

This was added for parity with other AWS SDKs as outlined in the issue.

## Scope

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-07 14:02 UTC, aajtodd requested changes
Thanks for the PR! Overall the changes look good, just a few housekeeping things to address.

2021-09-07 14:02 UTC, aajtodd commented on .gitignore
> +.kotlintest/
fix

update to [kotest](https://github.com/kotest/kotest/blob/master/.gitignore#L36)

2021-09-07 23:26 UTC, kmbotts commented on aws-runtime/auth/build.gradle.kts
> +                implementation("io.kotlintest:kotlintest-runner-junit5:3.4.2")
this worked

2021-09-07 23:27 UTC, kmbotts commented on aws-runtime/auth/jvm/src/aws/sdk/kotlin/runtime/auth/ProfileCredentialsProviderJvm.kt
> +private const val DEFAULT_PROFILE_NAME: String = "default"
worked. was able to return null after I figured out the "String?" syntax for the loadProfileName method

2021-09-07 23:27 UTC, kmbotts commented on aws-runtime/auth/jvm/src/aws/sdk/kotlin/runtime/auth/ProfileCredentialsProviderJvm.kt
> +public const val AWS_PROFILE_SYSTEM_PROPERTY: String = "aws.profile"
done

2021-09-07 23:28 UTC, kmbotts commented on .gitignore
> +.kotlintest/
done

2021-09-08 13:28 UTC, aajtodd approved these changes
One suggestion but otherwise looks good.

2021-09-08 13:28 UTC, aajtodd commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/AwsSdkSetting.kt
> +     *  Configure the AWS profile
style/docs

```
The name of the default profile that should be loaded from config
```

Also this could probably be defaulted to `default`, we don't yet take advantage of the defaults but we will when we implement #300 

e.g.

```kotlin
AwsSdkSetting<String>("AWS_PROFILE", "aws.profile", "default")
```

2021-09-09 18:31 UTC, kmbotts commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/AwsSdkSetting.kt
> +     *  Configure the AWS profile
you want me to add the "default" field while I'm at it? Or just stick to the doc update?

2021-09-09 18:47 UTC, aajtodd commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/AwsSdkSetting.kt
> +     *  Configure the AWS profile
Go ahead and add it

2021-09-09 22:35 UTC, kmbotts commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/AwsSdkSetting.kt
> +     *  Configure the AWS profile
Done

2021-09-10 15:33 UTC, aajtodd commented
@kmbotts Everything looks good, the `ktlint` check didn't run though. It looks like we are missing a trigger for pull requests in the [lint workflow](https://github.com/awslabs/aws-sdk-kotlin/blob/main/.github/workflows/lint.yml#L3)

e.g.
```
  pull_request:
    branches: [ main ]
```

Which is why all the other checks ran because the CI workflow has [it](https://github.com/awslabs/aws-sdk-kotlin/blob/main/.github/workflows/continuous-integration.yml#L6). 

I'll give you a few options since I don't want to have to keep requesting changes, let me know what works best for you:
* I can submit a PR and get it updated on `main` and you can refresh this branch 
* You can go update the lint workflow with the additional trigger on your branch and it should (hopefully) then run
* You can manually verify that `./gradlew ktlint` runs without issues (if it doesn't `./gradlew ktlintFormat` will usually fix everything automatically) and let me know by commenting in the PR. Then I'll merge this PR and get it updated in `main` out of band.

2021-09-10 17:04 UTC, kmbotts commented
I don't mind giving it a try later tonight. More opportunity to learn :)

2021-09-11 11:35 UTC, kmbotts commented
I added the trigger you suggested and successfully ran ktlintFormat and ktlint locally.

2021-09-13 13:43 UTC, merged