AWS configuration loader and parser
aws/aws-sdk-kotlin pull request #315
Opened 2021-09-09 00:42 UTC by kggilmer

## Issue \# 
https://github.com/awslabs/aws-sdk-kotlin/issues/216

## Description of changes
Provide an implementation for AWS configuration file loading and parsing.  Loading entails evaulating various environment, system properties, and files on the local filesystem.  Parsing entails converting 0 or more files into a property map that defines the selected profile.

A few notes as to some of the complexity:
* The spec defines specific behavior for a subset parsing errors that should be silently ignored.  Due to this a simple parser abstraction that is pass/exception does not fit well.
* Due to the complexities of merging continuations, parsing is broken into two phases: merging continuations and then parsing properties and assigning them into profiles.
* The test suites originally started in Java, Rust added more, and then I added one additional.  The rust team is working on a PR to push all new tests back into the spec.
* Due to the possibly sensitive nature of the contents of these configuration files, where possible I prevent printing the contents of the file in errors or logs.  This may not be the best option as it makes it more difficult to root-cause parse errors.  We may need to revisit this if others think it's more important to have clear error messages with the possibility of printing secrets in errors or logs.

A few notes on implementation:
* Because `Platform` is an object, I could not find a way of testing dependent code without introducing the mocking/stubbing library `mockk`.
* I opted to paste a relatively large JSON document as a string into a common test case rather than make the unit tests be JVM to get resource loading

## Scope

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-09 00:47 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoader.kt
> +internal fun loadAwsConfiguration(): AwsConfiguration {
I should make it more obvious in API comments but this is the entry-point into everything in this PR.

2021-09-09 18:27 UTC, ianbotsf requested changes

2021-09-09 18:27 UTC, ianbotsf commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoaderTest.kt
> +                println("*** TEST $index: ${testCase.name}")
**Nit**: Remove `println` statement.

2021-09-09 18:27 UTC, ianbotsf commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoaderTest.kt
> +            // .filter { testCase -> testCase.name == "User home is loaded from HOME with highest priority on windows platforms." }
**Nit**: Remove commented code.

2021-09-09 18:27 UTC, ianbotsf commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoaderTest.kt
> +
**Style**: This is probably better as a JSON file resource than inline content in a KT file.

2021-09-09 18:27 UTC, ianbotsf commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigParserTest.kt
> +            .filter { testCase -> testCase.name == "Property definitions must contain an equals sign." }
**Question**: Doesn't this filter out all but one test?

2021-09-09 18:27 UTC, ianbotsf commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigParserTest.kt
> +                println("*** TEST $index: $testCase")
**Nit**: Remove `println` statement.

2021-09-09 18:27 UTC, ianbotsf commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigParserTest.kt
> +    }
**Question**: Why is this interface necessary?

2021-09-09 18:27 UTC, ianbotsf commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigParserTest.kt
> +        data class MatchConfigAndCredentialOutputCase(override val name: String, val configInput: String, val credentialInput: String, val expectedOutput: String) :
**Style**: Excessive line length. Did `ktlint` not catch this?

2021-09-09 18:27 UTC, ianbotsf commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigParserTest.kt
> +  ],
**Style**: This is probably better as a JSON file resource than inline content in a KT file.

2021-09-09 18:27 UTC, ianbotsf commented
**Comment**: In general this code doesn't do enough logging. The specification states that error logic should occur in a number of different circumstances.

Furthermore, given the complexity of resolving configuration, I believe there will situations where users _want_ to debug the values which were loaded. I believe that, similar to our opt-in request/response logging, we should have opt-in configuration debug logging that includes a higher level of verbosity and might give away secrets.

2021-09-09 18:28 UTC, ianbotsf commented
**Comment**: In general, this code is highly-coupled and doesn't offer a lot of places for injection or sub-unit testing. `Platform` itself is an object (which is bad for testing) but we continue the pattern by operating out of top-level functions which take few dependencies that would allow us to test sub-portions or bypass parsing for other SDK-startup use cases. Could this code be written in a DI-friendlier manner?

2021-09-09 18:28 UTC, ianbotsf commented
**Question**: How are subproperties represented in this code? I see all the structures we're passing around are `Map<String, Map<String, String>>` but that doesn't seem to account for subproperties.

2021-09-09 18:28 UTC, ianbotsf commented
**Question**: Given the complexity of the specification and the implementation, it's hard for me to know whether it performs correctly in all cases or not. Do you have confidence that the included tests address all the possible corner cases mentioned in the spec?

2021-09-09 19:58 UTC, aajtodd commented
I haven't gotten into the details (will tomorrow hopefully) but general question is why is `AwsConfigFileParser`, `AwsConfigLoader`, etc in the `auth` project?

2021-09-10 00:17 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoader.kt
> +    )
Good catch, this was a hold over from previous stuff.  Fixed in next push.

2021-09-10 00:25 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoader.kt
> +}
The spec specifies default values for each configuration file type as having the `~` prefix without predication on OS type.  This implementation reflects my interpretation of the spec.  LMK if you see something that indicates otherwise.  Essentially from my understanding, the prefix `~` character to a path is the signal used to determine that the home directory should be found and prefixed to the path, regardless of validity of that character as it would apply to a specific filesystem implementation.

> In Windows, ~ is a valid file/directory name that could exist anywhere in the filesystem. 

Note this function does not mutate the incoming path except in the case that `~` is the first non-whitespace character.

2021-09-10 00:27 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoader.kt
> +    }
I disagree.  This logic is defined in and particular to the spec of AWS configuration file loading.  The platform type is the source of information specific to a platform itself and nothing else, (IMO).

2021-09-10 00:28 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoader.kt
> +}
Same as above.  Personally I find the specified behavior a little wonky in general and would not want it to escape out of the aws configuration file loading.

2021-09-10 00:34 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigParser.kt
> +    const val NEW_LINE: Char = '\n'
There are specific test cases for windows in the test suite, and the spec itself (making no qualifications for OS) specifies that continuation lines (for example) begin with a `\n` character.   My believe that the implementation is correct is based purely on the fact that the test cases pass, however it certainly should be tested that this actually works on a Windows host.  I will do that.

2021-09-10 00:42 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigParser.kt
> +private val credentialFunctions: List<ParseFn> = listOf(::credentialProfile, ::property, ::unmatchedLine)
Yeah, that may be better.  I considered this but opted to leave as is, due to a vague uneasiness with associating functions (logic) to enums.  To me state attached to enums should be static (things easily serializable) but nothing concrete comes to mind as to justification for this design bias.  I'll make the change.

2021-09-10 00:52 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigParser.kt
> +                        }
In this case the contract cannot be applied unfortunately because `lastProfile` is mutable.

2021-09-10 00:53 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigParser.kt
> +    const val INLINE_COMMENT_2 = " $COMMENT_2"
for performance reasons?  As a personal choice, I opted to use stdlib functions for string manipulation and parsing over regex because I find the former easier to read.

2021-09-10 00:54 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigParser.kt
> +    const val PROFILE_POSTFIX = ']'
It also is the same number of characters which pretty much seals the deal for me.

2021-09-10 00:56 UTC, kggilmer commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoaderTest.kt
> +                println("*** TEST $index: ${testCase.name}")
removed all printlns from unit tests, thanks.

2021-09-10 00:57 UTC, kggilmer commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoaderTest.kt
> +            // .filter { testCase -> testCase.name == "User home is loaded from HOME with highest priority on windows platforms." }
I intentionally left this here as a hint to my future self about how I can run just one test for troubleshooting.  This may come in to play if/when more test cases are added to the spec.  It's a minor thing and if you feel strongly I'll remove it or make it a comment.

2021-09-10 01:00 UTC, kggilmer commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoaderTest.kt
> +
I had started out that way but after thinking about it, IMO the attribute that I can, at a glance, know that a given test (or any source file) is common and lacks any specific JVM stuff outweighs the resource loading convenience.  Put another way, once a given source file is in a JVM source set, there is no compiler enforcement of platform code.

It's not a hill I want to die on though so can refactor if you feel strongly.

2021-09-10 01:02 UTC, kggilmer commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoaderTest.kt
> +
If there is some pure kotlin way of loading a resource file cleanly, I'm all :ear:

2021-09-10 01:02 UTC, kggilmer commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigParserTest.kt
> +            .filter { testCase -> testCase.name == "Property definitions must contain an equals sign." }
Whoops, forgot to comment this out before pushing.  It was a nervous moment to run the whole test suite but happily they all still pass since whenever I was working on this particular test.

2021-09-10 01:04 UTC, kggilmer commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigParserTest.kt
> +    }
It's a hold-over from previous version of this test.  Removed.

2021-09-10 01:06 UTC, kggilmer commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigParserTest.kt
> +        data class MatchConfigAndCredentialOutputCase(override val name: String, val configInput: String, val credentialInput: String, val expectedOutput: String) :
It did not.  Expanded parameter list to shorten the lines.

2021-09-10 01:06 UTC, kggilmer commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigParserTest.kt
> +  ],
See above about the resource vs common tradeoff.

2021-09-10 01:38 UTC, kggilmer commented
> Comment: In general this code doesn't do enough logging. The specification states that error logic should occur in a number of different circumstances.

I need to take another pass on logging.  Added TODO item.

> Comment: In general, this code is highly-coupled and doesn't offer a lot of places for injection or sub-unit testing. Platform itself is an object (which is bad for testing) but we continue the pattern by operating out of top-level functions which take few dependencies that would allow us to test sub-portions or bypass parsing for other SDK-startup use cases. Could this code be written in a DI-friendlier manner?

Regarding coupling...I mean it's functions all the way down.  If you look at the imports all it's using from the SDK is `Platform` and `BaseSdkException`.  Getting access to an AWS configuration is broken into three parts.  The functions to each are isolated in each file.  I'm not sure if I understand the problem.  Is it that you'd like to share some of this logic elsewhere in the SDK and find the way it's written to not support that?  Something else?

Regarding DI-friendly...the top level function is not DI friendly, it's true.  This in part comes from the nature of the spec, in that a single entry point should "do everything" to resolve, load, and parse files in order to produce a map of properties.  In fact I don't even test the top level function (I can't test it) because it uses `Platform` directly which will vary based on host.  I can update the function signature to allow for overridding of types to make it more DI friendly.  Is there places elsewhere that you find to be unfriendly to DI?

> Question: How are subproperties represented in this code? I see all the structures we're passing around are Map<String, Map<String, String>> but that doesn't seem to account for subproperties.

It seems weird to me but as I understand it subproperties are treated as literals by the configuration parser.  It seems that clients would need to do further parsing of subproperties to extract key/value pairs.  This is how the spec reads to me as well as the java implementation ([ex](https://code.amazon.com/packages/AwsSdkSepConfigurationFiles/blobs/b1d9ce8b89a3ca5077eba93649edeb19eb05d53e/--/src/software/amazon/awssdk/seps/profile/ProfileFileParser.java#L26)).  If you see something that differs from my interpretation, please LMK!

> Question: Given the complexity of the specification and the implementation, it's hard for me to know whether it performs correctly in all cases or not. Do you have confidence that the included tests address all the possible corner cases mentioned in the spec?

Here's the million dollar question :smile:   The test cases for the parser cover a lot of edge cases.  The loader test cases not as much but also the complexity is less there.  Before I'm confident I need to run tests on an actual windows host.  But generally, I rest on on the test suites.

> I haven't gotten into the details (will tomorrow hopefully) but general question is why is AwsConfigFileParser, AwsConfigLoader, etc in the auth project?

Just seemed like the most obvious place to put it when I started but I agree it probably needs it's own module since it's purpose is not purely for credential access.   Is there something better as a module than `aws-runtime/aws-config`?

2021-09-10 17:25 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoader.kt
> +}
Oh, there also this test case:

```json
{
      "name": "Windows style line endings are supported.",
      "input": {
        "configFile": "[profile foo]\r\nname = value"
      },
      "output": {
        "profiles": {
          "foo": {
            "name": "value"
          }
        }
      }
    }
```

2021-09-11 01:03 UTC, kggilmer commented
I've added most of the _shoulds_ from the spec regarding what to log including line numbers.  @aajtodd you're welcome to take a pass when you have time.

2021-09-13 12:59 UTC, rcoh commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigParserTest.kt
> +                println("*** TEST $index: $testCase")
I have this specific print in Rust, it's actually pretty handy.

2021-09-13 13:59 UTC, aajtodd commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoader.kt
> +    }
If it's specific to the spec (which it would seem to be) then I agree with Ken here.

2021-09-13 14:01 UTC, aajtodd commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigParser.kt
> +                        }
It can be applied if you assign it to a local variable:

```kt
val last = checkNotNull(lastProfile)
```

Not sure that's really much better but as an FYI

2021-09-13 14:04 UTC, aajtodd commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoaderTest.kt
> +
I don't know of one off hand. I see the value in what you're saying (keeping it such that the tests can stay in `common`). At the very least perhaps annotate with a language comment which will trigger the IDE to parse it as JSON (and highlight it). 

e.g.

```kt
// language=JSON
private val testSuiteJson = """
"""
```

2021-09-13 14:08 UTC, aajtodd commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigParserTest.kt
> +                println("*** TEST $index: $testCase")
The way I usually structure these is to override the assert message like [this](https://github.com/awslabs/aws-sdk-kotlin/blob/da361753ddb18d40c3e6eac135a598248a469677/aws-runtime/aws-core/common/test/aws/sdk/kotlin/runtime/endpoint/internal/EndpointsTest.kt#L143)

e.g.
```
assertEquals(..., "[idx=$index]: $testCase blah blah")
```

2021-09-13 15:28 UTC, aajtodd reviewed
Impressive work. Few questions and some minor feedback/suggestions.

2021-09-13 15:28 UTC, aajtodd commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigParser.kt
> +    const val NEW_LINE: Char = '\n'
Ian called this out but does this work on Windows correctly?

2021-09-13 15:54 UTC, ianbotsf commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoader.kt
> +}
Hmm, that is unexpected to me as a Windows user but you appear to be correct about what the spec says. We can leave this as is.

2021-09-13 16:02 UTC, ianbotsf commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoader.kt
> +    }
The spec seems to merely enumerate OS-standard ways of finding the home directory plus an additional JVM-specific one. If you wanted to write a specification-independent method for finding a user's home directory, how would it differ from this method?

I don't care that strongly about this so we can leave it if need be but I am curious.

2021-09-13 16:03 UTC, ianbotsf commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoader.kt
> +}
Given what I now know about the specification's treatment of **~** on Windows, I agree with you.

2021-09-13 16:05 UTC, ianbotsf commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigParser.kt
> +                        }
Oh right, then nevermind.

2021-09-13 16:09 UTC, ianbotsf commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigParser.kt
> +    const val INLINE_COMMENT_2 = " $COMMENT_2"
I was arguing from a standpoint of legibility. I find code cleaner when written as `if (someBigCondition)` rather than `if (condition1 || condition2)`, especially if those multiple conditions are repeated in multiple places. If you find the current code more legible then it would seem we're at an impasse and thus I'll defer to the existing code.

2021-09-13 16:12 UTC, ianbotsf commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoaderTest.kt
> +
If we have no platform-independent way to load test resources then this is fine.

2021-09-13 16:27 UTC, ianbotsf commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigLoader.kt
> +public fun loadAwsConfiguration(platform: Platform = Platform): AwsConfiguration {
> If `Platform` is an `object` why do we even need to take it as a parameter?

Accepting it as a parameter should allow for injecting a mocked version of the object. Overall, I agree that `Platform` should be a class or an interface but refactoring that is probably outside the scope of this PR.

2021-09-13 16:39 UTC, ianbotsf commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigLoader.kt
> +public fun loadAwsConfiguration(platform: Platform = Platform): AwsConfiguration {
**Question**: Where/how will `loadAwsConfiguration` be called at runtime? How should tests of that call location stub out configuration loading irrelevant to their own logic?

2021-09-16 00:54 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoader.kt
> +    }
>  If you wanted to write a specification-independent method for finding a user's home directory, how would it differ from this method?

It's a fair point but IMO this AWS config parser is written specifically to emulate the behavior of an external entity, and as such does not act in ways idiomatic to our platform.  I think it's safer to isolate this code to it's function rather than try and make it general purpose, at least right now.  If we do get a future case in which we need to manually resolve `~` to $HOME then we should look to see if there are wins to share implementation.

2021-09-16 00:55 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/config/AwsConfigParser.kt
> +    const val NEW_LINE: Char = '\n'
Verified tests and manual test work as expected on an actual host.

2021-09-16 00:59 UTC, kggilmer commented on aws-runtime/auth/common/test/aws/sdk/kotlin/runtime/auth/config/AwsConfigLoaderTest.kt
> +
TIL: `// language=JSON`.  Thanks!

2021-09-16 01:04 UTC, kggilmer commented on aws-runtime/aws-core/build.gradle.kts
> +                implementation("org.slf4j:slf4j-simple:$slf4jVersion")
Erm but this is a JVM dependency..right?

2021-09-16 01:10 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigLoader.kt
> +public fun loadAwsConfiguration(platform: Platform = Platform): AwsConfiguration {
In order to test this function I need a way of overriding the Platform singleton.  Happily this works well in the tests.  I think Android uses this pattern in places.  But yeah maybe turning `Platform` into an interface and then moving the existing to another name such as `LocalPlatform` which implements the interface maybe better.  Personally I'm not bothered w/ Platform as the test technique is straightforward IMO.

2021-09-16 01:12 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfiguration.kt
> +public val AwsConfiguration.region: String?
My reasoning for making them extensions is that they're just a convenience on top of the existing type.  They don't add anything themselves.  Future properties may be introduced  as well.  That said it's minor and if you prefer them in the type I'll make the change.

2021-09-16 01:13 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfiguration.kt
> + * The AWS signing and endpoint region to use for a profile
Well I think the comment is referring to the profile, so localized to the scope of AWS configuration.  As such it reads accurate to me but LMK if I missed something.

2021-09-16 01:31 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigLoader.kt
> +        envProfileResolver(platform::getenv),
Regarding the JVM property, it's not mentioned in the spec so I'll check.

2021-09-16 13:43 UTC, aajtodd commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigLoader.kt
> +        envProfileResolver(platform::getenv),
it's not going to be mentioned in the spec but we should be attempting to be compatible with the JVM properties in use by the Java SDK. Matt mentioned we probably could define an SEP or update existing ones at this point now that we have more than one JVM SDK...

2021-09-16 13:44 UTC, aajtodd commented on aws-runtime/aws-core/build.gradle.kts
> +                implementation("org.slf4j:slf4j-simple:$slf4jVersion")
errr sorry meant the `jvm` gradle config. It's fine though we can leave it off

2021-09-23 23:13 UTC, kggilmer commented on aws-runtime/aws-core/build.gradle.kts
> +                implementation("org.slf4j:slf4j-simple:$slf4jVersion")
I've added to the `jvm` config.

2021-09-23 23:22 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigLoader.kt
> +@InternalApi
Fixed.  OoC, is the reason to have both just the error text associated w/ the annotation?

2021-09-24 00:06 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigLoader.kt
> +        envProfileResolver(platform::getenv),
I'd like to discuss this as a team before implementing non-spec behavior from the Java SDK before committing to this change.  I think generally it's a good idea but want to be sure we understand the ramifications of copying behavior from another SDK.

2021-09-24 00:17 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigLoader.kt
> +internal fun envProfileResolver(getEnv: (String) -> String?): String = getEnv("AWS_PROFILE") ?: Literals.DEFAULT_PROFILE
I've updated this line.  I don't see any others.

2021-09-24 00:17 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigParser.kt
> +    const val NEW_LINE: Char = '\n'
yes

2021-09-24 00:20 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigParser.kt
> +public sealed class Token {
it doesn't need to be but it resolves this compiler warning in a few places:

```
'internal' property exposes its 'private-in-file' type argument Token
```

2021-09-24 00:21 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigParser.kt
> +        "AWS_CONFIG_FILE",
deferring until discussion mentioned above

2021-09-24 00:22 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigParser.kt
> +open class AwsConfigParseException(message: String) : SdkBaseException(message)
good catch, thanks.

2021-09-24 00:23 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigParser.kt
> +private var helpText = "See https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html for file format details."
fixed

2021-09-24 00:25 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigParser.kt
> + * TODO: When/if the stdlib version becomes stable this should be removed
I prefer this over opting in, generally because I don't like using "unstable" code.

2021-09-24 00:29 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/ContinuationMerger.kt
> +data class FileLine(val lineNumber: Int, val content: String)
fixed

2021-09-24 13:29 UTC, aajtodd commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigLoader.kt
> +@InternalApi
It's a bit of that and a bit of respecting the fact that they are in fact different libraries that can evolve separately. In practice there likely isn't much difference since the aws-runtime depends on smithy-kotlin runtime internal APIs of course. I think there is some benefit to the AWS specific annotation since it is most likely the one customers will interact with but could be persuaded to collapse these perhaps.

2021-09-24 13:32 UTC, aajtodd commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigParser.kt
> +public sealed class Token {
Can it be `internal` then?

2021-09-24 22:04 UTC, ianbotsf approved these changes
Love the new logging output!

2021-09-24 22:04 UTC, ianbotsf commented on examples/client-generator/model/weather-service.smithy
>    @required cityId: CityId
**Question**: Are these `countryCode` updates intentional or cross-branch bleed?

2021-09-24 22:05 UTC, ianbotsf commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigLoader.kt
> +public fun loadAwsConfiguration(platform: Platform = Platform): AwsConfiguration {
👆 Ping on this.

2021-09-24 23:01 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigParser.kt
> +public sealed class Token {
yes it's now `internal`

2021-09-25 00:11 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigLoader.kt
> +public fun loadAwsConfiguration(platform: Platform = Platform): AwsConfiguration {
My apologies, this one doesn't show up in the Files view for whatever reason so I missed it.  Well I believe that the places we'll need this don't exist yet, but generally anywhere that we'd need to pull any non-credential related properties out.  The spec links to some service specific settings for example.  In regards to testability, yes you're aboslutely right.  It's a PITA to test.  I'm following another of your suggestions and removing the default value of `Platform` such that it must be passed at the top level to retrieve a configuration in all cases.  Assumingthe call location also allows for passing platform it can be tested by mocking `Platform` and supplying your test configuration file.  I'll provide a unit test to illustrate.

2021-09-25 00:14 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/AwsSdkSetting.kt
> +public inline fun <reified T> AwsSdkSetting<T>.read(platform: Platform = Platform): T? =
Agreed and has more weight in light of your observations above regarding suitability for testing.

2021-09-25 00:19 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigParser.kt
> +                            throw AwsConfigParseException("Expected a profile definition preceding '${token.key}' on line $lineNumber. $helpText")
`ctrl` to the `c`, `ctrl` to the `v`

2021-09-25 00:25 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigParser.kt
> +                    is Token.Unmatched -> { logger.warn("Ignoring unknown data on line ${token.line.lineNumber}") }
No, a remnant from refactoring.

2021-09-25 00:29 UTC, kggilmer commented on examples/client-generator/model/weather-service.smithy
>    @required cityId: CityId
Yeah these are not part of my changes.  Will pull latest from main.

2021-09-27 13:32 UTC, aajtodd commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/Annotations.kt
> +    message = "This API is internal to aws-runtime and generated SDK's and should not be used. It could be removed or changed without notice."
Ughh apparently I need to go back to grammar school.

2021-09-27 14:22 UTC, aajtodd approved these changes
Nothing blocking. Couple suggestions/discussion but looks good

2021-09-27 16:54 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/AwsSdkSetting.kt
> +    public object AwsCredentialProfilesFile :
Looks like I mistakenly used the Java v1 name for this.  Fixed.

2021-09-27 17:01 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/AwsSdkSetting.kt
> +public inline fun <reified T> AwsSdkSetting<T>.read(platform: Platform): T? =
> it doesn't even make sense as a parameter anywhere.

While it's weird, it does allow to supply test instances which is important for verification.

> If all of this is to facilitate testing and what not we should probably define an interface that we require (whether that is local to config or a more general purpose one).

Yeah I think we have all come to this conclusion, but I'd rather save this refactoring for a subsequent effort.

> Second, I don't love having to thread a type around everywhere. Given that Platform generally involves things that we can control (environment variables, system properties, etc) why does it need to be a parameter?

to facilitate testing.

> This allows you to mock functions for tests but have the public API be cleaner. e.g.

Since this API is internal, it's not clear to me that the value of two functions to save one parameter in a single function is a net gain.  But, it's a good idea and I appreciate the suggestion.

> Unrelated, can we rename this to resolve()?

Yes

2021-09-27 18:14 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigLoader.kt
> +public suspend fun loadAwsConfiguration(platform: Platform): AwsConfiguration {
`loadAllProfiles()` supports the use case of loading all profiles.  I will update the names to be more consistent:

`loadAwsProfile()` -> `loadActiveAwsProfile()`
`loadAllProfiles()` -> `loadAwsProfiles()`
`AwsConfiguration` -> `AwsProfile`

2021-09-27 18:41 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfiguration.kt
> +data class AwsConfiguration(
There is now an internal function that can supply all profiles.  I've renamed `AwsConfiguration` to `AwsProfile`.  For multiple profiles, this is internal and not exposed and so uses a Map of Maps of String pairs.  If/when we need that somewhere else it can be refactored if needed.

2021-09-27 18:52 UTC, ianbotsf commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigLoader.kt
> +public fun loadAwsConfiguration(platform: Platform = Platform): AwsConfiguration {
Would it be better to define a class/interface this method lives inside to allow for dependency injection at the call site?

```kotlin
class AwsConfigurationLoader() {
    fun load(platform: Platform = Platform): AwsConfiguration = …
}

class SomethingThatNeedsConfig(configLoader: AwsConfigurationLoader) {
    fun foo() {
        val config = configLoader.load()
        …
    }
}
```

If we don't do that, I suppose the DI alternative is accepting a function type:

```kotlin
class SomethingThatNeedsConfig(loadAwsConfiguration: () -> AwsConfiguration = loadAwsConfiguration) {
    fun foo() {
        val config = loadAwsConfiguration()
        …
    }
}
```

2021-09-27 20:07 UTC, kggilmer commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/config/AwsConfigLoader.kt
> +public fun loadAwsConfiguration(platform: Platform = Platform): AwsConfiguration {
Right, the latter is what can be done now for any clients.  I'd like to see how refactoring `Platform` such that there is an interface shakes out before going any further on this end.

2021-09-27 21:07 UTC, merged