refactor(rt)!: split auth and signing packages; expose a method to sign requests
aws/aws-sdk-kotlin pull request #318
Opened 2021-09-17 14:57 UTC by aajtodd

## Issue \#

N/A

support PR(s):
* https://github.com/awslabs/smithy-kotlin/pull/479
* https://github.com/awslabs/aws-crt-kotlin/pull/30

## Description of changes

* move signing related things to `signing` subpackage of `auth`
* move credential related things to `credentials` subpackage of `auth`
* expose a top level `sign()` method that can be used to sign HttpRequests independent of middleware
* refactor middleware to re-use `AwsSigningConfig` for it's feature configuration
* expose SigV4A algorithm enum value

## Scope

This is a breaking change for users that import a specific credentials provider. They will need to update their code to the new import location.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-17 15:34 UTC, ianbotsf approved these changes

2021-09-17 21:26 UTC, kggilmer requested changes
Overall LGTM but would like to think a bit more about the modeling of `AwsSigningConfig.region`

2021-09-17 21:26 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/signing/AwsSigning.kt
> +public data class SigningResult<T>(val output: T, val signature: ByteArray) {
question

why is equals/hashCode impl required for this type?

2021-09-17 21:26 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/signing/AwsSigning.kt
> +/**
suggestion

I assume the intent is that customers may use this type since there is no internal markers.  the KDoc should probably be a bit more thorough in this case, specifying details for parameters for example.

2021-09-17 21:26 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/signing/AwsSigning.kt
> +public suspend fun sign(request: HttpRequest, config: AwsSigningConfig): SigningResult<HttpRequest> {
same as above regarding kdoc

2021-09-17 21:26 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/signing/Presigner.kt
> +/*
my bad

2021-09-17 21:26 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/signing/AwsSigV4SigningMiddleware.kt
> +            if (builder.region == null) { builder.region = "" }
question

It's not clear to me that this mapping from null to empty-string is better than allowing `region` to be a nullable property of `AwsSigningConfig` and deal with handling null based on context at points in code where the property is accessed.  From my understanding, here `""` means `null`, is this correct?

2021-09-20 12:56 UTC, aajtodd commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/signing/AwsSigning.kt
> +public data class SigningResult<T>(val output: T, val signature: ByteArray) {
Data classes don't handle arrays as expected. What you want usually is to compare the contents of the array not whether they are the same instance (which is what it will do by default). Intellij even warns you of this and generates the more appropriate one for you.

2021-09-20 13:00 UTC, aajtodd commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/signing/AwsSigV4SigningMiddleware.kt
> +            if (builder.region == null) { builder.region = "" }
Yeah basically. I changed this such that the middleware could just re-use the signing config rather than re-declaring an equivalent config type.

The issue I ran into is we (rightfully so) designed `AwsSigningConfig` to be general purpose and throw errors if not [configured correctly](https://github.com/awslabs/aws-sdk-kotlin/blob/b8a6bc72932f32425b4abef07ef160ef265eb70d/aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/signing/AwsSigningConfig.kt#L32). 

It's didn't seem necessarily the right thing to do to remove the validation since doing so will move the need to validate into each use of it. I opted to just abuse the type rather than remove the validation but if you see a cleaner way I'm all ears.

2021-09-23 19:41 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/signing/AwsSigV4SigningMiddleware.kt
> +            if (builder.region == null) { builder.region = "" }
IMO it would be cleaner to model the difference between presigning and signer middleware via different types which accurately capture their required inputs.  So based on your breakdown the middleware would have a type in which `region` is nullable and the presigner would have a `region` member that was non-null.

2021-09-24 17:29 UTC, aajtodd commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/signing/AwsSigV4SigningMiddleware.kt
> +            if (builder.region == null) { builder.region = "" }
That's how it was. I changed it because the signing config has a lot of knobs and it was a lot of duplication. If anything I would just remove the `requireNotNull()` on the signing config and enforce it elsewhere. The only reason I left is to try and give customers an early indication that their signing config isn't valid.

2021-09-25 00:48 UTC, kggilmer commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/signing/AwsSigV4SigningMiddleware.kt
> +            if (builder.region == null) { builder.region = "" }
I would prefer that the types used in signing accurately modeled the required inputs.  If you and @ianbotsf prefer this approach however I'm fine with that.

2021-09-25 00:48 UTC, kggilmer approved these changes

2021-09-27 15:20 UTC, ianbotsf commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/signing/AwsSigV4SigningMiddleware.kt
> +            if (builder.region == null) { builder.region = "" }
I agree with @kggilmer on this one. Having separate config classes which use different types for `region` seems more correct and more expected to me.

2021-09-27 15:43 UTC, aajtodd commented on aws-runtime/auth/common/src/aws/sdk/kotlin/runtime/auth/signing/AwsSigV4SigningMiddleware.kt
> +            if (builder.region == null) { builder.region = "" }
Reverted to using a dedicated type for middleware config

2021-09-27 17:35 UTC, merged