feat: implement basic retry support in runtime
aws/aws-sdk-kotlin pull request #328
Opened 2021-09-30 17:34 UTC by ianbotsf

## Issue \#

Addresses #20 and smithy-kotlin#224.

## Description of changes

This change adds support for retries in the runtime (but does not yet integrate them into codegen—separate PR coming). See the included design doc (**docs/design/retries.md**) for more details.

Companion PR: smithy-kotlin#487

## Scope

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-10-01 16:08 UTC, aajtodd requested changes
Looks good, couple questions

2021-10-01 16:08 UTC, aajtodd commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/retries/SdkRetryPolicy.kt
> +        "RequestTimeout" to Timeout,
correctness

Aren't both `RequestTimeout` and `RequestTImeoutException` classified as `Transient`?

2021-10-01 16:08 UTC, aajtodd commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/retries/SdkRetryPolicy.kt
> +    override fun evaluateOtherExceptions(ex: Throwable): RetryDirective? = when (ex) {
correctness

Don't we need to classify raw HTTP status codes `500`, `502`, `503`,  and `504` as `Transient`?

2021-10-04 18:19 UTC, ianbotsf commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/retries/SdkRetryPolicy.kt
> +        "RequestTimeout" to Timeout,
The spec calls these kinds of errors "transient" but our code calls them "timeout" errors. Transient isn't a good name for these since that's a class of error that also encompasses throttling and many server-side error conditions.

2021-10-04 18:54 UTC, ianbotsf commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/retries/SdkRetryPolicy.kt
> +    override fun evaluateOtherExceptions(ex: Throwable): RetryDirective? = when (ex) {
Hmm, seems I missed that part. In order to accomplish that, we'll need access to the status code of the response which is only available in the metadata when casting the [`protocolResponse`](https://github.com/awslabs/smithy-kotlin/blob/main/runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/Exceptions.kt#L92-L93) to an [`HttpProtocolResponse`](https://github.com/awslabs/smithy-kotlin/blob/main/runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/response/HttpResponse.kt#L23-L27), which is defined in **smithy-kotlin:runtime:protocol:http**. Given that `SdkRetryPolicy` is currently located in **aws-sdk-kotlin:aws-runtime:aws-core**, it seems we have two options:

* Make **aws-sdk-kotlin:aws-runtime:aws-core** depend on **smithy-kotlin:runtime:protocol:http**. Seems odd to have a "core" package depend on a protocol implementation but maybe that's okay for AWS SDK since all the services run on HTTP?
* Move the retry policy to **aws-sdk-kotlin:aws-runtime:protocols:http**, which already depends on **smithy-kotlin:runtime:protocol:http**. Seems odd to have a retry policy defined somewhere protocol-specific but again maybe that's okay for AWS SDK since all the services run on HTTP?

Which is least odd?

2021-10-05 14:22 UTC, aajtodd commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/retries/SdkRetryPolicy.kt
> +    override fun evaluateOtherExceptions(ex: Throwable): RetryDirective? = when (ex) {
> Make `aws-sdk-kotlin:aws-runtime:aws-core` depend on `smithy-kotlin:runtime:protocol:http`

I don't love this. I just moved config out of `aws-core` for similar reasons. It's an option though.


> Move the retry policy to aws-sdk-kotlin:aws-runtime:protocols:http, which already depends on smithy-kotlin:runtime:protocol:http. Seems odd to have a retry policy defined somewhere protocol-specific but again maybe that's okay for AWS SDK since all the services run on HTTP?

This is closer to what makes sense to me. I could also see defining the core logic in `aws-core` (basically what you have now) and having it be an `open` class that can be further customized for `HTTP` protocols? 

FWIW this looks to be where Rust defined theirs (`aws-http`). 

I don't love (3) either because it defeats the entire point of the generic interface. At that point we should maybe reconsider the design/relationships.

2021-10-05 18:26 UTC, aajtodd approved these changes
Fix and ship!

2021-10-05 18:26 UTC, aajtodd commented on aws-runtime/protocols/http/common/src/aws/sdk/kotlin/runtime/http/retries/AwsDefaultRetryPolicy.kt
> +    internal val knownStatusCodes = mapOf(
correctness

Aren't these `Transient` errors?

2021-10-05 18:26 UTC, aajtodd commented on aws-runtime/protocols/http/common/src/aws/sdk/kotlin/runtime/http/retries/AwsDefaultRetryPolicy.kt
> +    internal val knownStatusCodes = mapOf(
Also don't we need to define error codes for `RequestTimeout` and `RequestTimeoutException` as `Transient` error codes?

2021-10-05 18:38 UTC, ianbotsf commented on aws-runtime/protocols/http/common/src/aws/sdk/kotlin/runtime/http/retries/AwsDefaultRetryPolicy.kt
> +    internal val knownStatusCodes = mapOf(
Right you are, they should be `Timeout`.

2021-10-05 19:00 UTC, merged