Refactor presigner querystring
aws/aws-sdk-kotlin pull request #388
Opened 2021-10-29 23:49 UTC by kggilmer

## Issue \#

https://github.com/awslabs/aws-sdk-kotlin/issues/387

## Description of changes

* This is an interm (draft) PR for testing.  The "real" PR will likely be different.

## Scope

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-01 17:23 UTC, ianbotsf commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/PresignerGenerator.kt
> +            "com.amazonaws.sts#AWSSecurityTokenServiceV20110615" to "com.amazonaws.sts#GetCallerIdentity" -> true
**Comment**: I wonder if this could be derived from whether a body is supplied in the request. Take `PutObject` for instance...most of the time I expect no body will be supplied since [the feature exists to allow callers without a reference to the SDK or credentials to upload a file](https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html). But suppose a caller did provide a body and merely wanted to defer execution until later...under those conditions I'd imagine `shouldSignBody` should return `true`.

2021-11-01 18:34 UTC, kggilmer commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/PresignerGenerator.kt
> +            "com.amazonaws.sts#AWSSecurityTokenServiceV20110615" to "com.amazonaws.sts#GetCallerIdentity" -> true
Good call, I'll take a look.  Also sharing the link Aaron provided relating to this topic:

2021-11-09 16:15 UTC, aajtodd requested changes
Overall looks good. Couple signing config related issues to address

2021-11-09 16:15 UTC, aajtodd commented on services/s3/e2eTest/S3TestUtils.kt
> +    fun httpResponseFromGetRequest(presignedRequest: HttpRequest): Pair<Int, String?> {
suggestion

If this is general purpose it probably should have a parameter name of `request` rather than `presignedRequest`. You also probably don't need one for both `GET` and `PUT` requests. Just copy the original request (e.g. `req.copy(method=HttpMethod.GET)` or pass in the method as a parameter.

Personally I'd like us to eat our own dog food though rather than using the JVM `HttpsUrlConnection` by using `SdkHttpClient` with our own HTTP engine. We shouldn't really even need these two methods.

2021-11-09 16:15 UTC, aajtodd commented on services/sts/e2eTest/STSTest.kt
> +class STSIntegrationTest {
nit

`StsPresignTest` or `StsPresignIntegrationTest`

2021-11-09 16:15 UTC, aajtodd commented on services/sts/e2eTest/STSTest.kt
> +fun httpResponseCodeFromGetPresignedUrl(presignedRequest: HttpRequest): Int {
nit

This now exists in 3 places which furthers my inclination to just do away with it and use our own machinery.

```kotlin
fun testPutObjectPresigner(): Unit = runSuspendTest {
     val engine = CrtHttpEngine()
     val client = StsClient { region = "us-east-2"; httpEngine = engine }
     
    ...
     
     val presignedRequest = req.presign(...)
     
     // make any assertions on the request and/or copy to a new request if needed
     // e.g. to change the method
     // val presignedGet = presignedRequest.copy(method = HttpMethod.GET)
     assertTrue(presignedRequest.body is HttpBody.Empty)
     
     // use our own internal client which knows how to consume `HttpRequest` already
     val httpClient = sdkHttpClient(engine)
     
     val call = httpClient.call(presignedRequest)
     call.complete()

     assertEquals(200, call.response.status.value)
     engine.close()
}

```

2021-11-09 19:14 UTC, kggilmer commented on services/polly/e2eTest/PollyTest.kt
> +class STSIntegrationTest {
whoops, thanks for catching the copypasta

2021-11-09 19:39 UTC, ianbotsf approved these changes
No comments beyond what @aajtodd said.

2021-11-09 21:22 UTC, kggilmer commented on aws-runtime/aws-signing/common/src/aws/sdk/kotlin/runtime/auth/signing/Presigner.kt
> +        signedBodyValue = if (requestConfig.signBody) null else AwsSignedBodyValue.UNSIGNED_PAYLOAD
What you're saying here makes sense to me but it's not clear what is incorrect with line 93.

2021-11-09 21:22 UTC, kggilmer commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/PresignerGenerator.kt
> +    // Determine if body should be signed.  If body is to be signed, null is passed to signer for signedBodyValue
updated comment

2021-11-09 21:22 UTC, kggilmer commented on services/polly/e2eTest/PollyTest.kt
> +        urlConnection!!.inputStream.close()
removed in favor of dogfood

2021-11-09 21:22 UTC, kggilmer commented on services/s3/e2eTest/S3IntegrationTest.kt
> +    fun testPutObjectPresigner() = runSuspendTest {
tests cleaned up

2021-11-09 21:24 UTC, kggilmer commented on services/s3/e2eTest/S3TestUtils.kt
> +    fun httpResponseFromGetRequest(presignedRequest: HttpRequest): Pair<Int, String?> {
Opted to use the CRT for GETs, continue to use HttpUrlConnection for PUT.  IMO in this case dogfooding is a mixed bag, because the nature of the feature is that the presigned request should be usable outside of the context of the SDK.  So, we should ensure that some CRT HTTP client specific behavior isn't being relied upon for test pass in some future set of refactorings.

2021-11-09 21:24 UTC, kggilmer commented on services/sts/e2eTest/STSTest.kt
> +class STSIntegrationTest {
cleaned up tests

2021-11-09 21:24 UTC, kggilmer commented on services/sts/e2eTest/STSTest.kt
> +fun httpResponseCodeFromGetPresignedUrl(presignedRequest: HttpRequest): Int {
updated, see above

2021-11-09 21:31 UTC, aajtodd commented on aws-runtime/aws-signing/common/src/aws/sdk/kotlin/runtime/auth/signing/Presigner.kt
> +        signedBodyValue = if (requestConfig.signBody) null else AwsSignedBodyValue.UNSIGNED_PAYLOAD
If the config/user is requesting `signBody` we are setting `null` AND if there is in fact a body, CRT will sign it. Thus you don't end up with an unsigned body.

As written I'm very confused on what we are trying to do here and with the way it is written it looks like a bug. What are we _trying_ to do here?

2021-11-09 21:36 UTC, kggilmer commented
I took another look at the STS presigner based on the discussion in the morning standup.  It turns out that the op is a GET and there is in fact no body.  So there is nothing to append to the querystring.  It remains true in testing though that when a presigned request is generated on the qs, CRT must read the body to calculate the signature.

2021-11-09 21:37 UTC, kggilmer commented on aws-runtime/aws-signing/common/src/aws/sdk/kotlin/runtime/auth/signing/Presigner.kt
> +        signedBodyValue = if (requestConfig.signBody) null else AwsSignedBodyValue.UNSIGNED_PAYLOAD
I updated the property name to be more descriptive of what CRT does based on the value.

2021-11-10 14:59 UTC, aajtodd approved these changes
Fix and ship

2021-11-10 14:59 UTC, aajtodd commented on services/sts/e2eTest/STSPresignerTest.kt
> +    fun testPutObjectPresigner() = runSuspendTest {
fix

more copy pasta, should be `testGetCallerIdentityPresigner` or something

2021-11-10 14:59 UTC, aajtodd commented on services/sts/e2eTest/STSPresignerTest.kt
> +        val presignedRequest = req.presign(c.config, 60)
question

Are there any assertions to make about a presigned request here or for s3/polly? e.g. should a particular protocol/method be asserted, or no http body, etc?

2021-11-10 17:56 UTC, kggilmer commented on services/sts/e2eTest/STSPresignerTest.kt
> +    fun testPutObjectPresigner() = runSuspendTest {
fixed

2021-11-10 17:58 UTC, kggilmer commented on services/sts/e2eTest/STSPresignerTest.kt
> +        val presignedRequest = req.presign(c.config, 60)
Essentially the tests here simply verify that the signed request is not rejected by the service.  A deeper level of testing would include verifying the request values, yes.  IMO this is not important here because it seems unlikely that an invalid request (eg unexpected body provided, wrong method) would result in a valid service request.  Please LMK if you see it differently

2021-11-10 19:58 UTC, merged