API service docs workaround
aws/aws-sdk-kotlin pull request #405
Opened 2021-11-04 19:19 UTC by kggilmer

Build job that generates SDK API docs individually and link with a top index.

## Issue \#

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-09 16:59 UTC, ianbotsf commented on .github/workflows/api-docs.yml
> +            fi
**Question**: I don't understand this. Won't this set `docs-generated` to whatever the last result is in the loop? Meaning if an excluded service is last in the loop, `docs-generated` will be false even if other services' docs were generated.

2021-11-09 16:59 UTC, ianbotsf commented on .github/workflows/api-docs.yml
> +          tar cJvf api-docs-${{ matrix.service-prefix }}.tar.xz build/dokka/*
**Question**: The `v` in this `tar` command will significantly increase the logs. Is it strictly necessary?

2021-11-09 16:59 UTC, ianbotsf commented on .github/workflows/api-docs.yml
> +        service-prefix: [ a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z ]
**Comment**: To get a more even distribution, you could consider using modular arithmetic instead of a prefix. With this method, some instances will be building 30+ services while others will build 1.

2021-11-09 18:20 UTC, aajtodd commented on .github/workflows/api-docs.yml
> +        service-prefix: [ a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z ]
We already have a way to do this in the codebuild service check job FYI:

```shell
      - echo "Bootstrapping AWS services"
      - find codegen/sdk/aws-models -name '*.json' | sort | awk "NR % $NUM_JOBS == $JOB" > services.txt
      - cat services.txt
      - includes=$(cat services.txt | cut -d"/" -f4 | cut -d"." -f1 | sed 's/^\(.*\)$/+\1/' | paste -sd "," -)
      - echo $includes
      - ./gradlew -Paws.services=$includes :codegen:sdk:bootstrap
```

2021-11-09 19:07 UTC, aajtodd commented on .github/workflows/api-docs.yml
> +  workflow_dispatch:
it would be nice to have this run off release as well and just upload artifacts to a release OR have inputs to the workflow dispatch such that it updates the release with the artifact (i.e. use this release and tag to run with)

Creating independent releases is sort of confusing and creates extra tags for only this purpose. I suppose if we only plan on this being a stop gap for a very short time it won't matter but something to consider doing if it isn't too much work.

2021-11-09 21:46 UTC, kggilmer commented on .github/workflows/api-docs.yml
> +  workflow_dispatch:
At this point the job is best manually run due to time it takes the job to complete and some flakeyness observed in the past few weeks.  I've seen weird behavior where jobs are simply cancelled...some process returns 1 and the job halts.  I've also seen a case where a step simply froze.  The runner may have died or something.  In any case, beause of this random flakiness, I do not think we should tie this job in a critical-path to the weekly release.  if this job fails w/ some weirdness, it can be re-run without impacting other release process steps.

After a few weeks of job runs go by ok (and we see that the need for this job will not be super short term) I totally agree with what you've said here and can make followup work to integrate it into the SDK release.

2021-11-09 21:46 UTC, kggilmer commented on .github/workflows/api-docs.yml
> +  PUBLISH_GH_PAGES: false # toggle publishing on github pages branch
sure

2021-11-09 22:13 UTC, kggilmer commented
* Responded to PR feedback
* Remove unneeded variables, configuration
* Assume/clone same branch/tag exists on smithy-kotlin rather than cloning head of default branch

Test from latest revision: https://github.com/kggilmer/aws-sdk-kotlin/runs/4158355794

2021-11-09 22:46 UTC, ianbotsf requested changes

2021-11-09 22:46 UTC, ianbotsf commented on .github/workflows/api-docs.yml
> +            fi
**Correctness**: I think this is a regression from what it was before. Now _any_ exclusion will set the entire step's `docs_generated` to `false`...even if the excluded service wasn't last. I think you want to initially set `docs_generated=false` and conditionally set it to `true` in the happy path of `if [[ $excluded == 0 ]]` (line 69-81). That'll ensure it's `true` if _at least one_ service generated docs.

2021-11-09 22:53 UTC, kggilmer commented on .github/workflows/api-docs.yml
> +            fi
Yes.  test for this is still running.  Rather than save time by pushing untested updates I'm going to wait for jobs to complete.  If you care I'm pushing test changes here first: https://github.com/kggilmer/aws-sdk-kotlin/tree/feat-api-docs-codex

2021-11-10 14:54 UTC, aajtodd approved these changes

2021-11-10 14:54 UTC, aajtodd commented on .github/workflows/api-docs.yml
> +  workflow_dispatch:
> I do not think we should tie this job in a critical-path to the weekly release

I don't believe it will block anything it would just trigger off the release event and then upload artifacts to that release. 

At any rate in the short run we can keep it manual but could still have it tied to an existing release such that tag/release are inputs to the workflow dispatch, see:
https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#example-workflow-configuration

That way we don't have to create separate tags/releases just for docs, they can be tied to the same tags/release as an actual release.

2021-11-10 15:47 UTC, aajtodd commented on .github/workflows/api-docs.yml
> +  workflow_dispatch:
Just saw this as well FYI: https://cli.github.com/manual/gh_release_upload

2021-11-10 16:37 UTC, kggilmer commented on .github/workflows/api-docs.yml
> +            fi
@ianbotsf the awslabs branch is now up to date with my private repo test updates.  Please LMK if you still see an issue here.

2021-11-10 17:06 UTC, ianbotsf approved these changes

2021-11-10 17:09 UTC, kggilmer commented on .github/workflows/api-docs.yml
> +  workflow_dispatch:
The "critical path" part is how the release process is altered if the api-docs job has a spurious failure.  Re-release?  Run the job manually?  

In any case I realized it would be pretty easy to test it working and so added it now rather than later.  Latest version builds from (pre)release hook.  See here for (presently running) demo: https://github.com/kggilmer/aws-sdk-kotlin/actions/runs/1445251321

2021-11-10 20:25 UTC, kggilmer commented on .github/workflows/api-docs.yml
> +  workflow_dispatch:
> the workflow dispatch takes as inputs the release/tag to work on and upload to

I had something like this in an earlier version of the workflow.  Now it simply uses the branch which you select when launching any workflow via workflow_dispatch.  However I now realize this isn't going to work for us.  In "PR mode" we have a convention of consistent branch names across repos, but this association stops there.  For release builds we need to pull the version of `smithy-kotlin` from the gradle properties in `aws-sdk-kotlin` to ensure to pull down the correct upstream dependency.  This implies that smithy-kotlin is released before aws-sdk-kotlin, which I believe we already are working this way.

> you could then cut a release and manually go run the job 

I've updated the `workflow_dispatch` to require specifying the tag.  I assumed that tags and branches were the same here but turns out that's not the case so an explicit field is required.

Testing manual launch: https://github.com/kggilmer/aws-sdk-kotlin/actions/runs/1445980129
Testing release launch: https://github.com/kggilmer/aws-sdk-kotlin/actions/runs/1445987751

2021-11-11 02:32 UTC, kggilmer commented on .github/workflows/api-docs.yml
> +  workflow_dispatch:
Eventually completed test run: https://github.com/kggilmer/aws-sdk-kotlin/actions/runs/1446809624

Release: https://github.com/kggilmer/aws-sdk-kotlin/releases/tag/v0.9.0-alpha

2021-11-11 16:07 UTC, kggilmer commented on .github/workflows/api-docs.yml
> +        service-prefix: [ a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z ]
I'll come back to this great optimization idea if it ends up that the time savings will be of benefit.  As it stands the job runs between 1 and 2 hours.  A flatter distribution will certainly cause the job to complete faster but don't expect it to make a game-changing dent in the total job time.

This job is fairly complex (for my limited gh workflow skill set at least) and even minor changes take lots of wall clock time to tweak and test.

2021-11-11 16:17 UTC, aajtodd approved these changes

2021-11-11 16:17 UTC, aajtodd commented on gradle.properties
> +smithyKotlinVersion=0.7.1-alpha
do these versions need reverted?

2021-11-11 16:17 UTC, aajtodd commented on .github/workflows/api-docs.yml
> +          ref: ${{ env.GITHUB_REF }}
correctness/question

Won't this use the ref from aws-sdk-kotlin? Will this be the correct version of `smithy-kotlin`?

2021-11-11 16:56 UTC, kggilmer commented on .github/workflows/api-docs.yml
> +          ref: ${{ env.GITHUB_REF }}
Yes this is wrong, will fix.

2021-11-11 17:00 UTC, kggilmer commented on .github/workflows/api-docs.yml
> +          ref: ${{ env.GITHUB_REF }}
Fix verified

![image](https://user-images.githubusercontent.com/65979407/141338474-0947e658-b989-46fa-8885-dcc31abe793d.png)

2021-11-11 17:02 UTC, kggilmer commented on gradle.properties
> +smithyKotlinVersion=0.7.1-alpha
yep, reverting before push

2021-11-11 20:20 UTC, merged