fix: credentials provider ownership
aws/aws-sdk-kotlin pull request #498
Opened 2022-01-11 16:46 UTC by aajtodd

## Issue \#

N/A

## Description of changes

* Adds a `borrow()` extension that wraps an existing provider with a no-op close implementation
* Close the client config `credentialsProvider` in the service client's close implementation (if it was borrowed it will do nothing, otherwise it will close it)
* Implement `Closeable` for shared `AwsClientConfig`

## Comments

I still don't love any of this. I think my preference would still maybe be to just make clients "dumb" and make the shared config be the "one true way" to create service clients. This would make only one thing that needs closed and clients wouldn't even need to implement closeable since they wouldn't ever own anything. That isn't palatable to everyone though which leaves us with having to deal with managing ownership state. There are other possible solutions than what is proposed here, please share your ideas if you've got them.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-11 17:37 UTC, ianbotsf requested changes
I like the general direction of this, it's nice and clean!

2022-01-11 17:37 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/internal/BorrowedCredentialsProvider.kt
> + * This allows the SDK to treat resources as owned and not have to track ownership state.
**Nit**: it's → its

2022-01-11 17:37 UTC, ianbotsf commented on aws-runtime/aws-types/common/src/aws/sdk/kotlin/runtime/client/AwsClientConfig.kt
> +
**Comment**: This seems dangerous. Given the implications of forgetting to close something, it seems like there should be no default `close` and implementors should _have_ to make explicit decisions about closing.

2022-01-11 17:37 UTC, ianbotsf commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/core/AwsHttpProtocolClientGenerator.kt
> +    }
**Comment**: Would be nice to have a new test for this.

2022-01-11 17:45 UTC, aajtodd commented on aws-runtime/aws-types/common/src/aws/sdk/kotlin/runtime/client/AwsClientConfig.kt
> +
We could do that but every generated `Config` implements `AwsClientConfig` and so we would have to generate a `close()` method there. 

We could do that and just do `config.close()` instead in the generated client close implementation?

It would be nice to express a way to say that a property represents a closeable resource I guess and have the config generator automatically render it in the close implementation.

2022-01-11 19:41 UTC, kggilmer approved these changes

2022-01-11 19:41 UTC, kggilmer commented on aws-runtime/aws-types/common/src/aws/sdk/kotlin/runtime/client/AwsClientConfig.kt
> +
> It would be nice to express a way to say that a property represents a closeable resource I guess and have the config generator automatically render it in the close implementation.

+1.  Seems like going this way we'd be able to verify that a given codegen output cleans up resources as expected in CI

2022-01-19 17:53 UTC, ianbotsf approved these changes

2022-01-21 22:01 UTC, kggilmer approved these changes
Question regarding Closable and CredentialsProvider but nothing to warrant blocking the PR

2022-01-21 22:01 UTC, kggilmer commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/core/AwsHttpProtocolClientGenerator.kt
> +            .write("(config.credentialsProvider as? #T)?.close()", RuntimeTypes.IO.Closeable)
question

I'm missing something regarding `Closable` and `CredentialsProvider` types.  The latter doesn't specify a close method, but the `WrappedCredentialsProvider` does combine  the two, and looks here that we check to see if the cp implements closable and then call it if so.  Given this would it not be simpler to have CP simply implement `Closable`?  Put another way, what value are we gaining by having only `BorrowedCredentialsProvider` implement `Closable`?

2022-01-24 14:52 UTC, aajtodd commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/core/AwsHttpProtocolClientGenerator.kt
> +            .write("(config.credentialsProvider as? #T)?.close()", RuntimeTypes.IO.Closeable)
> what value are we gaining by having only `BorrowedCredentialsProvider` implement `Closable`

It isn't the only one that implements `Closeable`. All of the following do:
* `DefaultChainCredentialsProvider`
* `EcsCredentialsProvider`
* `ImdsCredentialsProvider`
* `ProfileCredentialsProvider`

Environment, StsWebIdentity, StsAssumeRole, and SSO providers do not implement `Closeable`. 

The issue is that the type is just `CredentialsProvider` both here and in `BorrowedCredentialsProvider` so both have to check if the underlying implementation actually needs to be closed or not. I have gone back and forth on this and considered making `CredentialsProvider` implement `Closeable` but ultimately decided against it to be more clear about what types do and don't need to be closed when used directly by a customer. I could be persuaded the other way though if you want to make a case for it.

2022-01-24 17:14 UTC, kggilmer commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/core/AwsHttpProtocolClientGenerator.kt
> +            .write("(config.credentialsProvider as? #T)?.close()", RuntimeTypes.IO.Closeable)
Personally I'm not sure what's best either way, but it may be more satisfying of "We ensure accessing AWS services is performant, secure, and reliable for developers" if `CredentialProvider` implements `Closable`.  I reckon this may be so because if closability varies, intuitively it seems likely that someone may forget that a particular CP needs to be closed.  Or perhaps a function that takes a non closing CP is passed a requires-closing CP during a refactor but the nuance is dropped in the refactor. If all CPs must be closed (with some of them being NOP), it seems to be less likely that this kind of bug would occur.  This comes at the expense of greater overall complexity of the CP type, however the value may outweigh the cost.  @ianbotsf any thoughts on this?

2022-01-24 17:18 UTC, ianbotsf commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/core/AwsHttpProtocolClientGenerator.kt
> +            .write("(config.credentialsProvider as? #T)?.close()", RuntimeTypes.IO.Closeable)
I'm in favor of explicitly modelling closability. If it can/must be closed, it should be `Closeable`. Otherwise, I don't think we should unnecessarily attach closing semantics to the `CredentialProvider` interface because _some_ of the implementations are closeable.

2022-01-27 00:40 UTC, aajtodd commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/core/AwsHttpProtocolClientGenerator.kt
> +            .write("(config.credentialsProvider as? #T)?.close()", RuntimeTypes.IO.Closeable)
Ya I can see both sides here and I hear the concern. I'm going to leave it as is for now and lets see how it shakes out.

2022-01-27 00:59 UTC, merged