Feat s3 transfermanager
aws/aws-sdk-kotlin pull request #643
Opened 2022-06-29 15:32 UTC by LDsBF

## Issue \#

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-29 21:01 UTC, LDsBF commented on hlls/s3-transfermanager/build.gradle.kts
>                  implementation("aws.smithy.kotlin:logging:$smithyKotlinVersion")
I try to delete commonTest part's smithy-kotlin dependency and successfully pass tests, I will delete underneath dependency

2022-06-29 21:26 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +        val localFile = File(from) // replace this with a real path
I forgot to erase it, sorry

2022-06-29 21:38 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +                val chunkSize = 8000000L     // chunk size in bytes
Ok, I will put it into S3TransferManagerConfig together with S3Client

2022-06-29 21:39 UTC, lucix-aws requested changes

2022-06-29 21:39 UTC, lucix-aws commented on hlls/gradle.properties
> +releasedSmithyVersion=0.+
(`ktlintFormat` _should_ handle this when you run it)

2022-06-29 21:39 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +        val s3 = S3Client.fromEnvironment {
Per Ian's comment above, remove this client instantiation once it's passed in from config.

2022-06-29 21:39 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +    override suspend fun upload(from: String, to: S3Uri, progressListener: ProgressListener?): Operation {
Additionally, I'd split between file and directory uploads - the main bulk of this function as you've written it is the split between those two routes.

2022-06-29 21:39 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +                for (i in 0 until subFiles.size) {
Prefer `forEach` over `for` like above.

2022-06-29 21:39 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            if (subFiles.size != 0) {
You don't need this check. A `for`/`forEach` is a no-op if the collection doesn't have any items.

2022-06-29 21:39 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +                    var subFrom = "" + from // next level recursion's from
I'm pretty sure this is obviated by Ian's `Paths` suggestion below, but FYI, this is a frivolous addition - a string plus an empty string is just equal to itself ie.
```kotlin
var subFrom = "" + from
var subFrom2 = from
// these two strings will be the same
```

2022-06-29 21:39 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/data/S3Uri.kt
> +                                     ) {}
Agreed on extracting parsing, but I think we should do it via an overload-style method instead (like we did with `Document`), so
```kotlin
data class S3Uri(val bucket: String, val key: String)

fun S3Uri(path: String): S3Uri {
  // parse, validate
  return S3Uri(/* ... */)
}

2022-06-29 21:39 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/data/Progress.kt
> +) {}
(pretty sure `ktlintFormat` will resolve it, don't quote me on that, tl;dr just run it before you start addressing format issues individually)

2022-06-29 22:05 UTC, ianbotsf commented on hlls/gradle.properties
> +releasedSmithyVersion=0.+
Unfortunately I don't think our lint configuration scans **.properties** files. The best way I've found to catch these kind of problems outside of **.kt** files is by looking at the diffs in the GItHub UI.

2022-06-29 22:17 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/data/S3Uri.kt
> +                                     ) {}
Oh yes you're right, that's a better solution.

2022-06-30 13:22 UTC, aajtodd reviewed
This is a great start. I've added a few comments in addition to what has already been called out.

2022-06-30 13:22 UTC, aajtodd commented on hlls/s3-transfermanager/build.gradle.kts
> +tasks.named<Test>("jvmTest") {
this shouldn't be necessary, it's already applied via `jvm.gradle` in the parent `hlls/build.gradle.kts` file

2022-06-30 13:22 UTC, aajtodd commented on hlls/s3-transfermanager/build.gradle.kts
> +            dependencies {
Almost all of these shouldn't be necessary as they are applied as part of the parent `hlls/build.gradle.kts` file via the platform `common.gradle` and `jvm.gradle` build files.

The only dependencies you should need to add are the ones unique to this project (e.g. `aws-runtime:testing`).

2022-06-30 13:22 UTC, aajtodd commented on hlls/s3-transfermanager/build.gradle.kts
> +                runtimeOnly("org.junit.jupiter:junit-jupiter-engine:5.4.2")
this is a JVM specific dependency as well (but shouldn't even need included here, see my other comment)

2022-06-30 13:22 UTC, aajtodd commented on hlls/s3-transfermanager/build.gradle.kts
> +                implementation("aws.smithy.kotlin:smithy-test:0.10.2")
why are we including `smithy-test`, it is for generated unit tests usually

2022-06-30 13:22 UTC, aajtodd commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +import S3TransferManager
this import is unnecessary, they are in the same package (or rather will be when you fix the package directive as Ian pointed out)

2022-06-30 13:22 UTC, aajtodd commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/handler/DefaultOperation.kt
> +public class DefaultOperation: Operation {
this shouldn't be public, `Operation` is an interface and this is an implementation detail.

2022-06-30 13:22 UTC, aajtodd commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +public class DefaultS3TransferManager(): S3TransferManager {
This also shouldn't be `public`

2022-06-30 13:22 UTC, aajtodd commented on hlls/s3-transfermanager/jvm/test/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManagerTest.kt
> +        }
Use the latter (`assertFailsWith`) as it is more clear the intent.

2022-06-30 15:07 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +public class DefaultS3TransferManager(): S3TransferManager {
To clarify, I believe it should be `internal` rather than `public`/`private`.

2022-06-30 17:03 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/data/S3Uri.kt
> +                                     ) {}
I will add more test case for invalid format check

2022-07-01 07:14 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +    override suspend fun upload(from: String, to: S3Uri, progressListener: ProgressListener?): Operation {
I split single file logic to private helper function, but keep directory logic within upload() since it need to recursively judge whether the current path points to a file or directory.

2022-07-01 20:20 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +    override suspend fun upload(from: String, to: S3Uri, progressListener: ProgressListener?): Operation {
Now I add another uploadDirectory() method separately :)

2022-07-06 17:37 UTC, LDsBF commented on hlls/s3-transfermanager/build.gradle.kts
> +                implementation("aws.smithy.kotlin:smithy-test:0.10.2")
I have just added some unit test for transfer manager

2022-07-06 22:27 UTC, ianbotsf requested changes
Lots of great improvements here and I think we're pretty close to having this ready to merge. Hopefully this is the last round of feedback necessary.

2022-07-06 22:27 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +        return operation
**Comment**: It looks like your helper methods return `Operation` already. There's no reason to create another new `Operation` in this outer method when you can just return the ones from the helper methods:

```kotlin
return if (localFile.isFile()) {
    uploadFile(localFile, to)
} else if (localFile.isDirectory()) {
    uploadDirectory(from, to, progressListener)
} else {
    throw IllegalArgumentException("From path is invalid")
}
```

2022-07-06 22:27 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
>          }
**Comment**: Same comment as above...just return the result from these methods instead of creating a new `Operation`.

2022-07-06 22:27 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +        val localFile = File(from)
**Comment**: It looks like `uploadDirectory` needs a `File` object but takes a `from: String` as a parameter. You've already got a `File` in the calling method, though, so just pass that instead of the string.

2022-07-06 22:27 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +        subFiles.forEachIndexed { index, subFile ->
**Comment**: It looks like `index` is unused here so you can replace `forEachIndexed` with a regular `forEach`.

2022-07-06 22:27 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/S3TransferManager.kt
> +        }
**Comment**: `fromEnvironment` implies we're loading something from the user's profile, environment variables, system properties, etc. Here, we're not doing that. It's effectively the same as the first `invoke` overload so we should just remove it.

2022-07-06 22:27 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/data/S3Uri.kt
> +    require(key.isNotEmpty()) { "s3Path input is invalid" }
**Comment**: We can help users debug by making the error messages more explicit. For each error case, let's indicate what went wrong so that it's easier to fix. For example, ``"s3Path input is valid: URIs must start with `s3://`"``.

2022-07-06 22:27 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/handler/PausedOperation.kt
> +import java.util.*
**Comment**: We generally shouldn't import `*` except in rare cases in test code (e.g., importing all of the `assert*` methods or something). Let's replace this with the specific types we need (which I believe is just `BitSet`).

2022-07-06 22:27 UTC, ianbotsf commented on services/s3/e2eTest/S3IntegrationTest.kt
> +/* * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved. * SPDX-License-Identifier: Apache-2.0. */package aws.sdk.kotlin.e2etestimport aws.sdk.kotlin.services.s3.S3Clientimport
**Comment**: Looks like something got messed up here. We shouldn't need any changes to **services/s3/e2eTest/S3IntegrationTest.kt** so let's make sure to revert this.

2022-07-06 22:43 UTC, LDsBF commented on hlls/s3-transfermanager/build.gradle.kts
> +                runtimeOnly("org.junit.jupiter:junit-jupiter-engine:$junitVersion")
After removing them, in unit test of DefaultS3TransferManagerTest, kotlinx.coroutines.test.runTest import can not be figured out :(

2022-07-06 22:49 UTC, LDsBF commented on hlls/s3-transfermanager/build.gradle.kts
> +}
I have deleted them in latest code

2022-07-06 22:53 UTC, LDsBF commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +            s3 = runBlocking {
But once I delete the inner one, compile error occurs saying that "Suspension functions can be called only within coroutine body"

2022-07-06 23:44 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/S3TransferManager.kt
> +        }
I remove if and find I can not configure my S3TransferManager with invoke, it seems block can just be recognized by fromEnvironment suspend fun :(

2022-07-06 23:50 UTC, LDsBF commented on services/s3/e2eTest/S3IntegrationTest.kt
> +/* * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved. * SPDX-License-Identifier: Apache-2.0. */package aws.sdk.kotlin.e2etestimport aws.sdk.kotlin.services.s3.S3Clientimport
I don't remember I have changed this test, I will copy and paste it from main branch

2022-07-07 02:48 UTC, ianbotsf commented on hlls/s3-transfermanager/build.gradle.kts
> +                runtimeOnly("org.junit.jupiter:junit-jupiter-engine:$junitVersion")
OK, leave them for now. We'll figure it out later.

2022-07-07 02:49 UTC, ianbotsf commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +            s3 = runBlocking {
Oh right because `fromEnvironment` isn't `suspend`. Okay, it's fine for now then.

2022-07-07 02:52 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/S3TransferManager.kt
> +        }
You mean in your integration test you can no longer `S3TransferManager.fromEnvironment { ... }`? Right, once we get rid of that method you'd need to invoke instead. In Kotlin, that's the same as using it like a method so it'd simplify to `S3TransferManager { ... }`.

2022-07-07 03:00 UTC, ianbotsf commented on services/s3/e2eTest/S3IntegrationTest.kt
> +/* * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved. * SPDX-License-Identifier: Apache-2.0. */package aws.sdk.kotlin.e2etestimport aws.sdk.kotlin.services.s3.S3Clientimport
Must've gotten accidentally messed up by the IDE. Looks like it replaced all the line endings or something. Copy-paste works or `git checkout services/s3/e2eTest/S3IntegrationTest.kt` would do it.

2022-07-07 18:27 UTC, ianbotsf requested changes
Looks mostly good. I'm seeing errors when I try to check out and build the project. There are some buildfile errors called out separately and also several warnings generated about visibility and unused variables.

For example:

```
> Task :hlls:s3-transfermanager:compileKotlinJvm
e: warnings found and -Werror specified
w: /local/home/issmith/workplace/s3tm/aws-sdk-kotlin/hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt: (127, 17): Variable 'subOperation' is never used
w: /local/home/issmith/workplace/s3tm/aws-sdk-kotlin/hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/S3TransferManager.kt: (21, 5): Visibility must be specified in explicit API mode
w: /local/home/issmith/workplace/s3tm/aws-sdk-kotlin/hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/S3TransferManager.kt: (23, 5): Visibility must be specified in explicit API mode
w: /local/home/issmith/workplace/s3tm/aws-sdk-kotlin/hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/S3TransferManager.kt: (24, 9): Visibility must be specified in explicit API mode
w: /local/home/issmith/workplace/s3tm/aws-sdk-kotlin/hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/S3TransferManager.kt: (29, 9): Visibility must be specified in explicit API mode
w: /local/home/issmith/workplace/s3tm/aws-sdk-kotlin/hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/S3TransferManager.kt: (31, 9): Visibility must be specified in explicit API mode
...
```

Can you please run `./gradlew build` and fix the errors?

2022-07-08 17:32 UTC, ianbotsf approved these changes
Great, this now builds for me completely so I think we're good to go! This PR is approved and I'll complete the merge into the **aws-sdk-kotlin** repo.

Congratulations on getting your first PR through approval!

2022-07-08 17:37 UTC, lucix-aws approved these changes

2022-07-08 18:09 UTC, merged