Add first version S3 transfer manager download feature, may include some import* issue caused by new incline function sorry :(
aws/aws-sdk-kotlin pull request #656
Opened 2022-07-18 05:40 UTC by LDsBF

## Issue \#

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-18 17:58 UTC, ianbotsf requested changes

2022-07-18 17:58 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +                }
**Comment**: We should generally catch the most specific exception we can. In this case, we specifically want to handle a `NotFound` exception. As written, this will catch (and ignore) other exceptions like authentication problems, filesystem errors, etc.

2022-07-18 17:58 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            }
**Correctness**: This code will download a file and then continue on to the rest of the method below, including attempting to download a directory. I think we're missing a `return` here or a better structuring of `if` branches.

2022-07-18 17:58 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            }
**Nit**: This doesn't need to be a `var`:

```kotlin
val keyPrefix = if (keyPrefix.endsWith('/')) keyPrefix else keyPrefix + '/'
```

2022-07-18 17:58 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            }
**Correctness**: Calling `toList()` on a `Flow` suspends until all of the items are collected. In our case, that means repeatedly calling `listObjectsV2` for subsequent pages until no more are found. This could involve dozens or hundreds of calls so we shouldn't do that here.

Instead, what we really want to know is whether there's at least one page with at least one item in the `contents`. We can accomplish that by:

```kotlin
if (response.firstOrNull()?.contents?.isNotEmpty() == true) {
    ...
}
```

The `firstOrNull` call gets the very first page or null if there are no pages. The `isNotEmpty()` call is necessary because the `listObjectsV2` API may return a response with 0 items in it. In that case, `contents` wouldn't be null.

2022-07-18 17:58 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            }
**Comment**: This code works but it could be better organized to take advantage of flows. We don't need to process each page of results individually in `downloadDirectory` (which doesn't download _a directory_ but actually processes _a page_). Instead we can flat map the flow into the individual list of objects and process each of those directly:

```kotlin
response // Flow<ListObjectsV2Response>, a collection of pages
    .transform { it.contents?.forEach { obj -> emit(obj) } } // Flow<Object>, a collection of individual objects
    .collect { obj ->
        val s3Uri = S3Uri(from.bucket, obj.key) // Form a new S3Uri out of the requested bucket and the object key
        val keySuffix =  obj.key.substringAfter(keyPrefix) // The unique part of the key after the prefix
        val subPath = Paths.get(to, keySuffix).toString() // Concat the original `to` with the key to get a destination file
        downloadFile(s3Uri, subPath)
    }
```

(Comments added for explanation. They're not necessary to duplicate in the actual PR.)

Note that this code assumes that `downloadFile` is correctly creating destination directories. See comment below.

2022-07-18 17:58 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +                    Files.createDirectories(Paths.get(to))
**Comment**: Given that this needs to happen for every downloaded file, it probably belongs in the `downloadFile` method instead.

2022-07-18 17:58 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            }
**Correctness**: The `downloadFile` method itself should be creating subdirectories as necessary before downloading the file:

```kotlin
s3.getObject(request) { resp ->
    val toPath = Paths.get(to)
    Files.createDirectories(toPath.parent)
    resp.body?.writeToFile(toPath)
}
```

2022-07-18 17:58 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            }
**Nit**: We never use the value `rc` so there's no reason to capture it as a `val`.

2022-07-18 18:08 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            if (subFrom != null) {
Let's return early (or filter these items we want to skip out first) instead of wrapping the whole loop body.

eg.
```kotlin
val subFrom = response.prefix?.let { it1 -> it.key?.substringAfter(it1) }
if (subFrom == null) {
    continue
}

// rest of loop body
```

2022-07-18 18:12 UTC, LDsBF commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerTestUtils.kt
> +import aws.sdk.kotlin.services.s3.*
I try to add their import one by one, but compiler automatically merge them into single * import when I added too many separate import lol. I will separate their import

2022-07-18 18:23 UTC, ianbotsf commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerTestUtils.kt
> +import aws.sdk.kotlin.services.s3.*
That isn't the compiler, it's IntelliJ. You can configure the import settings under **File** → **Settings** → **Editor** → **Code Style** → **Kotlin** → **Imports**.

2022-07-18 20:33 UTC, LDsBF commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +        assertNotNull(operation, "The transfer manager doesn't tackle directory download")
I just added a `operation.await()` after `assertNotNull` to wait for async download to complete in case of any coroutine's exception or error. Not sure whether it can solve.

2022-07-18 20:37 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +                } catch (_: Exception) {
This `try {} catch () {}` is used to catch `NotFound` exception from `s3.headObject`, which throw that exceotion when no object with given bucket/key is found. Since we need to continue following s3 key prefix directory searching, `IllegalArgumentException` will be thrown later if the key refers to nothing.

2022-07-19 18:44 UTC, ianbotsf commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +        operation.await()
**Question**: Does this work consistently? The `upload` operation is asynchronous too so it's possible for the download to begin or even complete before the upload is completed. We probably should `await` the completion of the upload before we begin downloading.

2022-07-19 18:44 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
>              }
**Comment**: Nice!

2022-07-19 18:46 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
>                  }
**Correctness**: We should move this `catch` to just surround the `headObject` call. We want to silently ignore failures there but not in any of our subsequent code.

2022-07-19 18:47 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
>              }
**Comment**: The only place that we set `validFrom` before this `if` block is when we have a file to download. We should just `return` immediately after `downloadFile` and not bother with `validFrom`.

2022-07-19 18:50 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            }
Did you have a chance to look into this suggestion? It may simplify the code but I'm not sure if it covers every case or if there's bugs in it.

2022-07-19 18:50 UTC, LDsBF commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +        operation.await()
agree

2022-07-19 21:55 UTC, ianbotsf reviewed
I like how much cleaner this is now that `objectExists` is a separate function! Great job!

Did you see [my comment about flow transformation yet](https://github.com/awslabs/aws-sdk-kotlin/pull/656#discussion_r923655681)? Have you had a chance to play with that?

2022-07-19 21:55 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            println("Continue!")
**Nit**: Let's not commit `println`s in business logic.

2022-07-19 22:19 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +    private suspend fun objectExists(s3Uri: S3Uri): Boolean {
No, I delete it and everything still works

2022-07-20 16:16 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +                    }
**Comment**: I believe that `key`'s nullability is a limitation of our codegen and not an actual possibility in responses from the service (at least, I don't understand what an object with a null key would mean semantically). I suggest you non-null assert the key inside this block and then remove the null checking elsewhere.

2022-07-20 17:19 UTC, ianbotsf approved these changes

2022-07-20 20:25 UTC, lucix-aws approved these changes

2022-07-20 20:25 UTC, lucix-aws commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +        operation = s3TransferManager.download(s3Uri, testDirectory.toString())
I'm still not a huge fan of these tests because they're not really verifying the end-to-end behavior here. Sure, you're calling upload and download, and I assume the methods execute, but we should verify that the contents we upload are really there in s3, and the contents we download are on the filesystem how we expect.

2022-07-20 20:31 UTC, LDsBF commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +        operation = s3TransferManager.download(s3Uri, testDirectory.toString())
I will add `headObject()` amd `FIle(downloadedFile)`to test them in next PR

2022-07-20 20:40 UTC, merged