Add more logic of multipart download and e2e tests
aws/aws-sdk-kotlin pull request #661
Opened 2022-07-25 06:50 UTC by LDsBF

## Issue \#

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-25 17:24 UTC, lucix-aws requested changes

2022-07-25 17:24 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +    private suspend fun headObject(s3Uri: S3Uri): HeadObjectResponse? =
This probably makes more sense to exist as an extension method on `S3Client`, which basically overloads `headObject` to take an `S3Uri`

ie.
```kotlin
// "headObjectOrNull" because it wraps the not-found exception logic to return null
// when the object doesn't exist - this is the "idiomatic" standard for
// "get-or-default"-type checks in kotlin
private suspend fun S3Client.headObjectOrNull(uri: S3Uri): HeadObjectResponse? {
    // as you have it now
}

2022-07-25 17:24 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            if (!from.key.endsWith('/')) {
Not sure this needed to change? I see that you changed your function to check for whether an object exists, but even so I'm pretty sure you can just do
```kotlin
if (!from.key.endsWith('/') && headObject(from) != null) {
    // ...
}
```

2022-07-25 17:24 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +                    response != null -> {
Pretty sure this will go away based on the comment right above this one, but a `when` with a single outcome is basically just an `if` and should be written that way.

2022-07-25 17:24 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +        when {
This might go away, but for what it's worth, a `when` with one outcome and an `else` is basically just an `if`/`else` and should be written that way.

2022-07-25 17:24 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +        try {
Do we need this `try`/`finally' for anything? The latter's block is empty.

2022-07-25 17:24 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +        when {
This check may not be necessary.

Theoretically, if `fileSize <= config.chunkSize`, `downloadFileParts` should still be usable - it would just only map out to a single `downloadFilePart` call internally.

2022-07-25 17:31 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/test/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManagerTest.kt
> +//        coEvery {
I tried to fix such unit test last week but still had some error while mocking the inline request and response, I will discuss with Ian and try to configure this week, sorry :(

2022-07-25 18:57 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            if (!from.key.endsWith('/')) {
If we use such `&&` here, we need to get `HeadObjectResponse` later by calling the `headObject()` again. I just think it's better to decrease reading from S3Client.

2022-07-25 18:57 UTC, ianbotsf commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +        assert(listObjectsResponse.contents!!.isNotEmpty())
Agreed. I'll also mention that kotlin-test has more expressive assertions that we should use instead of the language-level `assert`. We should use something more expressive like:

```kotlin
val contents = assertNotNull(listObjectsResponse.contents) // This handles the `!!` part for you
assertFalse(contents.isEmpty) // This captures nicely the semantics we want to convey
```

2022-07-25 18:58 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +                    response != null -> {
I will change that, sometimes confused about how to choose `if` and `when` lol. Now I know to use `if ` for just single condition judge :)

2022-07-25 19:03 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            if (!from.key.endsWith('/')) {
In both versions of the code, you'd only make the `headObject` call if the first part of the expression was `true` (`!from.key.endsWith('/')`) because of [short-circuiting](https://en.wikipedia.org/wiki/Short-circuit_evaluation). Most (if not all?) languages implement this kind of behavior, including Kotlin.

2022-07-25 19:11 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            if (!from.key.endsWith('/')) {
Ok most wikipedia pages on programming/technical topics are pretty horrendous to read and that one is no exception, so to clarify:

For any given boolean expression, say `X && Y && Z`, languages will stop evaluating the expression at the first point that they can logically determine the result.

So in the above- if X was true, and Y was false, the truthiness of Z would not be evaluated, since the overall expression is only true if ALL of its operands are true. Obviously this is one example and this kind of shortcut can apply to infinitely large/complex expressions and with the or / `||` operator as well, I chose an example that matches closest to what you've done in your code.

So given that short-circuiting is a thing, the following two snippets are programmatically the exact same, in the sense that the function in the expression is only evaluated if `x > 5`.

```kotlin
if (x > 5 && extremelyExpensiveBooleanFunctionThatTakesFiveMinutesToCompute()) {
  // ...
}
```
```kotlin
if (x > 5) {
  if (extremelyExpensiveBooleanFunctionThatTakesFiveMinutesToCompute()) {
    // ...
  }
}
```

2022-07-25 19:12 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            if (!from.key.endsWith('/')) {
Yep I know that from Java, but I think we need `response.contentLength` in this block, so I just wonder how to get that `headObjectResponse` later without calling `headObject()` again. If I write something like `response = headObject()` within upper `if`, will Kotlin directly judge the `=` operation to be `true`?

2022-07-25 19:49 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            if (!from.key.endsWith('/')) {
I think you're getting at a different concern here, which is how you can avoid calling `headObject` more than you need to. It's a valid concern. All I'm pointing out here is that in this particular change, moving the `headObject` call inside this one particular if block wasn't changing anything.

Given that you need the results of `headObject` elsewhere, you probably just want to call it and store the value further up in your method.

2022-07-25 20:18 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            if (!from.key.endsWith('/')) {
Make sense, I will just merge these two `if` and call `headObject` again if I need its return value.

2022-07-25 20:33 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +        try {
I did try to move it, but seems like `try` must be followed by at least one from `catch`/`finally` to deal with possible exception. I referred to this block from Java v1's S3 transfer manager, within which they wrote 
`finally {
            IOUtils.closeQuietly(objectContent, LOG);
            IOUtils.closeQuietly(randomAccessFile, LOG);
            IOUtils.closeQuietly(channel, LOG);
 }`
I'm not quite sure if we need to also close ``randomAccessFIle`/`channel` after downloading :(

2022-07-25 20:49 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +        when {
Absolutely, since `S3Client` only has `getObject()` for single/multipart download instead of `uploadPart()` for upload operation. I will merge both cases to single `downloadFilePart`, thx!

2022-07-25 22:35 UTC, LDsBF commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +                testUploadDirectory.toFile().delete()
I should consider such design earlier, my laziness... Many thanks!

2022-07-26 21:58 UTC, lucix-aws requested changes

2022-07-26 21:58 UTC, lucix-aws commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +        assertTrue(checkUpload(testLargeFile, toUri))
I was thinking about this some more, and since your upload/download code is explicitly reconstructing the file out of smaller parts (ie. its logic IS responsible for the final contents of the file in a non-trivial way), we should probably include verifying that the contents of the file are correct as well for the "large file" tests only.

2022-07-26 21:58 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +        val randomAccessFile = RandomAccessFile(localFile, "rw")
Missed this on the first pass.

We shouldn't need this `RandomAccessFile` mechanism. You should just be able to get an `SdkByteWriteChannel` from the file object you create outside this method, and call multiple writes to it with each of your downloaded chunks. That would also allow you to get rid of having to pass and return the `position` value in order to continuously create and seek on the channel.

My guess is that making the switch to write channel will pretty much get rid of the need for this helper method as well:

```kotlin
// ... get SdkByteWriteChannel for target file
val objectContent = resp.body
if (objectContent != null) {
  // get SdkByteReadChannel from ByteStream, write it to write channel
}

2022-07-26 21:58 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +                s3.getObject(request) { resp ->
Missed this on the first pass.

I don't think we're getting the full benefit of doing chunked downloads unless we're doing them in parallel. As it's written AFAIK the only thing we're really avoiding is potentially timing out on big files.

I think doing that parallelization is almost certainly a `# FUTURE` though, I don't really want to blow up scope on you here since that change would be a bit more involved, and since I'm pretty sure we didn't do parallel chunked uploading.

2022-07-26 21:58 UTC, lucix-aws commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +            else -> return true // there might be DS data that doesn't affect test
Is this ever actually hit? Not sure I understand the comment.

2022-07-26 21:58 UTC, lucix-aws commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +                return s3TransferManager.config.s3.headObjectOrNull(to) != null
We should check that the names match as well.

2022-07-26 21:58 UTC, lucix-aws commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +                    checkResult = false
Couldn't we just `return false` out of the overall method right here?

2022-07-26 22:00 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +        val randomAccessFile = RandomAccessFile(localFile, "rw")
Also, very minor, we don't really need the temporary `objectContent`. You can just reference `resp.body` directly.

2022-07-26 22:06 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +                s3.getObject(request) { resp ->
The main reason to do chunked downloads is independent of parallelism—it's to do with providing timely status updates via the progress listeners. If we download a massive file in a single chunk, the listener would only get one status update. This way, we provide updates every _n_ bytes which allows for things like filling a progress bar, providing time estimates, etc.

Parallelism is a nice-to-have (assuming it actually improves performance, that may be a lot of file locking in the OS).

2022-07-26 22:10 UTC, LDsBF commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +    private fun deleteFiles(file: File) {
Perhaps I should consider whether it's better to append some helper function as class extension function in later design, good concept :)

2022-07-26 22:19 UTC, LDsBF commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +        testUploadDirectory = Files.createTempDirectory(dir, "testUploadDirectory")
I think I understand what you want, but in `testDownload()` case, `testUploadDirectory` is just used to create local temp files to upload for later downloading test. I will try to remove `@BeforeEach` / `@AfterEach` annotation and try to call them only when needed.

2022-07-26 22:42 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            if (!from.key.endsWith('/') && s3.headObjectOrNull(from) != null) {
Don't worry, I have reverted it to extended function's chain `if` code

2022-07-26 22:48 UTC, LDsBF commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +        assertTrue(checkUpload(testLargeFile, toUri))
So for large file, we should check local and S3 files' each chunk's ByteStream and validate if they are the same?

2022-07-26 23:02 UTC, LDsBF commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +            else -> return true // there might be DS data that doesn't affect test
I used to discuss with Ian about that for `upload()`, some file is neither `isFile` nor `isDirectory`. Since we don't care about their upload, in this check function, I just set it to return true.

2022-07-26 23:37 UTC, LDsBF commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +                return s3TransferManager.config.s3.headObjectOrNull(to) != null
In `upload()` and `download()` API, file/object is uploaded/downloaded with the same name mutually (under given local directory name and key prefix directory). Therefore, at the end of `testUpload()`, when we call `checkUpload(testUploadDirectory.toFile(), toUri)`, `toUri` just refers to our upload target key prefix directory when we call `s3TransferManager.upload(testUploadDirectory.toString(), toUri)`, so all `subTo` 's `subKey` is concatenated from that key prefix and local file/directory name, and the result of heading them automatically validate the uploaded objects' name matches local file name, I think :)

2022-07-26 23:40 UTC, LDsBF commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +                    checkResult = false
I tried but compile error shows `'return' is not allowed here`, seems like collect doesn't allow immediate return like java :(

2022-07-26 23:54 UTC, LDsBF commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +        testUploadDirectory = Files.createTempDirectory(dir, "testUploadDirectory")
For download tests, `testUploadDirectory` should exist so that S3 objects can be uploaded first and then to be downloaded. I'm not sure whether we should prepare a `testUploadDirectory` / `testDownloadDirectory` for each test case separately to decrease our code amount or specify each case's test directory creation inside their own block but with more code.

2022-07-27 07:05 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            val byteArray = objectContent.toByteArray()
But when I checked `SdkByteWriteChannel` I found both `writeFully` and `writeAvailable` accept `src: ByteArray` as parameter so I'm confused whether to convert `ByteStream` to `ByteArray`. Additionally, for `SdkByteReadChannel`, it can be obtained from `ByteStram` by implementing `OneShotStream` or `ReplayableStream`, but for their example code, I just see one `FileContent` class but it just constructs using `File` insteand of `ByteStream`. So is there any more explaination about that guess :)

2022-07-27 13:52 UTC, lucix-aws commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +                return s3TransferManager.config.s3.headObjectOrNull(to) != null
Oh you're not wrong. `headObject`'s key will have the filename. I'm silly.

2022-07-27 13:53 UTC, lucix-aws commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +        assertTrue(checkUpload(testLargeFile, toUri))
That's right.

2022-07-27 14:07 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            val byteArray = objectContent.toByteArray()
Yeah I see the confusion on `writeFully`/`writeAvailable`. The method to write a read channel to a write channel is actually exposed as `SdkByteReadChannel.copyTo`. FWIW that seems like an API miss for us and we should probably add an extension on write channel that takes a read channel.

`ByteStream` like you said will have an underlying read channel when it's either implemented by `OneShotStream` or `ReplayableStream`. You'd have to write a utility to pull out the channel or throw if it's implemented by `Buffer`. Again this seems like something we should really be directly supporting such that customers can get at these channels and use them however they need to.

I'm working on a snippet that I'll post in a second here.

2022-07-27 14:51 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            val byteArray = objectContent.toByteArray()
Here's a sample of one write channel for writing two parts of an 8-byte file.

```kotlin
fun ByteStream.toReadChannel(): SdkByteReadChannel =
    when (this) {
        is ByteStream.OneShotStream -> readFrom()
        is ByteStream.ReplayableStream -> newReader()
        is ByteStream.Buffer -> TODO()
    }

// pretty sure the hll project is set up to not require this
@OptIn(InternalApi::class)
suspend fun writeABunchOfStreams() {
    val f = File("./tmp")
    val writeChannel = f.writeChannel()

    S3Client.fromEnvironment().apply {
        getObject(GetObjectRequest {
            bucket = "buckettestdgttxcq"
            key = "test.txt"
            range = "bytes=0-3"
        }) {
            it.body?.toReadChannel()?.copyTo(writeChannel, close = false)
        }
        getObject(GetObjectRequest {
            bucket = "buckettestdgttxcq"
            key = "test.txt"
            range = "bytes=4-7"
        }) {
            it.body?.toReadChannel()?.copyTo(writeChannel, close = false)
        }
    }

    // you'll need to ensure the write channel is closed, either on the final write call or manually after all of them
}
```

2022-07-27 15:09 UTC, lucix-aws commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +        testUploadDirectory = Files.createTempDirectory(dir, "testUploadDirectory")
Yeah, ideally the "precondition" for the download test is that the test data to be downloaded exists on S3 and your local file environment is blank.

The reverse goes for upload - the upload directory should be there, and the bucket should be blank.

2022-07-27 17:27 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            val byteArray = objectContent.toByteArray()
Seems like `@OptIn(InternalApi::class)` can not be removed for `hlls`, but other design just works. Thanks for instruction :)

2022-07-28 20:24 UTC, lucix-aws commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +                    resp.body?.toReadChannel()?.copyTo(writeChannel, close = false)
love it

2022-07-28 20:25 UTC, lucix-aws approved these changes

2022-07-29 17:01 UTC, ianbotsf approved these changes
I'm approving this PR for now with the comments below. Please follow up on these cleanups in your next PR!

2022-07-29 17:01 UTC, merged