Feat s3 transfermanager progressListener feature
aws/aws-sdk-kotlin pull request #670
Opened 2022-08-05 22:10 UTC by LDsBF

## Issue \#

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-05 23:09 UTC, ianbotsf requested changes
This is a good start so far. I've left comments on the business logic but I think they'll require large enough changes that I'm ignoring the tests for now. I'll take a deeper look at them once we get the business logic closer to correct.

2022-08-05 23:09 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +}
**Style**: This **DefaultS3TransferManager.kt** file is over 500 lines now—too long. Let's start pulling functionality out into other files to make it easier to read this file.

I suggest that all of your progress enumerating and updating should live outside this class. You may also be able to simplify your call patterns by having a single object to manage progress updates:

```kotlin
data class ProgressUpdater(val progress: Progress, val listener: ProgressListener) {
    fun enumerateProgress(fromFile: File)
    fun enumerateProgress(fromObjects: Flow<Object>)
    private fun addTotalProgress(bytes: Long, chunks: Long) // No longer needs to be public, it's just a helper method
    fun addFilesTransferred(num: Long)
    fun addBytesChunksTransferred(byteLength: Long, chunkNum: Long)
}
```

Now your transfer manager code only has to pass around a single updater instead of the pair of `Progress` and `ProgressListener`. Bonus: you can make the `ProgressUpdater` nullable inside the transfer manager and only initialize it (and estimate progress) if the `ProgressListener` is nonnull.

2022-08-08 05:18 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +}
I should have thought about overload.... Thx a lot!

2022-08-08 19:13 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/handler/DefaultOperation.kt
> +//    get() = progress
Since I can not set its access modifier, I will just set it to `val` in `Operation` and remove repeat initialization function.

2022-08-09 14:58 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/handler/DefaultOperation.kt
> +//    get() = progress
You should be able to set [an access modifier on just the setter](https://kotlinlang.org/docs/properties.html#backing-fields:~:text=If%20you%20need%20to,has%20the%20default%20implementation):

```kotlin
override var progress: Progress = Progress()
    private set
```

2022-08-09 15:41 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/handler/DefaultOperation.kt
> +//    get() = progress
Seems like I can not set a `private set` inside `Operation` interface and inherit that private set publicity in `DefaultOperation` :(, I prefer to set `Progress` as a `val` and initialize it at the begining of initializing a `DefaultOperation`

2022-08-09 21:02 UTC, ianbotsf requested changes

2022-08-09 21:02 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/handler/ProgressUpdater.kt
> +        progress = newProgress
**Comment**: As I noted back up in `Progress`, this code should modify as part of the `copy` call and not by updating mutable fields. Also, the chunk calculation can be simplified to simple arithmetic:

```kotlin
val chunks = (size + chunkSize - 1) / chunkSize
progress = progress.copy(
    totalFilesToTransfer = progress.totalFilesToTransfer + 1,
    totalBytesToTransfer = progress.totalBytesToTransfer + size,
    totalChunksToTransfer = progress.totalChunksToTransfer + chunks,
)
```

2022-08-09 21:02 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/handler/ProgressUpdater.kt
> +    private fun addTotalProgress(size: Long, chunkSize: Long) {
**Nit**: `@InternalSdkApi` is unnecessary on `private` or `internal` methods.

2022-08-09 21:04 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +    private fun upload(progressUpdater: ProgressUpdater?, from: String, to: S3Uri): Operation {
I change their sequence just to avoid overload conflict lol. I will rename some intermediate helper function

2022-08-09 21:05 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/data/Progress.kt
> +        totalFilesToTransfer == filesTransferred && totalBytesToTransfer == bytesTransferred && totalChunksToTransfer == chunksTransferred && isDone
Just want to double check that every actual transfer variable is equal to corresponding total workload.

2022-08-09 21:17 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +    private fun upload(progressUpdater: ProgressUpdater?, from: String, to: S3Uri): Operation {
I actually _like_ that they have the same name. They perform the same logical function just with different parameters.

Why would these two signatures conflict? They take different parameter types:
* `upload(String, S3Uri, ProgressListener?)`
* `upload(String, S3Uri, ProgressUpdater?)`

This should always be resolvable by the compiler _unless_ called with an explicit, literal null:

```kotlin
upload("foo", S3Uri("bar", "baz"), null)
```

In the above case, the compiler can't know whether null is a `ProgressListener?` or a `ProgressUpdater?`. But your code shouldn't need to call `upload` with a literal null so I don't think it can be an issue. Am I missing something?

2022-08-09 22:24 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            }
Seems like `estimateProgress` call `onProgress` will be printed out later than other child coroutines' `onProgress()`, I will remove this call.

2022-08-09 22:33 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            }
Actually, I tried to merge similar progress update into a single API yesterday, but it seems single transfer and multi chunks transfer requires calling different update method call with different sequence, especially when `addFilesTransferred()` intercepts between other API. 
I will redesign an API.

2022-08-09 22:55 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            }
I prefer to remove estimate step's `onProgress()` since moving it inside `estimateProgressForDownload()` might cause this initial progress to be printed out later than other coroutine's `onProgress()`. Consider later possible implementation of `onProgress()`, perhaps it's better to erase this estimate function's `onProgress()` for both upload and download.

2022-08-09 23:11 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/data/Progress.kt
> +        totalFilesToTransfer == filesTransferred && totalBytesToTransfer == bytesTransferred && totalChunksToTransfer == chunksTransferred && isDone
Just want to make all `Progress` memeber field `internal` ..... I will move it back to where it was

2022-08-10 19:15 UTC, ianbotsf requested changes
**Comment**: I've started taking a look at the updated e2e test code and it's a little confusing for me to follow. It seems like we're verifying the correctness of `ProgressUpdater` by using another `ProgressUpdater` (e.g., in the `checkUploadProgress` method). If `ProgressUpdater` has bugs and estimates progress incorrectly, then your code would still pass right?

I believe it'd be better to specify explicit values we expect to see for these tests. Something like:

```kotlin
val operation = ...
operation.await()
assertTrue(operation.progress.isDone)
assertEquals(5, operation.progress.currentFiles)
assertEquals(10, operation.progress.currentChunks)
assertEquals(1_234_567, operation.progress.currentBytes)
```

2022-08-10 19:15 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/handler/ProgressUpdater.kt
> +    }
**Correctness**: These `estimate` methods need to call `onProgress`. Users should get an initial `onProgress` call where all the current values are 0 and the total values are set appropriately.

2022-08-10 19:15 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/handler/ProgressUpdater.kt
> +        }
**Correctness**: The `onProgress` invocation must happen outside of the mutex. Otherwise, slow or badly-behaved user code could prevent progress from being updated by other tasks (and thus, prevent any transfers from proceeding).

Note that just moving the call as-is outside to after the mutex won't be thread-safe. It risks using a value of `progress` that was updated by a different thread. it's important to ensure that you've got an up-to-date reference to `progress` outside of the mutex, which you can achieve by storing the result of the copy and passing it to the `onProgress` invocation:

```kotlin
val newProgress = mutex.withLock {
    val chunks = (byteLength + chunkSize - 1) / chunkSize
    val isDone = progress.filesTransferred + fileNum == progress.totalFilesToTransfer
    progress.copy(
        filesTransferred = progress.filesTransferred + fileNum,
        bytesTransferred = progress.bytesTransferred + byteLength,
        chunksTransferred = progress.chunksTransferred + chunks,
        isDone = isDone,
    ).also { progress = it }
}
progressListener.onProgress(newProgress)
```

2022-08-10 19:15 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/handler/ProgressUpdater.kt
> +            }
**Nit**: It's not necessary to copy twice. Simply precompute the value of `isDone` and pass it alongside all the other values you're updating.

2022-08-10 21:02 UTC, LDsBF commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
> +        val s3Uri = S3Uri(testBucket, "folder1/")
Those are some special case for `checkUploadProgress` logic. Since you suggest hard coding test progress judgement, I will try to remove them.

2022-08-11 16:11 UTC, ianbotsf requested changes
Things are looking pretty good here, I'd guess just a few more changes and we'll be ready to ship!

2022-08-11 21:35 UTC, ianbotsf requested changes

2022-08-11 21:35 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/handler/ProgressUpdater.kt
>  public data class ProgressUpdater(var progress: Progress, val progressListener: ProgressListener, val chunkSize: Long) {
**Nit**: Please make this class `internal` too.

2022-08-11 21:35 UTC, ianbotsf commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
>          }
**Correctness**: Let's not make the `onProgress` method `suspend`—that may place additional burdens on user code. Instead, this `TestingProgressListener` can use `runBlocking` around the mutex lock.

2022-08-11 22:08 UTC, ianbotsf approved these changes

2022-08-11 22:09 UTC, merged