Add unit test of S3TM
aws/aws-sdk-kotlin pull request #679
Opened 2022-08-15 21:31 UTC by LDsBF

## Issue \#

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-16 17:59 UTC, ianbotsf requested changes
Off to a fantastic start with these.

2022-08-16 17:59 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/test/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManagerTest.kt
> +    }
**Comment**: Nice! These are great helper functions that make your unit tests extra readable.

2022-08-16 17:59 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/test/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManagerTest.kt
> +            }
**Correctness**: Let's also verify that the part number is set correctly in `uploadPart`.

2022-08-16 17:59 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/test/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManagerTest.kt
> +            }
**Correctness**: Let's add expectations for the byte range in each of these `getObject` calls.

2022-08-16 18:05 UTC, LDsBF commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
>          }
I found it while designing unit test's resource management, it is defined by `org.jetbrains.kotlin:kotlin-stdlib:1.7.10`, I manual test it in e2e test and unit test and seems it works just like my previous `deleteRecursively` which can delete either single file or a directory, so I guess it's better to directly use kotlin's standard library.

2022-08-16 18:08 UTC, ianbotsf commented on hlls/s3-transfermanager/e2eTest/S3TransferManagerIntegrationTest.kt
>          }
Oh ha, I looked everywhere _except_ Kotlin's stdlib for this. Makes sense, definitely better to use a stdlib function!

2022-08-16 18:19 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/test/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManagerTest.kt
>      }
I checked Kotlin's official doc about example code of mocking an object. It shows that for JUnit5, after mocking object before each test either manually or via mock extension annotion and executing test case, `unmockkAll` is called to revert back mocked object and clean the mock environment. In order to separately manage each unit test case's mock resource, I just add `unmockkAll` after each case

2022-08-16 18:28 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/test/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManagerTest.kt
> +            }
I think it's better to `coVerify` each file's transfer separately while testing a directory transfer since they are asynchronously executed so there's always some special cases where files are not executed in expected order. I will modify all of such test code

2022-08-16 19:21 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/test/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManagerTest.kt
>      }
OK, I don't think that's necessary in this case. Because you're setting up your mocks with `@BeforeEach`, they'll get reinitialized before every test. Returning them to their default state after every test shouldn't be necessary and shouldn't have any effect on the tests themselves.

2022-08-16 19:22 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/test/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManagerTest.kt
>  @ExtendWith(MockKExtension::class)
**Comment**: The `MockKExtension` extension shouldn't be necessary because you're not using annotations to initialize your mocks (you're using imperative mocks in the `setUp` method which is cleaner IMO).

2022-08-17 20:01 UTC, ianbotsf requested changes

2022-08-17 20:01 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/test/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManagerTest.kt
> +    }
**Question**: Are these temp dirs/files being cleaned up? Or does every run (successful or not) create more and more garbage data and leave it behind?

2022-08-17 20:40 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/test/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManagerTest.kt
> +    }
I add `FIle.deleteRecursively()` at the end of each unit test case in a `try{} finally{}` 's `finally{}` block so that no matter we successfully pass the test or any exception is thrown, the created directory/files will be deleted recursively before exiting the test case. In actual test, both success and failure case won't leave garbage files.

2022-08-17 20:43 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/test/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManagerTest.kt
> +    }
Oh right of course. Sorry, I forgot about that.

2022-08-17 22:01 UTC, ianbotsf approved these changes

2022-08-17 22:01 UTC, merged