feat: enable retry configuration
aws/aws-sdk-kotlin pull request #702
Opened 2022-09-21 19:42 UTC by lauzadis

Enables configuration of the retry strategy (specifically, max attempts and retry mode) through environment variables, system properties, and AWS profile configuration.

## Issue \#

#486 

## Description of changes

This change is required to achieve feature parity with existing SDKs. It solves the problem of lacking user configuration for max attempts and retry mode. 

Currently, we only support `legacy` and `standard` retry modes (with `legacy` behaving equivalently to `standard`). Support for `adaptive` retry mode will be added in #701.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-21 20:41 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategy.kt
> +    if (maxAttempts < 1) {
Prefer `require(maxAttempts < 1)` { "max attempts was $maxAttempts but should be at least 1" }

Note that the type of exception thrown by `require` is an `IllegalArgumentException`.

2022-09-21 20:41 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategy.kt
> +    val maxAttempts: Int = (
You should be able to omit the type declaration here.

2022-09-21 20:41 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategy.kt
> +        ).toInt()
**Question**: Do we want to handle a type conversion failure here? Or just let it bubble?

2022-09-21 20:41 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategy.kt
> +    if (retryMode == "adaptive") {
We can make this more explicit with a `when` construct e.g.

(If you haven't come across it yet, `when` is kotlin's version of `switch`, and can be used as an expression as well as a freestanding statement like in other languages)

```kotlin
return when (retryMode) {
    "standard", "legacy" -> StandardRetryStrategy(/* ... */)
    "adaptive" -> throw NotImplementedError(/* ... */)
    else -> throw IllegalArgumentException(/* ... */)
}
```

2022-09-21 20:41 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategy.kt
> +        AwsSdkSetting.AwsMaxAttempts.resolve(platformProvider)
This expression is awkward. You should be able to simplify it by invoking `toInt()` directly on the retrieved `maxRetryAttempts` from profile, instead of string-ifying and then re-intifying the whole expression.

2022-09-21 20:41 UTC, lucix-aws commented on aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategyTest.kt
> +        assertThrows(UnsupportedOperationException::class.java) {
You can use `assertFailsWith<T: Exception>(...)` here (and in your other failure checks) rather than having to get at the class reference.

2022-09-21 20:41 UTC, lucix-aws commented on aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategyTest.kt
> +class ResolveRetryStrategyTest {
This is a comprehensive test suite, well done!

2022-09-21 20:44 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategy.kt
> +        throw UnsupportedOperationException("Retry mode $retryMode is not supported, should be one of: \"legacy\", \"standard\", \"adaptive\"")
Forgot this on the first pass, but let's use `IllegalArgumentException` here.

2022-09-21 20:46 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt
> +public val AwsProfile.maxRetryAttempts: String?
Consider having this extension handle the type cast. This is the first time we've referenced a non-string field here, AFAIK, so I'm curious what the others think.

2022-09-21 20:51 UTC, ianbotsf requested changes

2022-09-21 20:51 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategy.kt
> +    }
**Nit**: Support matching of non-lowercase values like `Standard` or `STANDARD`.

2022-09-21 20:51 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategy.kt
> +    }
**Correctness**: We don't support a "legacy" retry mode and we never will. If a user tries to configure a retry mode of "legacy" they should get an error message.

2022-09-21 20:51 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt
> +    get() = this["retry_mode"]
**Comment**: It feels odd to me to treat these values as strings when we know they shouldn't be. I see we haven't defined any non-string values from profile yet but I believe these could be the first.

I'd suggest playing with parsing a non-null string into an `Int`/`RetryMode` at this level, including throwing an error when the values are nonsensical.

2022-09-21 20:51 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AwsSdkSetting.kt
> +    public object AwsRetryMode : AwsSdkSetting<String>("AWS_RETRY_MODE", "aws.retryMode")
**Comment**: Same as in **AwsProfile.kt**—let's treat these as `Int`/`RetryMode` settings rather than strings.

2022-09-21 20:51 UTC, ianbotsf commented on aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategyTest.kt
> +            assertThrows(IllegalArgumentException::class.java) {
**Style**: There's a slightly nicer syntax for this directly in **kotlin-test**:

```kotlin
assertThrows<IllegalArgumentException> { ... }
```

2022-09-21 21:06 UTC, aajtodd reviewed
Nice work

2022-09-21 21:06 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategy.kt
> +    }
Well what if they share profiles between SDKs or switch from one SDK to another, etc? It seems reasonable to me to interpret `legacy` as `standard` for our SDK but I'm not opposed to throwing an error either 🤷

2022-09-21 21:06 UTC, aajtodd commented on aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategyTest.kt
> +            runBlocking {
I'm not sure this is necessary `runTest` provides a scope already and `assertThrows` should be inline IIRC. 

`runBlocking` shouldn't even work in `common`, it's not available on every platform, not sure why it works here

2022-09-21 21:10 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategy.kt
> +    }
+1 to what Aaron said, I thought we agreed this morning to treat `legacy` exactly like `standard`, but I'm also open to just throwing an error

2022-09-21 21:12 UTC, lauzadis commented on aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategyTest.kt
> +            runBlocking {
I was having trouble because `resolveRetryStrategy` is a suspending function, and I followed the solution here: https://github.com/junit-team/junit5/issues/1851

I'll see if the recommended `assertFailsWith<T: Exception>(...)` fixes this

2022-09-21 21:33 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategy.kt
> +    }
Ooh, that's an interesting possibility I did not consider. OK I can live with that, especially given the verbiage in the [generic SDK docs on retry behavior](https://docs.aws.amazon.com/sdkref/latest/guide/feature-retry-behavior.html). I withdraw my concern here.

2022-09-22 14:06 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategy.kt
> +        ).toInt()
I will handle type conversion failures at the AwsProfile / AwsSdkSetting level (throw an error when reading the values, instead of when trying to use them)

2022-09-22 17:24 UTC, lucix-aws approved these changes

2022-09-22 17:24 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt
> +        throw IllegalArgumentException("Failed to parse maxAttempts " + this["max_attempts"] + " as an integer", e)
I see you used the string interpolation feature elsewhere, you can do it with more complex statements if you wrap the expression in `{}`s:

```kotlin
throw IllegalArgumentException("Failed to parse maxAttempts ${this["max_attempts"]} as an int", e)
```

2022-09-22 17:24 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/retries/ResolveRetryStrategy.kt
> +    // resolve max attempts
**Nit**: I'm generally not a fan of shortform-type comments like this where it describes the behavior that's otherwise evident based on the code itself.

2022-09-22 17:54 UTC, ianbotsf approved these changes
Only minor issues left. Fix at least the **Nit** (consider the **Style**s optional) and ship.

2022-09-22 17:54 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AwsSdkSetting.kt
> +                }
**Style**: This works but relies on uppercasing, exception catching, and duplicating the values from the enum in a string. Consider:

```kotlin
RetryMode
    .values()
    .firstOrNull { it.name.equals(strValue, ignoreCase = true) }
    ?: throw IllegalArgumentException("Retry mode $strValue is not supported, should be one of: ${RetryMode.values().joinToString(", ")}"
```

2022-09-22 17:54 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AwsSdkSetting.kt
> +            }
**Comment**: I assumed there'd be an easy generic way to parse _any_ enum class but after trying several different implementations it seems it's not straightforward (even with reified generics). Alas, it seems we're stuck with separate branches for any future enum class.

2022-09-22 17:54 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt
> +        throw IllegalArgumentException("Failed to parse maxAttempts " + this["max_attempts"] + " as an integer", e)
**Style**: Consider using null coalescing instead of exception catching:

```kotlin
get() = this["max_attempts"]?.run { toIntOrNull() ?: throw IllegalArgumentException(...) }
```

2022-09-22 17:54 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/retries/RetryMode.kt
> +}
**Nit**: Please add KDocs.

2022-09-22 17:57 UTC, aajtodd approved these changes
Fix and ship!

2022-09-22 17:57 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt
> +        throw IllegalArgumentException("Failed to parse maxAttempts " + this["max_attempts"] + " as an integer", e)
We might consider `ConfigurationException` here

2022-09-22 17:57 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/retries/RetryMode.kt
> +public enum class RetryMode {
fix: missing documentation

2022-09-22 17:57 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AwsSdkSetting.kt
> +            RetryMode::class -> {
Currently all the other AwsSdkSettings are simple types and match what they are allowed to be in config/environment and later converted as necessary. I suppose this is fine though.

2022-09-22 23:36 UTC, merged