feat(rt): support static stability for IMDS credentials
aws/aws-sdk-kotlin pull request #719
Opened 2022-10-05 21:41 UTC by lauzadis

Adds support for static stability for IMDS credentials. 
Uses the `expireCredentialsAfter` time in CachedCredentialsProvider for credentials which have an expiration time set.

## Issue \#
#707
#718

## Description of changes
### \#707:

This change is required to comply with AWS SDK standards. Specifically, this will support the use of expired IMDS credentials. This is useful because in the case of service degradation in IMDS which prevents credentials refresh, AWS will allow us to keep using the expired credentials.

When we use expired credentials, the CachedCredentialsProvider will continuously try to refresh them. To solve this, a new field called `nextRefresh` was added to the Credentials data class. When present, this will override any expiration times, and the providers will only try to refresh the credentials if the `nextRefresh` time has passed.

### \#718:
When receiving credentials with an expiration time, set the cached credentials' expiration time to the minimum of `expireCredentialsAfter` and the received expiration time. This will ensure we are refreshing credentials at the rate the user specifies.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-05 21:43 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +        if (previousCredentials != null &&
Is there a nicer way to do this null check? Previously I had:
```kotlin
previousCredentials?.run {
    this.nextRefresh?.run {
        if (clock.now() < this) {
            return previousCredentials as Credentials
        }
    }
}
```
and was torn between the two

2022-10-05 21:45 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +                    return previousCredentials ?: throw CredentialsProviderException("failed to load instance profile", ex)
is there a nice way to remove this duplicated `throw ...`? (i.e jump from the elvis operator to the else block)

2022-10-06 16:53 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +        }
**Question**: Is this the correct layer for this behavior? This means we'll effectively cache the credentials at this layer and _not_ try fetching new ones until `nextRefresh`. That sounds correct for a caching layer but not what I'd necessarily expect from the direct IMDS provider.

2022-10-06 16:58 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +        if (previousCredentials != null &&
I believe you could use the safe call operator and `takeIf` to clean this up slightly:

```kotlin
previousCredentials?.nextRefresh?.takeIf { Clock.now() < it }?.run {
    return previousCredentials as Credentials
}
```

2022-10-06 16:58 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +        if (previousCredentials != null &&
Why is the `as Credentials` cast necessary?

2022-10-06 17:55 UTC, aajtodd requested changes
Looks great overall. Couple questions and callouts (in addition to Ian's callout on thread safety)

2022-10-06 17:55 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +import java.io.IOException
fix: JVM only (not sure why this even compiles)

2022-10-06 17:55 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +        }
Yeah this seems to duplicate the cache behavior does it not?

2022-10-06 17:55 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +                    logger.info { STATIC_STABILITY_LOG_MESSAGE.format(DEFAULT_CREDENTIALS_REFRESH_SECONDS / 60) }
fix: It looks like [String.format](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/format.html) is JVM only.

2022-10-06 17:55 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +                if (creds.expiration!! < clock.now()) {
Question: Is this condition sufficient or should it include that `previousCredentials` wasn't `null` as well? I suppose it would be odd that IMDS would be returning expired creds so maybe this is ok?

2022-10-06 17:55 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +                var creds = Credentials(
Suggestion: I think we can restructure this to remove the mutable `creds` variable and the copy, something like:


```kotlin
val nextRefresh = if (resp.expiration != null && resp.expiration < clock.now()) {
     logger.warn(...)
     clock.now() + DEFAULT_CREDENTIALS_REFRESH_SECONDS.seconds
}else {
    null
}

return Credentials(..., nextRefresh = nextRefresh)
      .also { previousCredentials = it }

```

2022-10-06 17:55 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +                    logger.info { STATIC_STABILITY_LOG_MESSAGE.format(DEFAULT_CREDENTIALS_REFRESH_SECONDS / 60) }
Also probably log at `warn` level?

2022-10-06 17:55 UTC, aajtodd commented on aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProviderTest.kt
> +import java.net.SocketTimeoutException
fix: JVM only

2022-10-06 17:55 UTC, aajtodd commented on aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProviderTest.kt
> +    fun testDontRefreshUntilNextRefreshTimeHasPassed() = runTest {
fix/correctness: This seems like it should be a test on the `CachedCredentialsProvider` rather than this provider (related to Ian's [comment](https://github.com/awslabs/aws-sdk-kotlin/pull/719/files#r989279250) I suppose)

2022-10-06 17:58 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/CachedCredentialsProvider.kt
> +            val expirationTime = providerCreds.nextRefresh ?: minOf(providerCreds.expiration!!, (clock.now() + expireCredentialsAfter))
missed this in review: Missing test for this

2022-10-06 18:00 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +                    previousCredentials = previousCredentials?.copy(nextRefresh = clock.now() + DEFAULT_CREDENTIALS_REFRESH_SECONDS.seconds)
Another miss in my initial review.

Question: Should this be the `DEFAULT_CREDENTIALS_REFRESH_SECONDS`? I see our guidance is random between 5-10 minutes which would attempt to refresh a little more aggressively.

2022-10-06 18:36 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +        }
I think removing this would violate the guidelines for waiting 5-10 minutes between requests when the user has expired credentials and is using a direct IMDS provider, right?

This was added for the case when a user specifies a custom CredentialsProvider (i.e one consisting only of ImdsCredentialsProvider). If we remove this, then we will reach out to IMDS to get credentials [for every HTTP request](https://github.com/awslabs/smithy-kotlin/blob/cfa0fd3a30b4c50b75485786f043d4e2ad803f55/runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/DefaultAwsSigner.kt#L26), even if the returned credentials are expired. 

If we get expired credentials, we are supposed to wait 5-10 minutes before reaching out to IMDS again. This internal caching logic only runs when we have expired credentials (`nextRefresh != null`). If everything is operating normally, nextRefresh will remain null and there will be no caching.

2022-10-06 18:49 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +                if (creds.expiration!! < clock.now()) {
It is possible to receive expired credentials from IMDS when it's in static stability mode: 
> Test 1: SDK can use IMDS credential provider if first IMDS call returns expired credentials.

So you are proposing the conditional to be:
```kotlin
if (creds.expiration!! < clock.now() && previousCredentials != null)
```

I'm wondering what you think we should do if the incoming credentials are expired but previousCredentials is null? This can happen if we start an SDK client during an outage -- we will have no previousCredentials but the incoming credentials will be expired

2022-10-06 19:25 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +        }
Hmm I'm a little conflicted here. All of our providers work this way and would refresh on every HTTP request without a caching provider wrapping it. We even note this in some of the provider [documentation](https://github.com/awslabs/aws-sdk-kotlin/blob/230751e55e50afe97c263bcf2698202b959a18b0/aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ProfileCredentialsProvider.kt#L35-L36).

On one hand I would sort of like to keep that clean separation, on the other I can understand your point. 🤔 
@ianbotsf thoughts?

2022-10-06 19:30 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +                    previousCredentials = previousCredentials?.copy(nextRefresh = clock.now() + DEFAULT_CREDENTIALS_REFRESH_SECONDS.seconds)
I think either is fine I was mostly just asking if we think we should be more aggressive here or not

2022-10-06 19:30 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +                if (creds.expiration!! < clock.now()) {
> This can happen if we start an SDK client during an outage

Hmm good point. That seems sufficient then

2022-10-06 20:04 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +        if (previousCredentials != null &&
without `as Credentials`, I get this error: `Smart cast to 'Credentials' is impossible, because 'previousCredentials' is a mutable property that could have been changed by this time`

Another option that works is adding the non-null assertion `!!`
```kotlin
mu.withLock {
    previousCredentials?.nextRefresh?.takeIf { clock.now() < it }?.run {
        return previousCredentials!!
    }
}
```

I will change it to that.

2022-10-06 20:07 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +        }
I think the logic of using cached credentials from within the `ImdsCredentialsProvider` is correct _if_ we're in stability mode (because that's an implementation detail of how to use IMDS). If we're not in stability mode, I'd expect the provider to fetch fresh credentials every time `getCredentials` is called (just like every other provider does) and relegate _regular_ caching to the `CachedCredentialsProvider`.

How complicated would that be to implement?

2022-10-06 20:41 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +        }
There is no way to tell static stability is enabled with 100% certainty, so we can't really create any logic around that:
> IMDS doesn’t provide a formal flag, so the SDKs must always assume Static Stability is enabled.

One solution is to remove the `nextRefresh` logic from CachedCredentialsProvider entirely and leave the expired-credential caching solely in ImdsCredentialsProvider. In this scenario, when the default CachedCredentialsProvider is used and we are in static stability mode, the IMDS credentials will _always_ appear as expired. To fetch credentials, we walk the chain of CredentialsProviders, and when we reach ImdsCredentialsProvider, we will branch into this caching logic and return the credentials.

One downside is that we will have to check the entire chain, which could be costly. But the added overhead could be fixed [with this TODO](https://github.com/awslabs/aws-sdk-kotlin/blob/230751e55e50afe97c263bcf2698202b959a18b0/aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/CredentialsProviderChain.kt#L13) where we would cache the credential provider.

2022-10-06 20:52 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +        }
Will we know we're in stability mode the first time we call IMDS and get either expired credentials or some type of service error?

2022-10-06 21:05 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +        }
@ianbotsf We could but it would not be 100% certain. For example, there may have been a service error for some other reason (i.e there's an availability issue, but static stability is not enabled yet)

@aajtodd I am leaning towards the idea I proposed. One more possible downside is that we are adding a whole new field to Credentials (`nextRefresh`) just to be used in ImdsCredentialsProvider. Would it make sense to keep this as a member in ImdsCredentialsProvider instead of in the Credentials data class?

2022-10-10 19:48 UTC, aajtodd commented on aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProviderTest.kt
> +        for (i in 1..3) {
nit: `repeat(3) { ... }`

2022-10-10 19:48 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +                ex is SdkIOException ||
Lines 85-92 are nearly same as 99-107, we could probably consolidate

e.g.

```kotlin
val profileName = try {
    ... 
} catch(ex :Exception) {
    return useCachedCredentials(ex) ?: throw CredentialsProviderException("failed to load instance profile", ex)
}


val payload = try {
    ... 
} catch(ex :Exception) {
    return useCachedCredentials(ex) ?: throw CredentialsProviderException("failed to load credentials", ex)
}



private fun useCachedCredentials(ex: Exception): Credentials? = when(ex) {
    is SdkIOException || is EC2MetadataError && ex.statusCode == HttpStatusCode.InternalServerError.value -> {
        mu.withLock {
            previousCredentials?.run { nextRefresh = clock.now() + ... }
            previousCredentials        
         }
     }
     else -> null
}
```

2022-10-10 19:48 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +    private val mu = Mutex()
nit: You might clarify what this mutex protects:

e.g.

```kotlin
// protects previousCredentials + nextRefresh
private val mu = Mutex()
```

2022-10-10 21:18 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +    private var previousCredentials: Credentials? = null,
It was nice for testing purposes, but not necessary. I will refactor it and update the test cases

2022-10-10 22:05 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +public expect class SdkIOException : Exception // FIXME move this to the proper place when we do the larger KMP Exception refactor
When I switch this to `internal` or `private`, I get the following error in the JVM definition of SDKIOException:
```
Actual typealias 'SdkIOException' has no corresponding expected declaration The following declaration is incompatible because visibility is different:
internal final expect class SdkIOException : Exception /* = Exception */ defined in aws.sdk.kotlin.runtime.auth.credentials in file ImdsCredentialsProvider.kt
```

I played around with it for a while and this `expect` seems to be required to be public

2022-10-10 22:39 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +public expect class SdkIOException : Exception // FIXME move this to the proper place when we do the larger KMP Exception refactor
Expect and actual visibility has to match

2022-10-10 23:03 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +public expect class SdkIOException : Exception // FIXME move this to the proper place when we do the larger KMP Exception refactor
They were both matching in this case -- I tried all combinations and it does not compile when both are set to `internal`. This seems to be a common issue: https://youtrack.jetbrains.com/issue/KT-37316

It can be fixed by adding `@Suppress("ACTUAL_WITHOUT_EXPECT")` decorator to the JVM implementation. I will go that route unless anybody is against it?

2022-10-10 23:57 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +public expect class SdkIOException : Exception // FIXME move this to the proper place when we do the larger KMP Exception refactor
Ahh I see, because the type aliased actual differs in visibility. The suppression suggested seems fine then

2022-10-11 15:55 UTC, aajtodd approved these changes

2022-10-11 21:16 UTC, ianbotsf approved these changes
Looks pretty good to me!

2022-10-11 21:16 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ImdsCredentialsProvider.kt
> +                return previousCredentials
**Nit**: I believe this can be simplified to:

```
previousCredentials?.apply { nextRefresh = clock.now() + DEFAULT_CREDENTIALS_REFRESH_SECONDS.seconds }
```

2022-10-11 21:51 UTC, merged