feat: flexible checksums design
aws/aws-sdk-kotlin pull request #801
Opened 2022-12-29 19:35 UTC by lauzadis

This PR adds the flexible checksums design doc.

## Issue \#

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-01-04 14:04 UTC, aajtodd requested changes
This is a great start, couple comments/fixes suggested.

-----

On the preferred choice of `LazyAsyncValue` I'm not sure I agree. In part because `LazyAsyncValue` isn't really intended for this use case. It's just a `suspend` equivalent of [lazy](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/lazy.html). The main use case of `LazyAsyncValue` was/is to defer computing a value that is produced by some suspending computation. I can see where this definition _almost_ fits this use case. 

The crux of my issue is that `LazyAsyncValue` places absolutely no timing constraints on the consumer. You can call it whenever you want and it should execute and produce a result. The AWS chunked implementation cannot invoke it until the entire body is read. This works for this use case because the trailer is related to the body consumption but what if it wasn't? I think a better alternative here is to use [Deferred](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-deferred/) (which can be created by the producer with [CompletableDeferred](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-completable-deferred/)). A `Deferred` value has the advantage that it decouples the producer and consumer timing. A consumer can immediately invoke `await` and it won't complete until the producer sets a value for it. The other advantage is that deferred values support cancellation. 

I'm not sure if this is the alternative that was rejected, it wasn't clear but this would be my preferred choice for representing trailer header values. We should discuss as a group probably.

2023-01-04 15:29 UTC, lauzadis commented on docs/design/flexible-checksums.md
> +private val HashFunction.isSupported: Boolean get() = when (this) {
I changed the implementation to return null instead of throwing an exception -- I will update the doc

2023-01-04 15:31 UTC, lauzadis commented on docs/design/flexible-checksums.md
> +### Lazy Headers
Ok, that sounds better. I chose the name "Lazy Headers" to refer back to the original section where the design choice was introduced

2023-01-04 21:56 UTC, ianbotsf requested changes
Please also add a link to the new document in [docs/design/README.md](https://github.com/awslabs/aws-sdk-kotlin/blob/main/docs/design/README.md).

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +but the operation has the `requestChecksumRequired` property set, the SDK will fall back to the legacy behavior of computing the MD5 checksum.
**Style**: Sections without content besides other sections feel unnecessarily over-structured. In this case, the **Overview** subsection seems like the perfect introduction for the **Requests** section. I'd suggest just removing `## Overview`.

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +
**Comment**: It feels like **Requests** and **Responses** should be subsections of ~~**Design**~~ **Implementation**.

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +validating checksums present in responses.
**Nit**: This entire document is a "design". This section should probably be titled something like **Implementation** or **Specification**.

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +The `order` of AwsSigningMiddleware has already been set to 126, which ensures it will be executed towards the end of the mutate middleware stack,
**Nit**: AwsSigningMiddleware → `AwsSigningMiddleware`

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +For flexible checksums, we append the [checksum header name](#checksum-header-name) to the `x-amz-trailer` header.
**Style**: Avoid "we" in technical writing. It might be clearer here to say that "the checksum header name _will be appended_ to the `x-amz-trailer` header".

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +and adds it to the request headers. When this header is present, the rest of the flexible checksums request workflow is skipped.
**Style**: Elsewhere in this document (and generally) we refer to "requests" rather than "input". For consistency, I recommend following that convention in this section too.

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +When a user sets the `requestAlgorithmMember` property, they are choosing to opt-in to sending request checksums.
**Question**: I'm confused—`requestAlgorithmMember` is a property of a trait in a Smithy model and I do not see how users can "set" this value directly. Does this actually mean "when a user sets a value in the member identified by the `requestAlgorithmMember` property"?

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +```
**Style**: These `>` prefixes are unnecessary given this is already a preformatted block.

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +to the checksum header name.
**Style**: I believe `aws-chunked` is not the proper name of a feature (which is probably "[Chunked Upload](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html)") but rather a code literal used by systems that send/receive chunked streams. If so, we should probably monospace every mention of `aws-chunked` or use a proper name in its place.

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +However, it is wise to avoid tight coupling of the aws-chunked and flexible checksums features. The aws-chunked body should have
**Style**: wise → desirable

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +LazyAsyncValue is the SDK's pre-existing wrapper around Kotlin's [Lazy type](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-lazy/)
**Nit**: LazyAsyncValue → `LazyAsyncValue`

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +Today the aws-chunked reader has the following signature:
**Comment**: Our designs generally describe the system as it has been implemented after the design is completed. Using words like "today" to describe the prior state of the system or the now-deprecated design is confusing. It might be better to say "The previous implementation of the `aws-chunked` reader had the following signature" or "A naïve structure for the reader might be"...anything to indicate that what follows is _not_ current.

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +So, how will the value of the checksum be passed to the AwsChunked body?
**Nit**: AwsChunked vs aws-chunked

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +which maps String -> List<LazyAsyncValue&lt;String>>
**Nit**: String -> List<LazyAsyncValue&lt;String>> → `String -> List<LazyAsyncValue<String>>`

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +For efficiency, it is best for the SDK to compute the checksum as the user is consuming the response body.
**Question**: Does this only apply to streaming responses? I assume so since the caller does not "consume" non-streaming responses...they are returned inline and fully complete. Do we need additional description of what happens for non-streaming responses?

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +variable, and if it's present, will know that validation occurred.
**Nit**: variable → value

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +
**Question**: Neither this section nor its surrounding sections discuss what happens when validation yields a mismatch. Will we throw an exception? Leave it up to the user to compare expected and calculated values? Other?

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +
**Nit**: The following subsections are "appendices"—a collection in which each item is an "appendix". I suggest either renaming this section to `# Appendices` –or– removing this `# Appendix` section and updating the following sections to `# Appendix: Request Examples`, `# Appendix: Response Examples`, etc.

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +
**Comment**: It may be helpful to note in these examples that `requestAlgorithmMember` is `checksumAlgorithm` and to describe how the names `checksumSha256`, `checksumCrc32`, etc. are determined.

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +- CompletableFuture uses coroutines, which adds unnecessary cognitive load for developers
**Correctness**: `CompleteableFuture` _does not_ use coroutines...it uses Java-native concurrency primitives.

2023-01-04 21:56 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +    back since the data is not valid
**Style**: One cannot "claw back" a sent stream. It's probably more accurate to say a user may have to cancel, invalidate, or otherwise handle a downstream operation.

2023-01-04 22:46 UTC, lauzadis commented on docs/design/flexible-checksums.md
> +
Good question, I did not specify it here in the design. An exception will be thrown on checksum mismatch.

2023-01-04 23:20 UTC, lauzadis commented on docs/design/flexible-checksums.md
> +the SDK must use flexible checksums. Otherwise, if a request requires a checksum but
Yes, it is. I can clarify that here

2023-01-04 23:21 UTC, lauzadis commented on docs/design/flexible-checksums.md
> +For efficiency, it is best for the SDK to compute the checksum as the user is consuming the response body.
Yes, and that's something I'll need check in my implementation, because I'm not sure what would happen with a non-streaming response.

2023-01-11 22:28 UTC, ianbotsf reviewed
**Question**: Most of this design now seems to be [implemented in **smithy-kotlin**](https://github.com/awslabs/smithy-kotlin/pull/772). How much of this design is specific to **aws-sdk-kotlin**? Should the design be moved to the other repository?

2023-01-11 22:52 UTC, lauzadis commented on docs/design/flexible-checksums.md
> +it can throw exceptions if the computation was cancelled, threw an exception, or if the thread was interrupted while blocking
This is actually a part of the bulleted list, not its own sentence. I just broke it out onto a newline to prevent the Markdown line being too long, though I could capitalize every member of the bulleted lists if that seems better.

2023-01-11 22:57 UTC, lauzadis commented
> **Question**: Most of this design now seems to be [implemented in **smithy-kotlin**](https://github.com/awslabs/smithy-kotlin/pull/772). How much of this design is specific to **aws-sdk-kotlin**? Should the design be moved to the other repository?

Sure, if that's the heuristic the team uses to determine locating designs in **aws-sdk-kotlin** vs. **smithy-kotlin**. I thought it would be better here in **aws-sdk-kotlin** since the customization is specific to AWS services.

For what it's worth,`httpChecksum` is [documented](https://smithy.io/2.0/aws/aws-core.html#aws-protocols-httpchecksum-trait) as an "AWS-specific trait"

2023-01-11 23:02 UTC, ianbotsf commented on docs/design/flexible-checksums.md
> +it can throw exceptions if the computation was cancelled, threw an exception, or if the thread was interrupted while blocking
Is this meant to be a top-level bullet point in the list? If so, it's missing a leading `- `. It's currently rendering as part of the preceding line.

2023-01-12 14:34 UTC, aajtodd commented
> 

I think previously anything AWS we were putting in this repo but I think we'll eventually move AWS protocols (including trait support) into `smithy-kotlin` as a separate package. This repo will eventually (hopefully) just contain customization's required for AWS SDK Kotlin (and perhaps a small runtime component, e.g. `aws-config` is pretty specific to AWS SDK's). I could make an argument for both but being forward looking, probably relocate to `smithy-kotlin`, perhaps in a new "aws" subfolder of design or something. We can discuss as a team.

2023-01-12 14:44 UTC, aajtodd approved these changes
No blocking comments other than what Ian has already called out.

2023-01-12 14:44 UTC, aajtodd commented on docs/design/flexible-checksums.md
> +A new middleware is introduced at the `mutate` stage. This stage of the HTTP request lifecycle represents the last chance
nit: `mutate` is not the last chance to modify the request before sent out on the network (that would be `receive`).

2023-01-12 14:44 UTC, aajtodd commented on docs/design/flexible-checksums.md
> +the checksum will be immediately computed and injected under the appropriate header name.
question: I'm assuming this is only true for replayable streams/bodies?

2023-01-12 14:44 UTC, aajtodd commented on docs/design/flexible-checksums.md
> +For non-streaming responses, the entire response is loaded into memory at once. The SDK will validate the checksum prior to deserializing
question: Is this some flag passed to the middleware when constructed based on the model? The middleware otherwise will not be able to tell the difference between streaming and non streaming responses (all HTTP response bodies are basically "streaming"). 

Also keep in mind reading HTTP response bodies can only be done once, you'll have to copy the response into a new (e.g. `HttpBody.Bytes`) instance so that the deserializer can read it "again".

2023-01-13 14:31 UTC, lauzadis commented on docs/design/flexible-checksums.md
> +it can throw exceptions if the computation was cancelled, threw an exception, or if the thread was interrupted while blocking
I was intending for it to be part of the preceding line, but in hindsight it's not a useful bit of information so I'll remove it

2023-01-13 14:42 UTC, lauzadis commented on docs/design/flexible-checksums.md
> +For non-streaming responses, the entire response is loaded into memory at once. The SDK will validate the checksum prior to deserializing
If that's the case, then yeah I will probably need to pass a flag based on the model. Based on the current feedback on the implementation PR I will already need to refactor this validation middleware, and I'll make sure it works for both streaming and non-streaming responses.

2023-02-01 18:53 UTC, lauzadis commented
Moving to **smithy-kotlin** repo: https://github.com/awslabs/smithy-kotlin/pull/788

2023-02-01 18:53 UTC, closed without merging