refactor: track upstream client configuration changes
aws/aws-sdk-kotlin pull request #814
Opened 2023-01-13 15:24 UTC by aajtodd

## Issue \#

upstream: https://github.com/awslabs/smithy-kotlin/pull/778

## Description of changes

* refactors generated service client companion objects to inherit from `AbstractAwsSdkClientFactory` which moves `fromEnvironment()` into the runtime.
* Introduces `AwsSdkClientConfig` to give `region` a home
* Makes the same simplification to `AwsRuntimeTypes` that was applied upstream

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-01-13 15:24 UTC, aajtodd commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/client/AwsSdkClientConfig.kt
> +public interface AwsSdkClientConfig : SdkClientConfig {
Alternatively could move this to `AwsRegionConfig` mixin

2023-01-17 21:57 UTC, ianbotsf requested changes

2023-01-17 21:57 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
> +public abstract class AbstractAwsSdkClientFactory<
**Nit**: Missing KDocs on type parameters.

2023-01-17 21:57 UTC, ianbotsf commented on aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/client/AwsSdkClientConfig.kt
> +    public interface Builder {
**Nit**: Missing KDocs on public interface.

2023-01-18 23:44 UTC, lauzadis approved these changes

2023-01-19 17:27 UTC, ianbotsf approved these changes

2023-01-20 13:21 UTC, merged