feature: add sub-property support to config parser
aws/aws-sdk-kotlin pull request #854
Opened 2023-02-17 15:02 UTC by lucix-aws

In preparation for #206, add support for sub-properties in config.

## Description of changes
* Add support for sub-property continuations, e.g.:
```
[default]
foo = bar ; top-level property
baz = ; parent
  qux1 = 1 ; sub-property. note this "comment" is actually part of the value per configuration-file SEP
  qux2 = 2
```
* Refactor parsing pipeline that transforms input -> config profile map. Workflow is now:
`tokenize (handle all explicit parsing failures) -> build profile mapping (handle and log all dropping of valid-but-malformed values) -> merge`
* Continuations and sub-properties are now explicitly tokenized and handled in the profile mapping, rather than being pre-folded before tokenization
* Tokenization is now context-aware and will explicitly reject otherwise-valid tokens that are incorrectly positioned, rather than deferring and requiring later handling of what should be an explicit fail-fast scenario
* Organize parser components within package

Plumbing for s3-specific properties will be implemented as a follow-on PR.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-02-17 15:48 UTC, lucix-aws commented on aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/config/profile/SpecTestSuites.kt
> -      "name": "Profiles can contain multiple properties.",
FYI this is removed because it was a duplicated test case -- the one above it is identical.

2023-02-17 22:15 UTC, aajtodd approved these changes

2023-02-17 22:18 UTC, ianbotsf requested changes

2023-02-17 22:18 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/ParseFn.kt
> +        .splitWhitespace(limit = 2)
**Correctness**: This doesn't appear to handle whitespace between `[` and `profile`.

2023-02-17 22:18 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/Text.kt
> +internal fun String.isValidIdentifier(): Boolean = !any { it.isWhitespace() }
**Nit**: `!any` → `none`

2023-02-17 22:29 UTC, lucix-aws commented on aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/config/profile/SpecTestSuites.kt
> +        "errorContaining": "Encountered unexpected token"
You're correct that it has generalized all parsing errors, I felt the tradeoff was ideal given that the line of the failed parse is always included for all of these.

I also feel that the SEP is a bit disingenuous in the way it lists out the different "fail fast" cases, and that ultimately, all of them _are_ really more accurately represented as "unexpected token". For example, one of the cases is
- Property definitions without an = sign cause parsing to fail immediately.

But realistically, how would you even determine that something was _trying_ to be a property definition without that = sign? To me that implies there's some additional parsed state of "recognized token, but critically invalid".

For those reasons I would argue it's better to follow the intent of the SEP rather than the letter.

2023-02-17 22:31 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsConfigParser.kt
> +                if (containsKey(token)) continue
This is allowed per the SEP, it's valid to have two separate profile declarations with their own keys, you basically just treat it as one profile in the output. One of the existing unit tests (not shown in diff) does cover this case.

2023-02-17 22:33 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsConfigParser.kt
> +                }
Since the tokens are in declaration order after `tokenize`, the last defined value for the key will always win, which is intentional per the SEP.

2023-02-17 22:38 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt
>  public data class AwsProfile(
We had discussed that it was most likely incorrectly non-internal before, hence the change. I don't think any of those cases are strictly _off_ the table, though.

2023-02-17 22:38 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsConfigParser.kt
> +                currentProfile as Token.Profile
It's guaranteed within the scope of this code because the tokens are in declaration order (I believe the documentation for the `tokenize` function mentions this).

FWIW I'm not the world's biggest fan of having this implied context persist across two logically discrete pieces of code. Ultimately, since they're coupled and internal to the parser, I felt it was fine.

2023-02-17 22:41 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsConfigParser.kt
> +                currentProfile as Token.Profile
I did consider adding profile/parent information to the tokens for properties/sub-properties, that would allow you to ignore the order of the tokens (to some extent, you'd still have to know declaration order for the "last wins" part of building the map) and instead sort them and avoid having to trust that you're not going to incorrectly index at some point, but I just went back to the fact that this code is internal, and the interaction between `tokenize` and `toProfileMap` is static, and left it alone.

2023-02-17 22:44 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/FileLine.kt
> +}
Not sure what you mean? In the case of `isComment` here it's `trim()`ing the content before it makes that check. Profiles can certainly end with comments, I did note there's not really a clear directive on whether you can have leading whitespace on them, but since there's no difference between the two I didn't see the harm in ignoring it.

2023-02-17 22:44 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/FileType.kt
> +    ),
This is ported from what we had before, I'll double-check this.

2023-02-17 22:49 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/ParseFn.kt
> +        .splitWhitespace(limit = 2)
`splitWhitespace` here is a homespun utility in `Text.kt` and it filters out blank (i.e. `isBlank()`) segments.

There is an existing unit test that covers this as well.

2023-02-17 22:50 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/ParseFn.kt
> +        .splitWhitespace(limit = 2)
e.g.
```kt
fun main() {
	println(" 		  		 	  			 	profile 	 	 qux".splitWhitespace(limit = 2))
}

fun String.splitWhitespace(limit: Int): List<String> =
    trim().split(" ", "\t", limit = limit).filter(String::isNotBlank).map(String::trim)
```
gives us
`[profile, qux]`

2023-02-20 12:33 UTC, aajtodd commented on aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/config/profile/SpecTestSuites.kt
> +        "errorContaining": "Encountered unexpected token"
I think I was more concerned with the users ability to track down the issue, if the error contains the line/col number then it's probably good enough

2023-02-20 12:34 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/Token.kt
> +internal sealed class Token {
Are you suggesting `sealed interface` or just an `interface`? I think there is value in knowing the set of token implementations (aka sealed).

2023-02-20 15:31 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/Token.kt
> +internal sealed class Token {
Yes a `sealed interface`, sorry.

2023-02-20 15:49 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsConfigParser.kt
> +                currentProfile as Token.Profile
OK, and `tokenize` guarantees that a profile always precedes the first property?

This code seems to muddle the responsibilities of **lexing** (turning a text stream into tokens and categorizing them into types) and **parsing** (turning a token stream into a syntax tree, identifying context between elements). This means implicit contracts are present in disparate parts of the code, which make it difficult to follow and easy to break. I wonder if this code would be simpler and easier to read if those responsibilities were more clearly separated.

2023-02-20 15:50 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsConfigParser.kt
> +                }
It fees like we should emit a warning here. Users may be surprised if their config values are silently discarded, especially if they just don't scroll down far enough in their file.

2023-02-20 15:52 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/FileLine.kt
> +}
Sorry, I missed the `trim` in both of these methods.

2023-03-01 22:05 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/FileType.kt
> +    ),
FYI, these segments are passed through a `normalizePath` method downstream that explicitly handles home directory expansion.

2023-03-01 22:06 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
> +        coroutineContext.withRootTraceSpan(tracer.createRootSpan("fromEnvironment")) {
**Question**: unsure about the exact span hierarchy, but this seemed correct. This root span will then disappear in the built client, and we go back to creating root spans for each operation.

2023-03-02 15:01 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
> +            coroutineContext.withChildTraceSpan("resolveRegion") {
This seems unnecessary to have two child spans, what are we gaining?

2023-03-02 15:11 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
> +    >(private val clientName: String) : SdkClientFactory<TConfig, TConfigBuilder, TClient, TClientBuilder>
Question/Correctness: We have a property [serviceName](https://github.com/awslabs/smithy-kotlin/blob/cbf83d8bbe631ddd309f35fda08d36084bae1c02/runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/SdkClient.kt#L17) off `SdkClient` that isn't configurable. We just [codegen the override directly ](https://github.com/awslabs/smithy-kotlin/blob/a639523d2d09c3c73c6ddd5ad98f1cb19f9295a9/codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientGenerator.kt#L164). Should we just move this to a configurable property on `SdkClientConfig.Builder` (with it defaulted the way it is now via codegen)?

Taking a step back though, do we even need this property? If we aren't configured with a tracer we could probably just use the class name as a fallback. 

e.g.

```kotlin
DefaultTracer(LogingTraceProbe, builder::class.simpleName)
```

2023-03-02 15:14 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsConfigLoader.kt
> +            parse(coroutineContext.traceSpan, FileType.CONFIGURATION, platform.readFileOrNull(source.configPath)?.decodeToString()),
correctness: this is doing file IO on the wrong dispatcher thread potentially

```kotlin
withContext(SdkDispatchers.IO) {
    mergeProfiles (
        ... 
    )
}
```

2023-03-02 15:20 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsConfigParser.kt
> +private fun TraceSpan.warnParse(message: String) =
suggestion: Should probably be `inline` and take the `() -> Any` lambda as an argument instead of forcing the message to be formatted on every call

2023-03-02 15:47 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
> +            coroutineContext.withChildTraceSpan("resolveRegion") {
I mean, these are two different "events" that delegate somewhat deep, it seems useful to have the spans capture that, but no strong opinion.

2023-03-02 22:42 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsConfigParser.kt
> +    warn("AwsConfigParse", content = { contextMessage(message) })
**Nit**: There's no real class here (although that seems like it'd simplify passing around the `traceSpan`) but the file name is **AwsConfigParser** (with an "r"), which seems like a better choice for source component.

2023-03-02 22:42 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsConfigParser.kt
> +    warn("AwsConfigParse", content = { contextMessage(message) })
**Suggestion**: `contextMessage` has the capability to show a line number where the problem occurred but we don't use that here. I think it'd be especially useful in larger files to see where warnings are occurring. Could we enhance `Token` to remember its line number and then pass the token into this helper method so a line number can be passed to `contextMessage`?

2023-03-02 22:42 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt
> +    }
**Question**: These `require` calls will throw `IllegalArgumentException`. Is that what we want or would `ConfigurationException` be better?

2023-03-02 22:42 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
> +    >(private val clientName: String) : SdkClientFactory<TConfig, TConfigBuilder, TClient, TClientBuilder>
Using the builder class name as a default won't work...it's always `Builder`.

I like the idea of a configurable name retrievable from the builder. If we do, we should _move_ the service name default codegen from [the config-level tracer instantiation](https://github.com/awslabs/smithy-kotlin/blob/39e45f76eca4c4fee4f32202f4d2645bd324f91d/codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/util/RuntimeConfigProperty.kt#L139) and then reuse the value in constructing the `DefaultTracer` (rather than codegenning it twice).

2023-03-03 15:21 UTC, lucix-aws commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt
> +    }
Definitely the former, `IllegalArgumentException` is what is says, `ConfigurationException` right now is being used when there's some issue with the config itself (e.g. a retrieved profile value was invalid, we couldn't load a region anywhere, etc.)

2023-03-03 16:22 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt
> +    }
If anything wouldn't `IllegalStateException` be more appropriate than `IllegalArgumentException`? (i.e `check` not `require`)

2023-03-06 18:47 UTC, ianbotsf approved these changes

2023-03-06 18:47 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
> +        coroutineContext.withRootTraceSpan(tracer.createRootSpan("From environment")) {
**Nit**: I still don't think "From environment" is a helpful span title. It describes a method name or a strategy, not necessarily a taxonomical lifespan. I suggest something like "Initialization", "Config resolution", etc.

2023-03-06 18:47 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsConfigParser.kt
> +        add(line to token)
**Question**: This works but seems like it has a wide impact on type signatures elsewhere in the code. Would it be easier to make `FileLine` a property of `Token`? Then you wouldn't have to worry about `Pair<FileLine, Token>` or explicitly passing the line to `warnParse`.

2023-03-07 19:24 UTC, merged