feat(rt): retry certain HTTP errors (SRA)
aws/aws-sdk-kotlin pull request #894
Opened 2023-04-12 14:38 UTC by aajtodd

## Issue \#

upstream: https://github.com/awslabs/smithy-kotlin/pull/829

## Description of changes

Track upstream HTTP exception changes.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-12 15:05 UTC, lauzadis approved these changes

2023-04-17 21:26 UTC, ianbotsf requested changes

2023-04-17 21:26 UTC, ianbotsf commented on aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/retries/AwsDefaultRetryPolicy.kt
> +        "IDPCommunicationError" to Transient,
**Comment**: It looks like the specification has been updated since our original implementation and now the `"InternalError"` error code must also be treated as a `Transient` error.

2023-04-19 18:26 UTC, aajtodd commented on aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/retries/AwsDefaultRetryPolicy.kt
> +        "IDPCommunicationError" to Transient,
Discussed offline. We are going to punt on this for now since it's covered by https://github.com/awslabs/aws-sdk-kotlin/issues/199

2023-04-19 19:27 UTC, lauzadis approved these changes

2023-04-19 19:58 UTC, ianbotsf approved these changes

2023-04-19 20:01 UTC, merged