feat!: Resolve `LogMode` from environment
aws/aws-sdk-kotlin pull request #897
Opened 2023-04-13 19:28 UTC by lauzadis

This PR renames `SdkLogMode` to `LogMode`.

 It also enables resolving `LogMode` from the user's environment when a client is instantiated using `fromEnvironment()`.

Places checked (in priority order):
- `sdk.logMode` JVM system property
- `SDK_LOG_MODE` environment variable

Users can configure the following `LogMode` values: `LogRequest`, `LogResponse`, `LogRequestWithBody`, `LogResponseWithBody`.

Composite `LogMode` values are supported too, they can be configured by adding a pipe `|` between values. For example, `LogRequest|LogResponse`.

Misc. changes:
- Relocate `TestPlatformProvider` to **smithy-kotlin**, delete the `aws-runtime:testing` module

## Issue \#

#432 

## Description of changes

Currently `LogMode` can only be configured in code during SDK client initialization. This change enables users to configure the value without changing any code. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-13 19:42 UTC, aajtodd requested changes
Looks ok but couple things we need to address.

2023-04-13 19:42 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AwsSdkSetting.kt
> +    public object SdkLogMode : AwsSdkSetting<aws.smithy.kotlin.runtime.client.SdkLogMode>("AWS_SDK_LOG_MODE", "aws.sdkLogMode")
**fix**: This is AWS SDK Kotlin specific, we shouldn't pollute the `aws.` system property namespace. Java uses their own namespace for this ([example](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkSystemSetting.java#L128)).

So for us it should probably be `AWS_SDK_KOTLIN_SDK_LOG_MODE` and `aws.sdk.kotlin.sdkLogMode`

2023-04-13 19:42 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt
> +public val AwsProfile.sdkLogMode: SdkLogMode?
**fix**: Remove, we don't want to add non-standard profile properties to shared config files. Log mode will be via environment or system property only which I think is sufficient.

2023-04-13 20:34 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt
> +public val AwsProfile.sdkLogMode: SdkLogMode?
Sounds good, [the issue](https://github.com/awslabs/aws-sdk-kotlin/issues/432) originally referenced parsing from config files as a goal, but I can see why it would be good to avoid clashing profile properties

2023-04-14 11:54 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
> +            builder.config.sdkLogMode = builder.config.sdkLogMode ?: resolveSdkLogMode()
**Question**: Should we just have `resolveSdkLogMode()` be the default for the property type such that all generated clients (AWS SDK or not) benefit from this?

e.g.

```kotlin
override val sdkLogMode: SdkLogMode = builder.sdkLogMode ?: resolveSdkLogMode()
```

2023-04-14 14:08 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AwsSdkSetting.kt
> +    public object SdkLogMode : AwsSdkSetting<aws.smithy.kotlin.runtime.client.SdkLogMode>("AWS_SDK_KOTLIN_SDK_LOG_MODE", "aws.sdk.kotlin.sdkLogMode")
**Question**: Repeated words in multi-word identifiers always feel redundant and redundant to me. Can we remove one of the "SDK"s from these identifiers?

Maybe a somewhat larger namespacing question would be: is `AWS_SDK_KOTLIN`/`aws.sdk.kotlin` how we want to identify Kotlin SDK-specific config options? Or should we build towards a future when more (perhaps _all_) SDKs have similar options for configuring logging?

2023-04-14 14:13 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/ResolveSdkLogMode.kt
> +): SdkLogMode = AwsSdkSetting.SdkLogMode.resolve(platformProvider) ?: SdkLogMode.Default
**Question**: Under what circumstances would the `resolve` call return `null`?

2023-04-14 14:23 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AwsSdkSetting.kt
> +    public object SdkLogMode : AwsSdkSetting<aws.smithy.kotlin.runtime.client.SdkLogMode>("AWS_SDK_KOTLIN_SDK_LOG_MODE", "aws.sdk.kotlin.sdkLogMode")
I generally agree but I'm leaning towards leaving the redundant "SDK" because it reflects the exact name of the field being configured, `SdkLogMode`

> always feel redundant and redundant to me

is this a joke about redundancy? 😄

2023-04-14 15:11 UTC, lauzadis commented on aws-runtime/aws-config/api/aws-config.api
> +
I took a look around, and I don't think it's possible

2023-04-14 16:32 UTC, lauzadis commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
> +            builder.config.sdkLogMode = builder.config.sdkLogMode ?: resolveSdkLogMode()
I tried but this is not easily done due to our dependencies. Adding the `resolveSdkLogMode` function as the default would require adding a dependency on aws-sdk-kotlin to smithy-kotlin to get that function imported.

It's also not possible to relocate the function because it relies on `AwsSdkSetting` which is also in aws-sdk-kotlin

2023-04-17 12:19 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
> +            builder.config.sdkLogMode = builder.config.sdkLogMode ?: resolveSdkLogMode()
Well we could have an equivalent `SdkSetting` in `smithy-kotlin`. I don't feel super strongly but if we force it to be only consumable `fromEnvironment()` then customers won't be able to enable additional logging without a code change potentially. Maybe thats ok 🤔

2023-04-17 12:21 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AwsSdkSetting.kt
> +    public object SdkLogMode : AwsSdkSetting<aws.smithy.kotlin.runtime.client.SdkLogMode>("AWS_SDK_KOTLIN_SDK_LOG_MODE", "aws.sdk.kotlin.sdkLogMode")
> Or should we build towards a future when more (perhaps all) SDKs have similar options for configuring logging?

I think this is solvable though by allowing multiple environment variables and system properties. If there are new cross SDK environment settings added that we have kotlin specific ones for we can just set a priority for the new settings.

2023-04-17 15:44 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
> +            builder.config.sdkLogMode = builder.config.sdkLogMode ?: resolveSdkLogMode()
Many of the settings in `AwsSdkSetting` take effect regardless of `fromEnvironment()` though. `fromEnvironment()` is mostly there for dealing with the fact that if you aren't explicit we may have to do _some_ work that involves I/O to resolve credentials provider and potentially region. Things that affect debuggability should probably be easy to consider with just an environment change regardless of how the client is constructed. If they set an `SdkLogMode` explicitly it will of course still take precedence.

2023-05-01 20:10 UTC, ianbotsf approved these changes

2023-05-01 20:10 UTC, ianbotsf commented on aws-runtime/aws-core/build.gradle.kts
>          }
**Nit**: This entire source set block can be deleted now that there are no dependencies.

2023-05-02 13:38 UTC, aajtodd approved these changes

2023-05-02 20:10 UTC, merged