misc: update closeability of various types of `CredentialsProvider`
aws/aws-sdk-kotlin pull request #936
Opened 2023-06-02 21:22 UTC by lauzadis

## Issue \#

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-06-05 18:11 UTC, ianbotsf requested changes

2023-06-05 18:11 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/SsoCredentialsProvider.kt
>      private val httpClient: HttpClientEngine? = null,
**Correctness**: This seems wrong. The client's lifetime is managed by the caller _if they provide one_. But if they don't, then `SsoClient` and `SsoTokenProvider`/`SsoOidcClient` will create new clients (different instances!) and we'll never explicitly close them, leaking resources. I think `SsoCredentialsProvider` _should_ be closeable and should default the client to `DefaultHttpEngine` at the provider level before passing to `SsoClient` and `SsoTokenProvider`/`SsoOidcClient`. We should in turn close the underlying `SsoClient` and `SsoTokenProvider`/`SsoOidcClient`.

Similar comment applies to `StsAssumeRoleCredentialsProvider` and `StsWebIdentityCredentialsProvider`.

2023-06-06 13:03 UTC, aajtodd reviewed
> Added default HTTP client engines to ProfileCredentialsProvider and DefaultChainBearerTokenProvider. These providers had an issue because the httpClient parameter in the constructor is nullable but was being treated as non-null. Instead, we should check if it's null, and if it is, create a DefaultHttpEngine which will be managed and closed when the provider is closed. This is [already how it's done in EcsCredentialsProvider](https://github.com/awslabs/aws-sdk-kotlin/blob/e233721ecbc368f5465ee963b7ecb5d880fc69e1/aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/EcsCredentialsProvider.kt#L68-L69) today, just extending it to these other providers.

I don't think this is necessary. The STS and SSO credential providers basically treat the engine as a pass through parameter to the underlying service clients. If it's `null` the service clients will instantiate one for you (expensive), if it's not then it's cheap to instantiate them. The reason ECS creates one if it's `null` is there is no underlying service client so we have to handle the engine ourselves in the credential provider since it's not handled for us by a generated client (same thing in IMDS cred provider).

2023-06-06 13:03 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/DefaultChainBearerTokenProvider.kt
> +    private val engine = httpClient ?: DefaultHttpEngine()
I don't think we need to do this, I'll comment on the overall PR about this more.

2023-06-06 18:38 UTC, ianbotsf approved these changes

2023-06-06 18:50 UTC, aajtodd approved these changes

2023-06-06 19:31 UTC, merged