feat: route53 custom error unmarshalling
aws/aws-sdk-kotlin pull request #961
Opened 2023-06-23 19:09 UTC by 0marperez

## Issue \#

Github issue https://github.com/awslabs/aws-sdk-kotlin/issues/242

## Description of changes
Implements route 53 custom error unmarshalling for `InvaildChangeBatchResponse`. Tests included.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-06-23 20:04 UTC, ianbotsf commented on .changes/7f80de87-a59a-420e-a175-c21a89f93fe9.json
> +}
**Suggestion**: This fixes a bug, right? Customers won't get the correct exception type today?

Also, this description is not very meaningful to customers. I suggest something like ``"Correctly handle and throw `InvaildChangeBatch` responses from Route53"``.

2023-06-23 20:07 UTC, 0marperez commented on .changes/7f80de87-a59a-420e-a175-c21a89f93fe9.json
> +}
Yeah, I wasn't sure what to name it. I'll change it

2023-06-23 20:09 UTC, 0marperez commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/CustomErrorUnmarshalling.kt
> +
A good amount, let me see what I can do

2023-06-23 20:34 UTC, lauzadis commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/route53/CustomErrorUnmarshallingIntegration.kt
> +class CustomErrorUnmarshallingIntegration : KotlinIntegration {
Could you give this a more precise name like `ChangeResourceRecordSetsUnmarshallingIntegration`? It helps when using the IDE search functionality

2023-06-23 20:34 UTC, lauzadis commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/CustomErrorUnmarshalling.kt
Generally the file's name should match the class it's defining (in this case, `ChangeResourceRecordSetsOperationDeserializer`)

2023-06-23 20:34 UTC, lauzadis commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/CustomErrorUnmarshalling.kt
> +import aws.sdk.kotlin.services.route53.model.ChangeResourceRecordSetsResponse
The patterns seem fine, but I noticed we're missing the custom rules in **aws-sdk-kotlin**, they're [only in **smithy-kotlin**](https://github.com/awslabs/smithy-kotlin/tree/b2643e0f13031dbb6f212d4797f7baaac1997136/ktlint-rules/src/main/kotlin/software/aws/ktlint/rules). I made a [small backlog item](https://github.com/orgs/awslabs/projects/45/views/1?pane=issue&itemId=31624164) to fix this.

2023-06-23 20:40 UTC, lauzadis commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/route53/CustomErrorUnmarshallingIntegration.kt
Can you add a few test cases for this integration? Similar to [this test](https://github.com/awslabs/aws-sdk-kotlin/blob/main/codegen/smithy-aws-kotlin-codegen/src/test/kotlin/aws/sdk/kotlin/codegen/customization/s3/ContinueIntegrationTest.kt) for a custom S3 integration

2023-06-26 14:18 UTC, 0marperez commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/CustomErrorUnmarshalling.kt
> +
Turns out none of it. Ideally I would do that but a lot of that code as marked as private or internal. The only function that is public (`parseRestXmlErrorResponse`) I ended up modifying.

2023-06-28 20:09 UTC, ianbotsf approved these changes
Looks pretty good. A few minor points left...fix and ship!

2023-06-28 20:09 UTC, ianbotsf commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/ChangeResourceRecordSetsUnmarshalling.kt
> +) : RestXmlErrorDetails
**Question**: Do we need these classes? Couldn't the deserializers return `ErrorDetails?` directly?

2023-06-28 20:09 UTC, ianbotsf commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/route53/ChangeResourceRecordSetsUnmarshallingIntegration.kt
> +            writer.write("#L\naws.sdk.kotlin.services.route53.internal.parseCustomXmlErrorResponse(payload) ?: #L", lines?.get(0) ?: "", lines?.get(1) ?: "")
**Nit**: Solely referring to the original value with this lines list is pretty inscrutable. I suggest giving each line a clearer name so that it's easier to understand what's going on here. We can also clean up the null checking by just requiring a non-null value up front:

```kotlin
requireNotNull(originalValue) { "Unexpectedly empty original value" }
val (nullCheckLine, parseLine) = originalValue.split("\n", limit = 2)
writer.write("#L", nullCheckLine)
writer.write("aws.sdk.kotlin.services.route53.internal.parseCustomXmlErrorResponse(payload) ?: #L", parseLine)
```

2023-06-28 20:29 UTC, lauzadis approved these changes
Great! No comments outside of what Ian already had.

2023-06-29 12:48 UTC, aajtodd requested changes

2023-06-29 12:48 UTC, aajtodd commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/route53/ChangeResourceRecordSetsUnmarshallingIntegration.kt
> +            requireNotNull(originalValue) { "Unexpectedly empty original value" }
**nit**: `checkNotNull` would be more appropriate

`require*` functions throw illegal argument exception whereas `check` throws illegal state exception.

Though neither of these should be required..see my other comment.

2023-06-29 12:48 UTC, aajtodd commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/route53/ChangeResourceRecordSetsUnmarshallingIntegration.kt
> +            val (nullCheckLine, parseLine) = originalValue.split("\n", limit = 2)
**fix**: This is making a lot of assumptions. It seems to assume that the format of this will always be:

```kotlin
        checkNotNull(payload){ "unable to parse error from empty response" }
        parseXyz(payload)
```

This isn't true for every protocol nor is it true in general once you introduce a section other section writers could manipulate it. 

This should likely just wholesale replace the section given it's two lines of code.

2023-06-29 14:57 UTC, 0marperez commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/ChangeResourceRecordSetsUnmarshalling.kt
> +) : RestXmlErrorDetails
One of the deserializers can, the other can't. I can have the one that can return `ErrorDetails?` do that but I would have to leave the other data class in there for the one that can't.

2023-06-30 17:37 UTC, ianbotsf approved these changes

2023-06-30 18:50 UTC, aajtodd requested changes

2023-06-30 18:50 UTC, aajtodd commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/route53/ChangeResourceRecordSetsUnmarshallingIntegration.kt
> +                    write("builder.message = it.message")
**correctness**: This ignores the other fields possible like request ID. We already go through the process of deserializing this type. I think it might be better to just return the built exception type and throw it.

e.g.

```kotlin
parseCustomInvalidChangeBatchErrorResponse(payload)?.let {
     setAseErrorMetadata(it.exception, wrappedResponse, it.errorDetails)
     throw it.exception
}
```

2023-06-30 18:50 UTC, aajtodd commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/ChangeResourceRecordSetsUnmarshalling.kt
> +private object InvalidChangeBatchMessageDeserializer {
**question**: This is a nested type right? Can we not just re-use the generated deserializer for this then?

2023-06-30 18:50 UTC, aajtodd commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/ChangeResourceRecordSetsUnmarshalling.kt
> +public suspend fun parseCustomXmlErrorResponse(payload: ByteArray): ErrorDetails? {
As I noted elsewhere we go through the process of deserializing the exception type here let's not lose all that work. Instead just return the built exception and the error details together as a pair or something and then you can just throw it.

2023-07-06 13:51 UTC, 0marperez commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/ChangeResourceRecordSetsUnmarshalling.kt
> +private interface RestXmlErrorDetails {
It was there from the copy and pasting I did and was necessary for that code to work. I modified things and it's no longer there anymore

2023-07-06 13:52 UTC, 0marperez commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/ChangeResourceRecordSetsUnmarshalling.kt
> +private object InvalidChangeBatchMessageDeserializer {
I modified things and it's not exactly the same so no

2023-07-06 15:25 UTC, aajtodd commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/ChangeResourceRecordSetsUnmarshalling.kt
> +private object InvalidChangeBatchMessageDeserializer {
Why is the generated deserializer not usable as is?

2023-07-06 16:19 UTC, 0marperez commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/ChangeResourceRecordSetsUnmarshalling.kt
> +private object InvalidChangeBatchMessageDeserializer {
Because of [this](https://github.com/awslabs/smithy-kotlin/blob/3e1d8618b0090b218461cffdcce20619d6b4119b/runtime/protocol/aws-xml-protocols/common/src/aws/smithy/kotlin/runtime/awsprotocol/xml/RestXmlErrorDeserializer.kt#L105C38-L105C38) line I believe. It should be `Messages` instead of `Error`. But I could be wrong

2023-07-06 17:59 UTC, aajtodd commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/ChangeResourceRecordSetsUnmarshalling.kt
> +private object InvalidChangeBatchMessageDeserializer {
I see now it's not a nested type it's just a list of string. Ok I have further questions now, new comments incoming.

2023-07-06 18:05 UTC, aajtodd commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/ChangeResourceRecordSetsUnmarshalling.kt
> +                            if (messages == null) messages = deserializeString() else messages += "\n" + deserializeString()
**correctness**: This is modeled as a list field why are we joining it to a string with `\n`?

2023-07-06 18:05 UTC, aajtodd commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/ChangeResourceRecordSetsUnmarshalling.kt
> +    builder.message = messages
**correctness**: Why are we setting `message` to the result of parsing the list field? Also what if it populates both `Message` and `Messages`?

e.g.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<InvalidChangeBatch xmlns="https://route53.amazonaws.com/doc/2013-04-01/">
  <Messages>
    <Message>Message from list</Message>
  </Messages>
  <Message>Some other message</Message>
  <RequestId>b25f48e8-84fd-11e6-80d9-574e0c4664cb</RequestId>
</InvalidChangeBatch>
```

2023-07-06 19:30 UTC, 0marperez commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/ChangeResourceRecordSetsUnmarshalling.kt
> +                            if (messages == null) messages = deserializeString() else messages += "\n" + deserializeString()
I see how it looks like the `Messages` field here because of the variable but it's `Message` which is a String. I am assuming a response that looks like this here:

```
<?xml version="1.0" encoding="UTF-8"?>
<InvalidChangeBatch xmlns="https://route53.amazonaws.com/doc/2013-04-01/">
  <Messages>
    <Message>Tried to create resource record set duplicate.example.com. type A, but it already exists</Message>
    <Message>Tried to create resource record set duplicate.example.com. type B, but it already exists</Message>
  </Messages>
  <RequestId>b25f48e8-84fd-11e6-80d9-574e0c4664cb</RequestId>
</InvalidChangeBatch>
```

Is this even right/possible?

2023-07-06 19:30 UTC, 0marperez commented on services/route53/common/src/aws/sdk/kotlin/services/route53/internal/ChangeResourceRecordSetsUnmarshalling.kt
> +    builder.message = messages
**Why are we setting message to the result of parsing the list field?** : 
I'm setting the `Message` value here which is a String not a String list. That variable name is pretty confusing and makes it seem like the `Messages` field. I'll change it
 
**What if it populates both Message and Messages?** : 
So I don't populate `Messages` right now I only extract the `Message`. I also asked Monday if I had to worry about seeing a `Message` not inside a `Messages` tag and got told that it shouldn't happen. So that's something we have to look out for as well?

2023-07-07 13:51 UTC, aajtodd approved these changes

2023-07-07 13:51 UTC, aajtodd commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/core/AwsHttpBindingProtocolGenerator.kt
> +            .declareSection(ProtocolErrorDeserialization) { }
**nit**: you don't need the empty `{ }` it's already the [default](https://github.com/awslabs/smithy-kotlin/blob/a639523d2d09c3c73c6ddd5ad98f1cb19f9295a9/codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/AbstractCodeWriterExt.kt#L124)

2023-07-07 15:11 UTC, merged