fix: s3 custom treatment getbucketlocation response
aws/aws-sdk-kotlin pull request #989
Opened 2023-07-19 14:37 UTC by 0marperez

## Issue \#
[194](https://github.com/awslabs/aws-sdk-kotlin/issues/194) - Custom treatment of `GetBucketLocation` response

## Description of changes

This was previously fixed using a customization but it left out error deserialization and deserialization of both wrapped and unwrapped non-error responses. Both possibilities are accounted for now

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-07-19 16:54 UTC, aajtodd requested changes
I think we should fix this by implementing support generically for [@s3UnwrappedXmlOutput trait](https://smithy.io/2.0/aws/customizations/s3-customizations.html#aws-customizations-s3unwrappedxmloutput-trait).

This could be done by:
1. Add a new `FieldTrait` for `XmlUnwrappedStruct` or similar and implement support in the [XmlDeserializer](https://github.com/awslabs/smithy-kotlin/blob/38b4a024357ff508d0e3066fdf311061ff32ccae/runtime/serde/serde-xml/common/src/aws/smithy/kotlin/runtime/serde/xml/XmlDeserializer.kt#L42) for it.
2.  Either override the descriptor generator for the S3 generator OR define our own generic trait for this and map the `s3UnwrappedXmlOutput` to our own generic trait. Then `smithy-kotlin` just operates on our own trait and a customization can preprocess the model to map `s3UnwrappedXmlOutput` to whatever we are looking for/define.

2023-07-26 16:45 UTC, ianbotsf commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/UnwrappedXMLOutputIntegration.kt
> +class UnwrappedXMLOutputIntegration : KotlinIntegration {
**Style**: Generally our names should follow PascalCase, including treating abbreviations like "XML" as regular words for the purposes of capitalization (e.g., `UnwrappedXmlOutputIntegration`).

2023-07-26 16:45 UTC, ianbotsf commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/UnwrappedXMLOutputIntegration.kt
> +            }
**Question**: Why do we need to check shape IDs from an allowlist? Why can't we just detect the `aws.customizations#s3UnwrappedXmlOutput` trait and then apply the new `UnwrappedXMLOutput` trait?

```kotlin
when {
    shape is StructureShape && shape.hasTrait<S3UnwrappedXmlOutputTrait>() ->
        shape.toBuilder().addTrait(UnwrappedXMLOutput()).build()

    else -> shape
}
```

2023-07-26 19:01 UTC, aajtodd commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/UnwrappedXMLOutputIntegration.kt
> +            }
Yeah that seems cleaner.

2023-07-26 19:01 UTC, aajtodd commented on services/s3/common/src/aws/sdk/kotlin/services/s3/internal/GetBucketLocationUnwrappedDeserializer.kt
> +internal fun deserializeWrapped(builder: GetBucketLocationResponse.Builder, payload: ByteArray) {
**fix**: We shouldn't need this now right?

2023-07-26 19:01 UTC, aajtodd commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/GetBucketLocationDeserializerIntegration.kt
>  class GetBucketLocationDeserializerIntegration : KotlinIntegration {
**fix**: Shouldn't need this now either right?

2023-07-28 16:41 UTC, ianbotsf commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/UnwrappedXmlOutputIntegration.kt
> +    }
**Comment**: We don't need a full `mapShapes` call to find the initial set of structs. We can just iterate through the model directly:

```kotlin
override fun preprocessModel(model: Model, settings: KotlinSettings) {
    val unwrappedStructures = model
        .operationShapes
        .filter { it.hasTrait<S3UnwrappedXmlOutputTrait>() }
        .map { it.outputShape }
        .toSet()
    return ModelTransformer
        .create()
        .mapShapes(model) { shape ->
            when {
                shape.id in unwrappedStructures ->
                    shape.toBuilder().addTrait(UnwrappedXmlOutput()).build()
                else -> shape
            }
        }
}
```

2023-07-28 16:41 UTC, ianbotsf commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/UnwrappedXmlOutputIntegration.kt
> +                        shape
**Question**: Is checking for `outputShape != smithy.api#Unit` important here? It seems like that would be a malformed model since there's no output to unwrap.

2023-07-28 16:41 UTC, ianbotsf commented on codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/UnwrappedXmlOutputIntegration.kt
> +                        shape.toBuilder().addTrait(UnwrappedXmlOutput()).build()
**Question**: Is checking for `shape is StructureShape` important here? It seems like the only things we add to the list are output shapes from operations marked with `S3UnwrappedXmlOutputTrait`, which _must_ be structures right?

2023-07-28 16:41 UTC, ianbotsf commented on services/s3/common/test/aws/sdk/kotlin/services/s3/internal/GetBucketLocationOperationDeserializerTest.kt
> +    }
**Question**: I'm confused by this test. Why is the expected output `UsWest2` when response XML stated `us-west-2`?

2023-07-31 14:12 UTC, aajtodd approved these changes

2023-08-07 15:36 UTC, lauzadis approved these changes

2023-08-07 15:36 UTC, lauzadis commented on codegen/smithy-aws-kotlin-codegen/src/test/kotlin/aws/sdk/kotlin/codegen/customization/s3/UnwrappedXmlOutputIntegrationTest.kt
> +        .toSmithyModel()
You can grab this function from https://github.com/awslabs/aws-sdk-kotlin/blob/s3-custom-treatment-getbucketlocation-response/codegen/smithy-aws-kotlin-codegen/src/test/kotlin/aws/sdk/kotlin/codegen/testutil/ModelUtil.kt#L7 instead of duplicating it

Note this wasn't available when you first created this PR, I merged it in sometime after :)

2023-08-08 15:35 UTC, merged