feat: make user-supplied region available to credentials providers
aws/aws-sdk-kotlin pull request #997
Opened 2023-07-26 04:07 UTC by 0marperez

## Issue \#
[583](https://github.com/awslabs/aws-sdk-kotlin/issues/583) - Make user-supplied region available to config resolution providers

## Description of changes

There are several places where config resolution providers require bootstrapping region, which is possibly present in user-supplied client config. This fixes this issue by making region available via attributes/execution context 

Also look at: 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-07-26 16:54 UTC, ianbotsf commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ProfileCredentialsProvider.kt
> +        val region = asyncLazy { region ?: profileOverride?.getOrNull("region") ?: attributes.getOrNull(AttributeKey("region")) ?: resolveRegion(platformProvider) }
**Question**: Does this work? I'd expected we'd need the `"AwsRegion"` attribute, which is already defined as [`AwsClientOption.Region`](https://github.com/awslabs/aws-sdk-kotlin/blob/74c3a2d49632d6ac97177078d85829846f4bf11d/aws-runtime/aws-core/common/src/aws/sdk/kotlin/runtime/client/AwsClientOption.kt#L19).

2023-07-27 12:56 UTC, aajtodd requested changes

2023-07-27 12:56 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ProfileCredentialsProvider.kt
> +        val region = asyncLazy { region ?: profileOverride?.getOrNull("region") ?: attributes.getOrNull(AttributeKey("region")) ?: resolveRegion(platformProvider) }
Yes we need to use the existing attribute, we should _almost_ never inline an attribute key like this.

2023-07-27 12:57 UTC, aajtodd commented on aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/ProfileCredentialsProvider.kt
> +        val region = asyncLazy { region ?: profileOverride?.getOrNull("region") ?: attributes.getOrNull(AttributeKey("region")) ?: resolveRegion(platformProvider) }
Also we should have a new unit test for this

2023-07-31 14:10 UTC, aajtodd approved these changes

2023-08-07 16:35 UTC, lauzadis approved these changes

2023-08-07 20:10 UTC, merged